### ISSUE TITLE
Running pihole -g resets list

### ISSUE THREAD

**Issue by josemalone** [notracking/hosts-blocklists#1]
Using PH 2.6.3, and following the directions. 

After doing `pihole -g` the `adlist.default` file is put in its original state like it's being rewritten. I was expecting my previous saved changes to stick.

>
>- Uncomment the following two lines in /etc/pihole/adlist.default
>
>https://raw.github.com/notracking/hosts-blocklists/master/hostnames.txt
>https://raw.github.com/notracking/hosts-blocklists/master/domains.txt
>
>-     Comment out any other list that is already included
>-     Update blocklists with `pihole -g`

**Comment by rotational467** [comment]
You need to create your own copy of the adlists file, and modify that one (use sudo where necessary if not running as root):

`cd /etc/pihole
cp adlists.default adlists.list
nano adlists.list`

Make your changes in the adlists.list file, then run `pihole -g`.  You can check the Pi-hole github page if you need a fresh copy of the adlists.default file.

**Comment by notracking** [comment]
I provided you with the incorrect instructions on how to update the PiHole list. Their adlists.list states the actual correct procedure on how to do this. Thank you for the feedback! I updated the README.
