### ISSUE TITLE
Easylist - vokskdqa.com

### ISSUE THREAD

**Issue by HellboyPI** [notracking/hosts-blocklists#101]
I was seeing a lot of queries in my network to "vokskdqa.com" domain. This is a malicious domain and it is in the [easy list](https://easylist-downloads.adblockplus.org/easylist.txt). The problem is, it is not in your domains or hostnames list although the easylist is included in the sources.

Could you please check why it is not included?

**Comment by notracking** [comment]
No, been checking on this and it will cause to much trouble. $third-party are marked in _most_ lists as $third-party for a good reason.
