### ISSUE TITLE
kijiji messaging

### ISSUE THREAD

**Issue by ve6rah** [notracking/hosts-blocklists#104]
I have noticed that hostnames.txt contains an entry for mingle.kijiji.ca
This blocks the messaging features within the Kijiji app. I've had to whitelist it on my end.

On a side-note, is there an easy "whitelist" option in DNSMasq that would override these blacklists?

**Comment by notracking** [comment]
Fixed! Changes will be visible with the next autoupdate.

You can whitelist by using `grep` or `sed` right after you've downloaded the lists.

Or in dnsmasq you could simply add another list containing your whitelisted entries and forcing them to a given dns in the format `address=/unblockme.com/1.1.1.1` I believe that you should your whitelist file first before loading the regular blocklists.
