### ISSUE TITLE
voxmedia.com is blocked at domains.txt and made broken functionality on some sites

### ISSUE THREAD

**Issue by kyrios21** [notracking/hosts-blocklists#106]
It made the comments section is not shown at all. Even we can't post comment.
SBNation have some portals for all sports fans all over the world.
managingmadrid.com ==> Real Madrid fans community
barcablaugranes.com ==> Barcelona FC
bavarianfootballworks.com ==> Bayern Munich
blackwhitereadallover.com ==> Juventus FC
As Madrid fan, I'm no longer able to read comments from other fans as well as I can't post comment.
Please check?

**Comment by notracking** [comment]
Whitelisted, but you will get the following filters in return (comments will work though).

- :: providence.voxmedia.com
- :: optimize-stats.voxmedia.com
- :: phonograph2.voxmedia.com
