### ISSUE TITLE
CBC Comments section

### ISSUE THREAD

**Issue by ve6rah** [notracking/hosts-blocklists#109]
Hello,

The comments section of the website www.cbc.ca relies on viafoura.net which is currently blocked in domains.txt whitelisting that entry seems to solve it

Thanks.

**Comment by ve6rah** [comment]
Just to update, it looks like some articles use viafoura.net in the comments section, whereas others use api.viafoura.co which is in hostnames.txt. I've whitelisted both on my end to make the comments work on all the articles I've found so far.

**Comment by notracking** [comment]
Thank you! I've added them to the whitelist, changes will be visible with the next autoupdate.
