### ISSUE TITLE
hockeyapp.net

### ISSUE THREAD

**Issue by ve6rah** [notracking/hosts-blocklists#112]
Good morning,

Our company uses hockeyapp.net for beta testing apps before they are loaded onto the iOS app store or Google Play.

This domain appears in domains.txt and I had to whitelist it to access apps hosted there.

**Comment by notracking** [comment]
I will whitelist `hockeyapp.net`, but then `gate.hockeyapp.net` will be added to the hostnames filters.
I'm not sure if this will have any negative effect, if so please open a new ticket.

Changes will be visible after the next auto update!

**Comment by 3xploiton3** [comment]
![](https://i.imgur.com/1dC6SRb.jpg)
![](https://i.imgur.com/GUBEwai.jpg)
