### ISSUE TITLE
CTV News Videos

### ISSUE THREAD

**Issue by ve6rah** [notracking/hosts-blocklists#113]
The ctvnews.ca website uses cdns.gigya.com to distribute their video content.
gigya.com appears in domains.txt

Can we either whitelist it, or make it a more specific target?

**Comment by notracking** [comment]
Videos seem to play without any problems here (FF with uBlock Origin). Do you have a more exact example? And do you also use a browser adblocker?

**Comment by ve6rah** [comment]
odd... videos do not load for me at all unless I specifically whitelist that domain, and then they work perfectly normally. I have no other adblocker running.
Specifically I was viewing https://calgary.ctvnews.ca/video?clipId=373266

**Comment by notracking** [comment]
I've added this to the whitelist with a special remark. Changes should be visible after the next autoupdate!

**Comment by notracking** [comment]
I'm still having doubts about this domain. As jawz101 is stating [here](https://github.com/jawz101/MobileAdTrackers/issues/4#issuecomment-435939129), this domain has nothing to do with actual video delivery it's purely there for tracking purposes.

The video stream will not load unless the scripts from gigya.com are loaded...., unless you are running a decent adblocker like uBlock Origin. Having a browser adblocker installed is still a very good idea, as dns filtering will never be 100% perfect. This is an excellent example of that.

My vote would be to blacklist this domain again, anyone has any thoughts on this?

**Comment by ve6rah** [comment]
If this is blacklisted, there will be no possible way to watch those news videos, adblocker or no.

The only solution for me if you blacklist it will be to whitelist it on my side. If that's what I have to do, then so be it.

Also, ublock is not an option on Android devices, not everyone is browsing from a full PC at all times.

I have tried both on my laptop (using ublock origin), and on my phone (android, therefore no ublock) and both fail to load videos unless this domain is whitelisted.

It all depends on what the goal is, if the goal of  this list is to block all tracking, then block it. But if the goal is to only block to the extent that legitimate functionality is not impaired, then I have to say that this blocks legitimate functionality.

**Comment by notracking** [comment]
Thanks for helping me getting on the right track again ;)

I'm leaving this whitelist entry in place, under the following condition:
 - Known trackers that break useful functions in legit websites will be whitelisted only in case the number of broken websites is higher than the number of sites using the tracker.

This will prevent single (small) websites with (for example) a broken google ads implementation from trumping very important blocks (like google ads), while still allowing me to whitelist almost all blocks that are breaking stuff (situations like these are relatively rare).

People using network wide dns filtering will always be only partly protected. Only in combination with proper content manipulation techniques (eg: browser adblockers / nBlock) one could achieve a almost perfect setup.
This means that if users are into the extreme levels of blocking everything and anything that might remotely be used for tracking / ads, must already have additional systems in place as dns filters alone are not suited for that usecase.

This leads me to the "do not break things" blocklist approach (as also noted in the official readme).
