### ISSUE TITLE
bitbucket.org

### ISSUE THREAD

**Issue by jonathanhoskin** [notracking/hosts-blocklists#114]
Hi. Love this repo, thanks for the good work.

I use bitbucket.org for software development; I'm not sure how/why it's in `domains.txt`, but it's causing me issues with pushing/pulling obviously.

Any thoughts? Happy to whitelist it?

TIA

**Comment by notracking** [comment]
Thank you for your kind words, I've added this one to the whitelist, it should obviously not be blocked. Changes will be visible after the next auto update.

**Comment by jonathanhoskin** [comment]
Many thanks @notracking !
