### ISSUE TITLE
whitelist domains and suggestions for other lists

### ISSUE THREAD

**Issue by HellboyPI** [notracking/hosts-blocklists#12]
Hello! 

Thank you for the excellent combined (wildcard) list. I've found some domains, that, I believe, do not belong in this list.

bing.net, virtualearth.net - Bing search and Bing maps
here.com - Nokia Here maps used by Facebook.
gearbest.com - popular electronic store.
jwpcdn.com, jwplatform.com, jwpltx.com - The [JWPlayer](https://www.jwplayer.com/) video platform.
h-cdn.com - [HolaCDN](https://holacdn.com/) - CDN for video delivery. Used for video streaming.
symcd.com - [Symantec CA](https://knowledge.symantec.com/library/VERISIGN/ALL_OTHER/Symantec/AD663/Symantec_OCSP_FQDN_List.txt). Used for verifying SSL certificates.
performgroup.com - Digital sports content and media group. Domain used for content delivery to other Perform brands. Example, goal.com
po.st - Link shortener service used mostly on social networks.

Some suggestions for your (wildcard) list:
[DShield.org Suspicious Domain List](http://www.dshield.org/feeds/suspiciousdomains_Low.txt)
[Mailscanner list](http://phishing.mailscanner.info/) of phishing sites
[Mitchell Krogs Badd-Boyz-Hosts](https://github.com/mitchellkrogza/Badd-Boyz-Hosts)
[WaLLy3K database](https://wally3k.github.io/) of lists from various sources.

**Comment by notracking** [comment]
Many, many thanks for the feedback!

It seems that quidsup is starting to give a lot of false calls these days. I'm reconsidering if this source belongs here. With exception of **po.st** (I will check again when I have a bit more time to analyze), I've fixed all your suggestions. Results will be visible upon the next auto-update.

(**Fixed** quidsup) _bing.net, virtualearth.net - Bing search and Bing maps_
(**Fixed** disconnect malware list) _here.com - Nokia Here maps used by Facebook._
(**Fixed** japanese adblock list) _gearbest.com - popular electronic store._
(**Fixed** japanese adblock list) _jwpcdn.com, jwplatform.com, jwpltx.com - The JWPlayer video platform._
(**Fixed** quidsup) _h-cdn.com - HolaCDN - CDN for video delivery. Used for video streaming._
(**Fixed** quidsup) _symcd.com - Symantec CA. Used for verifying SSL certificates._
(**Fixed** quidsup) _performgroup.com - Digital sports content and media group. Domain used for content delivery to other Perform brands. Example, goal.com_
(**Open** almost all lists) **po.st - Link shortener service used mostly on social networks.**

**Comment by notracking** [comment]
As for you list suggestions:

DShield.org Suspicious Domain List - Added the Medium variant, with some case specific filters, used approved whitelist
Mailscanner list of phishing sites - Not added, will generate tons of false calls when using this as domain / hostname filter.
Mitchell Krogs Badd-Boyz-Hosts - Added (though most hosts are already on the list)
WaLLy3K database of lists from various sources. - Added adaway, used whitelist suggestions

**Comment by CNMan** [comment]
```
2017/03/01 22:31:00 don't match TLDs: accounts.pkr.com.invalid
2017/03/01 22:31:01 don't match TLDs: ssl-nl.persgroep.edgekey.neto
2017/03/01 22:31:01 don't match TLDs: unk.vver.kiae.rr
```
```
2017/03/01 22:31:00 invalid line: 0.0.0.0 clk.77978.xn--q9jyb4c
2017/03/01 22:31:01 invalid line: 0.0.0.0 smartadserver
2017/03/01 22:31:02 invalid line: 0.0.0.0 xiaoqiang
```

**Comment by notracking** [comment]
@CNMan Thanks for the feedback, please create a new issue for this (this item is closed) and I will have a look at it.
