### ISSUE TITLE
use.fontawesome.com is blocked in hostnames.txt

### ISSUE THREAD

**Issue by ookangzheng** [notracking/hosts-blocklists#120]
use.fontawesome.com , cdn for fontawesome 5
![image](https://user-images.githubusercontent.com/6301735/48065148-d5d43180-e204-11e8-8859-29527a2bf5ae.png)

**Comment by ookangzheng** [comment]
also
maxcdn.bootstrapcdn.com (fontawesome v4)

**Comment by notracking** [comment]
You are on a roll sir! Also added to the whitelist.
