### ISSUE TITLE
letsencrypt ocsp blocked in hostnames.txt

### ISSUE THREAD

**Issue by larryhynes** [notracking/hosts-blocklists#122]
Hi

`ocsp.int-x3.letsencrypt.org` is currently blocked in `hostnames.txt`. This interferes with the mysterious workings of the [Online Certificate Status Protocol](https://en.wikipedia.org/wiki/Online_Certificate_Status_Protocol), and would usually be regarded as A Bad Thing. Is there a particular reason that it is included in the blocklist?

**Comment by notracking** [comment]
A big cleanup update is coming up tonight. The new version does not have this hostname blocked, but I will add the entire letsencrypt domain to the whitelist to be sure.

**Comment by larryhynes** [comment]
Hrm. I updated a few days ago, so it's probably been removed since. (I've already deleted it locally.) Sorry, I should have pulled before opening the issue. Thanks for looking into it.

**Comment by larryhynes** [comment]
To confirm: I just pulled latest now, and there are no letsencrypt urls in it. Many thanks.

**Comment by notracking** [comment]
np!
