### ISSUE TITLE
gstaticadssl.l.google.com is blocked in hostnames.txt

### ISSUE THREAD

**Issue by ookangzheng** [notracking/hosts-blocklists#128]
Domain: gstaticadssl.l.google.com is CNAME of fonts.gstatic.com
```bash
fonts.gstatic.com.	143	IN	CNAME	gstaticadssl.l.google.com.
gstaticadssl.l.google.com. 2	IN	A	0.0.0.0
```

**Comment by notracking** [comment]
added to the whitelist!

**Comment by cbuijs** [comment]
It seems to be a ad/track construction by google. I blacklist it and I don't see any usability impact.

See here:
https://www.reddit.com/r/uBlockOrigin/comments/8lyb5n/dealing_with_googleadapislgooglecom_and/

**Comment by notracking** [comment]
@cbuijs is correct. Will block this one again.
