### ISSUE TITLE
Aliexpress.com broken lately

### ISSUE THREAD

**Issue by Carl-Robert** [notracking/hosts-blocklists#13]
Hey!
https://www.aliexpress.com/ Doesn't work anymore (started somewhere this week), because the alicdn.com is blocked on the domains.txt. This is a cdn for the alibaba shopping site, more popular than ebay, so I don't really think it should be blocked. It is responsible of bringing the content (images, scripts, layouts etc) to users, with it blocked the website is mostly plain html.

**Comment by notracking** [comment]
This will be fixed with the next automatic update.

Thanks!
