### ISSUE TITLE
gh.ffshrine.org is blocked in hostnames.txt

### ISSUE THREAD

**Issue by ookangzheng** [notracking/hosts-blocklists#135]
<img width="882" alt="screen shot 2018-12-31 at 15 51 21" src="https://user-images.githubusercontent.com/6301735/50556439-0ec7e880-0d14-11e9-9a84-3336ccb239dd.png">
I watched some tutorial, and its a site to download some mp3

**Comment by notracking** [comment]
Thanks again! Fixed.
