### ISSUE TITLE
how-to whitelist

### ISSUE THREAD

**Issue by tve** [notracking/hosts-blocklists#137]
I'm using the block lists with plain dnsmasq, many thanks for all the work! Something I stumble into occasionally is how to (temporarily or more permanently) whitelist a site. Maybe you could add a couple of lines of how-to to the readme? For example, to get a prerelease version of some software I need to fill-out a form that posts to forms.hubspot.com which is blacklisted. The listing may well be correct, but right now I really need to submit that form...

**Comment by kokspflanze** [comment]
hi, i added this in my update script, its called one time each day.

````
#!/usr/bin/env bash

curl -Lo /opt/domains.txt https://raw.githubusercontent.com/notracking/hosts-blocklists/master/domains.txt
curl -Lo /opt/hostnames.txt https://raw.githubusercontent.com/notracking/hosts-blocklists/master/hostnames.txt
sed -i -e 's/0\.0\.0\.0/192\.168\.11\.40/g' /opt/hostnames.txt
sed -i -e 's/0\.0\.0\.0/192\.168\.11\.40/g' /opt/domains.txt
sed -i -e '/jdownloader\.org/d' /opt/domains.txt
sed -i -e '/kundenserver\.de/d' /opt/domains.txt
sed -i -e '/wemfbox\.ch/d' /opt/domains.txt
sed -i -e '/appboy\.com/d' /opt/domains.txt
systemctl restart dnsmasq
````

i think you mean `sed -i -e '/jdownloader\.org/d' /opt/domains.txt` what you mean. that remove jdownloader.org from the list, just as example

**Comment by notracking** [comment]
An alternative method is to overrule by adding dupe rules, pointing at your upsteam (unfiltered) dns and loading them before you load the blocklists. This works for bot hostname and domain name filters.

Create 2 files (whitelist.hostnames.txt and whitelist.domains.txt) and add your whitelist entries in the normal dnsmasq format, but instead of pointing them to 0.0.0.0 point them to a non-filtered dns like 1.1.1.1

whitelist.hostnames.txt:

```thisis.a.not.so.evilsite.com 1.1.1.1```

whitelist.domains.txt:
```address=/nicedomain.com/1.1.1.1```

And add them to you dnsmasq.conf file, before loading the blocklists:
```
# Local whitelists
addn-hosts=/files/pub/dnsfilters/whitelist.hostnames.txt
conf-file=/files/pub/dnsfilters/whitelist.domains.txt
# Blocklists
addn-hosts=/files/pub/dnsfilters/hostnames.txt
conf-file=/files/pub/dnsfilters/domains.txt```

For changes to apply to your whitelists and dnsmasq conf files, you should always reload the dnsmas config by ```sudo service dnsmasq restart```

**Comment by notracking** [comment]
Very nice addition @cbuijs it's the easiest on of the lot, though it will only work on domains, whitelisting will always include all subdomains. But that's a small price to pay. I will leave this ticket open until I have something written up in the readme.

**Comment by ve6rah** [comment]
@cbuijs Is there a specific place we need to put those server commands? I find that despite using the server entry in dnsmasq.conf as listed in your post above, the entry in domains.txt is still overriding it.

**Comment by cbuijs** [comment]
@ve6rah 

I use it in this order:

- `Address` statements (I only use it to spoof addresses when needed).
- Default `server` statements.
- Whitelist `server` statements (with the dash)
- Blacklist `server` statements (without the dash)

I don't think it matters "where" in the conf-file it sits, as long as it is in this order.

**Comment by cbuijs** [comment]
@notracking 

Wait, you mean you cannot blacklist a subdomain of a whitelisted one. Yes that is true and perhaps a limitation.

But from my experience I never needed to use that on the big bad internet. On company networks different story, but that is most of the time a clusterf*ck anyway :-). The need for this shows bad DNS craftmanship :-).

**Comment by ve6rah** [comment]
@cbuijs There must be something different with my version of dnsmasq? I can't get your method to work for me. It just seems to ignore the whitelist statement and use the entry in domains.txt instead every time. I've tried placing the server sections before, and after, the domains.txt entry, but in neither case does it whitelist the domains I've asked it to.

When I check the log files, it states "using standard nameservers for domain" and lists the whitelisted domain, but it doesn't seem to actually do it. I do also notice that regardless of the position in the conf file, the log file puts that line before the line about reading hostnames.txt (it never lists domains.txt, but I'm assuming that's read about the same time)

I think I'm going to have to stick with using sed on the incoming file, which is unfortunate, because this looked a little easier to manage.

**Comment by tve** [comment]
@cbuijs' method only seems to work for hosts for me. The `domains.txt` contains
```
address=/boldchat.com/0.0.0.0
address=/boldchat.com/::
```
and my whitelist contains
```
server=/boldchat.com/#
```
and that doesnt work using Dnsmasq version 2.79. Here's what `host` says for one domain, note how the MX record does resolve but the A record doesn't:
```
> host -v api.boldchat.com.
Trying "api.boldchat.com"
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 22379
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;api.boldchat.com.              IN      A

;; ANSWER SECTION:
api.boldchat.com.       10      IN      A       0.0.0.0

Received 50 bytes from 127.0.0.1#53 in 34 ms
Trying "api.boldchat.com"
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 61601
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;api.boldchat.com.              IN      AAAA

;; ANSWER SECTION:
api.boldchat.com.       10      IN      AAAA    ::

Received 62 bytes from 127.0.0.1#53 in 35 ms
Trying "api.boldchat.com"
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 63899
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;api.boldchat.com.              IN      MX

;; ANSWER SECTION:
api.boldchat.com.       219     IN      CNAME   rpc.boldchat.com.
rpc.boldchat.com.       241     IN      CNAME   boldchat.logmein.com.
boldchat.logmein.com.   4253    IN      CNAME   boldchat.logmein.com.logmein.com.akadns.net.

;; AUTHORITY SECTION:
akadns.net.             180     IN      SOA     internal.akadns.net. hostmaster.akamai.com. 15523269
23 90000 90000 90000 180

Received 216 bytes from 127.0.0.1#53 in 132 ms
```
If I change my whitelist to:
```
server=/api.boldchat.com/#
```
the white-listing works.

**Comment by ve6rah** [comment]
So you can only whitelist a sub-domain of the domain being blocked. That's unfortunate.

**Comment by feedzapper** [comment]
This solution for a Whitelist works very nice for me ..
it uses "fgrep" to delete Whitelisted domains from the domains.txt file and also if you need this from the hostnames.txt file :-)
https://www.linksysinfo.org/index.php?threads/tips-blocking-ads-and-tracker-using-hosts-adblock-with-combination-of-domains.74338

**Comment by two-dogs** [comment]
@cbuijs , your white-list method works here, thanks
System:    Host: skynet-HP-tw Kernel: 5.1.3-1-default x86_64 bits: 64 Desktop: N/A Distro: openSUSE Tumbleweed 20190521 : dnsmasq  ver: 2.80-3.2

**Comment by notracking** [comment]
After some more testing, there is only one proper solution and that is simply removing unwanted blocks directly from your local blocklists.

@tve is correct that @cbuijs' method will not work on domains and my initial proposal does simply not work reliably over various dnsmasq versions.

***This is also a note to self: will add some simple one liner console examples (sed/grep/whatever) to the readme file***

**Comment by sanzxip** [comment]
Can any one make a hostfile for pubg game nobanned id for me plz u guys are so telented

**Comment by notracking** [comment]
Updated the readme and added a script (daily cronjob) [here](https://raw.githubusercontent.com/notracking/hosts-blocklists-scripts/master/notracking_update).
