### ISSUE TITLE
Blocking Thumbnails in Google Play Store

### ISSUE THREAD

**Issue by xUltra-xx** [notracking/hosts-blocklists#138]
Hello, have set sercuredns without ads in my Android device and now in Play Store I can't see thumbnails.

**Comment by xUltra-xx** [comment]
Yes I use this in private DNS on Android 9 (3 Devices) It works good but only the Play Store Thumbnails not visible.
Have uploaded 2 pics https://imgur.com/a/v10eq13

**Comment by ve6rah** [comment]
Have you confirmed with securedns.eu that they are in fact using notracking's list unmodified? I'm not seeing anything on their website indicating the source of their blocking lists, and as it works properly on my device with my own copy of this list, I'm inclined to believe it's something on their end.

**Comment by xUltra-xx** [comment]
Thanks for answer. Region is Austria.

**Comment by ve6rah** [comment]
It's hard to be certain without logging some queries, but I find if I use the play store in a browser in my region, the images are loaded from lh3.googleusercontent.com, I do note that afs.googleusercontent.com is in hostnames.txt, so it's possible that other regions may use that instead?

Do you have the ability to whitelist and try it? (if you're only using it as private dns on android, you may need to work with the DNS provider)

**Comment by xUltra-xx** [comment]
Ok thanks. For now I using it only in Android but have informed the provider.
