### ISSUE TITLE
accept donations?

### ISSUE THREAD

**Issue by bahamas10** [notracking/hosts-blocklists#139]
this may not be the best channel to ask this question (feel free to close this issue if so) but do you accept donations for maintaining this?  I've been using this for the last half year and It's been perfect - seamlessly running in the background but making my home network usage much more enjoyable.  paypal? bitcoin? anything like that?

thanks for doing this :)

**Comment by notracking** [comment]
Thanks you for the kind words!

I'm not really in need for donations, allthough it would be nice to enable the possibility for people to buy me beers (yes, that will help! ;)).

Will leave this open for now, will investigate if setting something up is worth the hassle.

**Comment by notracking** [comment]
Thanks again, but no. Decided not to start accepting any donations whatsoever, just enjoy the lists! ;)

**Comment by notracking** [comment]
And changed, upgraded to a new dedicated server to generate the lists. There is now an option so support the notracking Blocklist!

**Comment by bahamas10** [comment]
@notracking awesome! I just donated, thanks again for the lists :)

**Comment by notracking** [comment]
That's very generous, thanks for the support!
