### ISSUE TITLE
"Add More List" ?

### ISSUE THREAD

**Issue by Doimatcuabautroi** [notracking/hosts-blocklists#140]
https://tspprs.com/
https://dbl.oisd.nl/

**Comment by Doimatcuabautroi** [comment]
https://dbl.oisd.nl/

**Comment by Atavic** [comment]
# https://tspprs.com/ Block-IT! Project

Combined List: *1,153,024 entries*
A combination of the following list: Abuse, Ads, Crypto, Fraud, Drugs, Main, Misc, Malware, Ransomware, Scam, Tracking. 
(Available separately)

# oisd.nl - domain block list

Entries: *1,630,666*

Questions/comments: https://redd.it/9xwwwy

Blocks; Ads, Mobile Ads, Tracking, Analytics, Phishing, Malware, Spyware, Ransomware, Exploid, Fraud, Abuse, Scam, Spam, Hijack, Misleading Marketing, Illegal Pharmacy, Fake News

Does **not** block things like: Facebook/Twitter/Snapchat etc
Does **not** block Torrent, Warez, Porn

Credits: YAMA-EDV FadeMind sidus-dev addy-dclxvi deathbybandaid EnergizedProtection zant95 CHEF-KOCH notracking joeylane WillPresley StevenBlack Joshndroid SanderGit soteria-nou blokadaorg lightswitch05 lixuy bastiandg XionKzn michaeltrimm r-a-y borisschapira alobbs ultranity csirtgadgets AdguardTeam LaxusiC Ultimate-Hosts-Blacklist Firestorrrm ElCap1tan aziraphale adblockultimate migafgarcia nerddownloads lewisje GoldenKappa jkohrman 10069 Sunybyjava Spam404 w13d marinhero Anonymousnl Mydong panpap pjsp92 gorhill anudeepND littlepig10 byaka jawz101 vk496 qiaofei32 MajkiIT AegisTeam ozark46 worldomkar sudaraka mozillahispano kurobeats azet12 kowith337 chexov wenketel Bearsgoroar DevAbanoub HexxiumCreations gioxx Hubird-au nord73 loyingEcu waitusz CitizenXVIL anarki999 sumsethan mhxion Akamaru cx9527 greatis killsting vokins michalterbert FrendoWu QuickBox kimanlo laksa19 nomadturk lassekongo83 yowu zoln tcptomato easonjim PoorPocketsMcNewHold timmyrs morpehus Galigator TakoYachty crystoneme ConnersHua SlowMemory Rokufukka-iou genediazjr kcschan h2y Scott-St openhoangnc piperun duangsuse eEIi0A5L turtle2472 uBlockOrigin Cederick Saeviome slang1998 cjx82630 zcbenz hoshsadiq koala0529 kaselis hant0508 wolfsrealm sharad cb-software IDKwhattoputhere dintendocoltd xinggsf DandelionSprout bogachenko quidsup xlimit91 ADsecu yescallop qutorial dfkt SkeletalDemise yanggis xqin toshiya44 GATmyIT olegwukr mayesidevel darugnaa grufwub rbrito SweetSophia abpvn Neilpang reelsense Recon 4ft35t fboes xwgod e32ubhds Perflyst yagas stamparm ogollemon k2jp makarono jobro13 jiri001meitner IAreKyleW00t Sinfonietta jmdugan KimmoOinonen NanoAdblocker miyurusankalpa quyentruong hulkhaugen jc1arke Nickwasused TheBinaryLoop MagicMarvMan astrolince BreakingTheNews cbuijs] support.it-mate.co.uk hosts-file.net v.firebog.net tspprs.com git.habd.as s3.amazonaws.com netcologne.dl.sourceforge.net hblock.molinero.xyz download.dnscrypt.info nkhq.de netix.dl.sourceforge.net dsi.ut-capitole.fr adaway.herokuapp.com birds-are-nice.me rlwpx.free.fr firewall.netpatch.co forum.dd-wrt.com gist.githubusercontent.com blacklists.cert.gov.ge mirror1.malwaredomains.com cdn.ad-blocker.org mirror.uta.edu.ec adguard.com sourceforge.net static.squarespace.com wapinet.ru easylist-msie.adblockplus.org meteophysique.free.fr downloads.marcofolio.net pasteall.org dns-bh.sagadc.org vietpn.com pastebin.com cfile23.uf.tistory.com topfloor.ca cycle-planet.com www3.telus.net download.buckreynolds.com blogmoda.com gitlab.com git.maze.io distortion.io people.duke.edu kawtriple.com ipv6.divservices.com kopatsch.com davidc.theunixplace.com time.hol.es pub.pcmajster.pl line.ircnet.nu smart.wapil.com pumpkin333.sakura.ne.jp dn-mwsl-hosts.qbox.me scrapbox.io phishing.army okki.io 162.248.138.248:83 idannywu.com 77l5b4.com1.z0.glb.clouddn.com getlives.com easylist-downloads.adblockplus.org hosts.nfz.moe cancer.cs.ucdavis.edu jansal.net abuseme.eu iballinst.com tools.yiclear.com bitbucket.org web2.airmail.net entropy.soldierx.com filtri-dns.ga svn.dd-wrt.com blog-imgs-49.fc2.com filters.adtidy.org 280blocker.net nagafix.co.uk tekrider.net stascorp.com dehakkelaar.nl roomchat.im chitta001.cocolog-nifty.com osint.bambenekconsulting.com jeffmilner.com 60t.org code.taobao.org rainman.me jonafeucht.de ja.pastebin.ca hosts.herndl.org pds25.egloos.com zitstif.no-ip.org abp.mozilla-hispano.org latimp.net fonk.wz.cz members.ping.de cyberside.net.ee accs-net.com imai.mydns.jp proxy.yeh.sh kprules.b0.upaiyun.com tch3.net ideone.com de.community.norton.com vergessenhoch3.net gameindustry.de slexy.org github.com adb.juvander.net madll.free.fr michael-prokop.at web.archive.org fanboy.co.nz 7af4rr.com1.z0.glb.clouddn.com h2ochip.com datadragon.com gdr.geekhood.net lw764.ultraseedbox.com n2o.io nnt.0am.jp adblocklist.org drashna.net digitalexprezz.in gurud.ee ajnasz.hu paste.ee lauritzt.dk adguardteam.github.io hosts.jixun.moe blogram.net satterly.neocities.org

**Comment by loveqianool** [comment]
https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts
https://hosts.nfz.moe/full/hosts

**Comment by Atavic** [comment]
^ Not bad ones at all. Chinese mantainers, the 1st one has categories based on packages, maybe a firewall logged the connections from packages, as *alibaba, qq* or *baidu*.

> https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts

See: https://github.com/jdlingyu/ad-wars (Not updated from May 2018)

> https://hosts.nfz.moe/full/hosts

See: https://github.com/neofelhz/neohosts

**Comment by notracking** [comment]
Thanks!

Took some time, but here it is..
tspprs.com - too many false calls (ads list checked)
dbl.oisd.nl - also includes notracking list, but only the domains list, which has no purpose in a hostname list for pihole. But anyway, there are some nice sources in there.

Added:
@Doimatcuabautroi
 - https://raw.githubusercontent.com/DandelionSprout/adfilt/master/NorwegianExperimentalList%20alternate%20versions/NordicFiltersDnsmasq.conf
 - https://raw.githubusercontent.com/RooneyMcNibNug/pihole-stuff/master/SNAFU.txt
 - https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt
 - https://raw.githubusercontent.com/Akamaru/Pi-Hole-Lists/master/gamefake.txt
 - https://raw.githubusercontent.com/Akamaru/Pi-Hole-Lists/master/mobile.txt

@loveqianool 
 - https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts
 - https://raw.githubusercontent.com/neoFelhz/neohosts/data/_data/basic/common.txt

@Atavic Thanks for the extra info :)
