### ISSUE TITLE
Offer "plain" lists of hosts/domains for other software?

### ISSUE THREAD

**Issue by deanishe** [notracking/hosts-blocklists#142]
The dnsmasq format isn't exactly difficult to parse, but having just a simple list of hosts & domains (i.e. one host/domain per line) would make the lists easier to use with other software, such as unbound.

Any chance of that?

**Comment by bigpresh** [comment]
I was thinking recently that it would be nice if it consisted as a list of domains/hosts in the repo, and an "update" script you could run from cron which generated the dnsmasq config for your from that, with options to control what IP it should resolve to and an ability to point at a whitelist file that would omit some entries for quick and easy local whitelisting.

That would work well with this :)  (Scripts to turn the data into other formats could easily be contributed then, too.)

**Comment by deanishe** [comment]
> an ability to point at a whitelist file

Yes. This would also be very useful. One man's evil tracker is another man's must-read social media.

**Comment by HellboyPI** [comment]
Maybe something like the github user Energized has published, lists in multiple formats/ flavors. 
See [here](https://github.com/EnergizedProtection/block).

**Comment by deanishe** [comment]
The variety of formats is great, but it doesn't have the domain/hostname distinction that makes @notracking's lists so useful.

Having distinct domain and hostname lists is *way* better if your blocker can use them.

**Comment by tve** [comment]
I just switched from dnsmasq to dnscrypt-proxy so I could use DNS-over-HTTPS. dnscrypt-proxy has nice black and whitelist support using pattern matching (https://github.com/jedisct1/dnscrypt-proxy/wiki/Filters). One difference is that it doesn't respond with 0.0.0.0 for blocked domains/hosts, I'll see whether that causes issues. I use the following script to convert the notracking lists to dnscrypt-proxy:
```
wget -O domains.new https://raw.githubusercontent.com/notracking/hosts-blocklists/master/domains.txt
wget -O hostnames.new https://raw.githubusercontent.com/notracking/hosts-blocklists/master/hostnames.txt

sed <domains.new >blacklist.txt \
  -e '/::$/d' \
  -e 's;^address=/;;' \
  -e 's;/0.*;;'

sed <hostnames.new >>blacklist.txt \
  -e '/^::/d' \
  -e 's/^0.0.0.0 /=/'

sudo dnscrypt-proxy -restart
```

**Comment by notracking** [comment]
This repos will only contain the 2 filter lists in a format accepted by dnsmasq. I don't see any added value in adding and maintaining multiple formats as these lists are already fairly easy to parse (as @tve demonstrated).

I want to keep it simple in here, both for me (maintenance) and the less experienced dnsmasq user looking for a blocklist solution.

**Comment by websocket98765** [comment]
Thank you @tve ! I almost didn't use these blocklists because I don't want to give up DNS encryption, but your solution looks like it would work. Using `dnscrypt-proxy` should be the preferred way in the README to set up these blocklists.

**Comment by websocket98765** [comment]
@tve Error in your hostname regex, that prepends a `=` to the output. Should be:
```
sed <hostnames.new >>blacklist.txt \
  -e '/^::/d' \
  -e 's/^0.0.0.0 //'
```

**Comment by tve** [comment]
@websocket98765 that '=' is there on purpose. Please read https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Filters#filter-patterns : `=example.com` -> `block example.com but not *.example.com`.

**Comment by websocket98765** [comment]
@tve Good to know. Thanks

**Comment by notracking** [comment]
And dnscrypt-proxy is now also supported.
