### ISSUE TITLE
[Request] Add additional Adblock Plus sources lists

### ISSUE THREAD

**Issue by smed79** [notracking/hosts-blocklists#143]
This is a request to add additional Adblock Plus sources lists

* https://easylist-downloads.adblockplus.org/Liste_AR.txt
* http://www.squidblacklist.org/downloads/sbl-adblock.acl
* https://raw.githubusercontent.com/easylist/EasyListHebrew/master/EasyListHebrew.txt
* https://cdn.rawgit.com/SlashArash/adblockfa/master/adblockfa.txt
* https://easylist-downloads.adblockplus.org/advblock.txt
* https://raw.githubusercontent.com/ABPindo/indonesianadblockrules/master/subscriptions/abpindo.txt

Thank you.

**Comment by beerisgood** [comment]
AdBlocker lists aren't recommend as Hosts list

**Comment by notracking** [comment]
@beerisgood, depends. I'd only use the full domain filters without other specifiers (as written in the readme). This actually provided plenty of good hosts for our blocklist.

I will look in to these later, been a bit busy these days..

**Comment by smed79** [comment]
@beerisgood example of from **Liste AR**

ABP filters
```
||clickyab.com^$third-party
||adv.bokra.net^
```
will become (Hosts list)
```
0.0.0.0 clickyab.com
0.0.0.0 adv.bokra.net
```
or (if subdomains are known)
```
0.0.0.0 a.clickyab.com
0.0.0.0 www.clickyab.com
0.0.0.0 static.clickyab.com
0.0.0.0 supplier.clickyab.com
0.0.0.0 adv.bokra.net
```

**Comment by notracking** [comment]
Only adv.bokra.net will be used for blocking as clickyab.com has a exception filter on it.

**Comment by notracking** [comment]
- https://easylist-downloads.adblockplus.org/Liste_AR.txt - added
 - http://www.squidblacklist.org/downloads/sbl-adblock.acl - only 3rd party filters
 - https://raw.githubusercontent.com/easylist/EasyListHebrew/master/EasyListHebrew.txt - added
 - https://cdn.rawgit.com/SlashArash/adblockfa/master/adblockfa.txt - no results
 - https://easylist-downloads.adblockplus.org/advblock.txt - no results
 - https://raw.githubusercontent.com/ABPindo/indonesianadblockrules/master/subscriptions/abpindo.txt - added

Thanks!
