### ISSUE TITLE
Current state of hostnames.txt breaks GeForce driver update locations

### ISSUE THREAD

**Issue by aaronjwood** [notracking/hosts-blocklists#146]
Breaks https://www.geforce.com/drivers
```
VM313:1 GET https://gfwsl.geforce.com/nvidia_web_services/controller.php/com.nvidia.services.Drivers.getMenuArrays/%7B%22pt%22:1,%22driverType%22:%22all%22%7D net::ERR_NAME_NOT_RESOLVED
```

Also breaks GeForce Experience and prevents it from being able to grab new drivers:
![Capture](https://user-images.githubusercontent.com/446283/56461173-309cb800-6363-11e9-9f44-8e1e23c7e185.PNG)

Removing all of the related entries (except for telemetry.*) in `hostnames.txt` fixes it.

**Comment by notracking** [comment]
I've whitelisted `gfwsl.geforce.com`, let's see how far that will take us.
