### ISSUE TITLE
Getting 14 "bad name..." errors when restarting dnsmasq 

### ISSUE THREAD

**Issue by mflannery** [notracking/hosts-blocklists#147]
I see the following in journalctl -flu dnsmasq when restarting dnsmasq:

...
Apr 30 09:42:07 localhost dnsmasq[18513]: bad name at /etc/hostnames.txt line 51425
Apr 30 09:42:07 localhost dnsmasq[18513]: bad name at /etc/hostnames.txt line 51426
Apr 30 09:42:07 localhost dnsmasq[18513]: bad name at /etc/hostnames.txt line 51427
Apr 30 09:42:07 localhost dnsmasq[18513]: bad name at /etc/hostnames.txt line 51428
Apr 30 09:42:07 localhost dnsmasq[18513]: bad name at /etc/hostnames.txt line 51455
Apr 30 09:42:07 localhost dnsmasq[18513]: bad name at /etc/hostnames.txt line 51456
Apr 30 09:42:07 localhost dnsmasq[18513]: bad name at /etc/hostnames.txt line 51471
Apr 30 09:42:07 localhost dnsmasq[18513]: bad name at /etc/hostnames.txt line 51472
Apr 30 09:42:07 localhost dnsmasq[18513]: bad name at /etc/hostnames.txt line 51473
Apr 30 09:42:07 localhost dnsmasq[18513]: bad name at /etc/hostnames.txt line 51474
Apr 30 09:42:07 localhost dnsmasq[18513]: bad name at /etc/hostnames.txt line 51479
Apr 30 09:42:07 localhost dnsmasq[18513]: bad name at /etc/hostnames.txt line 51480
Apr 30 09:42:07 localhost dnsmasq[18513]: bad name at /etc/hostnames.txt line 51485
Apr 30 09:42:07 localhost dnsmasq[18513]: bad name at /etc/hostnames.txt line 51486
...

I changed the hostname to localhost to aid readability. 

This is the most recent hostnames.txt file downloaded from github this morning. I assume dnsmasq is ignoring these lines but upon examining them I don't see anything different between these and the lines preceding or following. I just don't like to see errors in my logs.

Mike

**Comment by notracking** [comment]
Nothing here, could you give the actual lines that your dnsmasq is complaining about?

```
# journalctl -flu dnsmasq
-- Logs begin at Fri 2019-03-22 20:41:24 CET. --
May 05 05:33:45 fileserver systemd[1]: Stopping dnsmasq - A lightweight DHCP and caching DNS server...
May 05 05:33:45 fileserver systemd[1]: Stopped dnsmasq - A lightweight DHCP and caching DNS server.
May 05 05:33:45 fileserver systemd[1]: Starting dnsmasq - A lightweight DHCP and caching DNS server...
May 05 05:33:45 fileserver dnsmasq[27186]: dnsmasq: syntax check OK.
May 05 05:33:46 fileserver systemd[1]: Started dnsmasq - A lightweight DHCP and caching DNS server.
May 05 09:16:23 fileserver systemd[1]: Stopping dnsmasq - A lightweight DHCP and caching DNS server...
May 05 09:16:23 fileserver systemd[1]: Stopped dnsmasq - A lightweight DHCP and caching DNS server.
May 05 09:16:23 fileserver systemd[1]: Starting dnsmasq - A lightweight DHCP and caching DNS server...
May 05 09:16:23 fileserver dnsmasq[24383]: dnsmasq: syntax check OK.
May 05 09:16:24 fileserver systemd[1]: Started dnsmasq - A lightweight DHCP and caching DNS server.
```

**Comment by mflannery** [comment]
This is from the latest hostnames.txt file downloaded this morning:

 51425	:: r.twimg.com
 51426	0.0.0.0 r.voila.fr
 51427	:: r.voila.fr
 51428	0.0.0.0 r.xcycm.com
 51455	:: r10.cooleremail.com
 51456	0.0.0.0 r11.cooleremail.com
 51471	:: r2---sn-vgqs7n7k.googlevideo.com
 51472	0.0.0.0 r2.cooleremail.com
 51473	:: r2.cooleremail.com
 51474	0.0.0.0 r20---sn-vgqs7ne7.googlevideo.com
 51479	:: r20.sn-vgqs7ne7.googlevideo.com
 51480	0.0.0.0 r3.cooleremail.com
 51485	:: r3ny9p.ndc.northern-dishedends.co.uk
 51486	0.0.0.0 r4---sn-8pgbpohxqp5-ac5e.googlevideo.com
 51425	:: r.twimg.com
 51426	0.0.0.0 r.voila.fr
 51427	:: r.voila.fr
 51428	0.0.0.0 r.xcycm.com
 51455	:: r10.cooleremail.com
 51456	0.0.0.0 r11.cooleremail.com
 51471	:: r2---sn-vgqs7n7k.googlevideo.com
 51472	0.0.0.0 r2.cooleremail.com
 51473	:: r2.cooleremail.com
 51474	0.0.0.0 r20---sn-vgqs7ne7.googlevideo.com
 51479	:: r20.sn-vgqs7ne7.googlevideo.com
 51480	0.0.0.0 r3.cooleremail.com
 51485	:: r3ny9p.ndc.northern-dishedends.co.uk
 51486	0.0.0.0 r4---sn-8pgbpohxqp5-ac5e.googlevideo.com

I personally don't see anything wrong here but when I restart dnsmasq I get:

May 07 07:28:15 admin.cluster.net dnsmasq[13925]: bad name at /etc/hostnames.txt line 51425
May 07 07:28:15 admin.cluster.net dnsmasq[13925]: bad name at /etc/hostnames.txt line 51426
May 07 07:28:15 admin.cluster.net dnsmasq[13925]: bad name at /etc/hostnames.txt line 51427
May 07 07:28:15 admin.cluster.net dnsmasq[13925]: bad name at /etc/hostnames.txt line 51428
May 07 07:28:15 admin.cluster.net dnsmasq[13925]: bad name at /etc/hostnames.txt line 51455
May 07 07:28:15 admin.cluster.net dnsmasq[13925]: bad name at /etc/hostnames.txt line 51456
May 07 07:28:15 admin.cluster.net dnsmasq[13925]: bad name at /etc/hostnames.txt line 51471
May 07 07:28:15 admin.cluster.net dnsmasq[13925]: bad name at /etc/hostnames.txt line 51472
May 07 07:28:15 admin.cluster.net dnsmasq[13925]: bad name at /etc/hostnames.txt line 51473
May 07 07:28:15 admin.cluster.net dnsmasq[13925]: bad name at /etc/hostnames.txt line 51474
May 07 07:28:15 admin.cluster.net dnsmasq[13925]: bad name at /etc/hostnames.txt line 51479
May 07 07:28:15 admin.cluster.net dnsmasq[13925]: bad name at /etc/hostnames.txt line 51480
May 07 07:28:15 admin.cluster.net dnsmasq[13925]: bad name at /etc/hostnames.txt line 51485
May 07 07:28:15 admin.cluster.net dnsmasq[13925]: bad name at /etc/hostnames.txt line 51486
May 07 07:30:30 admin.cluster.net dnsmasq[13943]: bad name at /etc/hostnames.txt line 51425
May 07 07:30:30 admin.cluster.net dnsmasq[13943]: bad name at /etc/hostnames.txt line 51426
May 07 07:30:30 admin.cluster.net dnsmasq[13943]: bad name at /etc/hostnames.txt line 51427
May 07 07:30:30 admin.cluster.net dnsmasq[13943]: bad name at /etc/hostnames.txt line 51428
May 07 07:30:30 admin.cluster.net dnsmasq[13943]: bad name at /etc/hostnames.txt line 51455
May 07 07:30:30 admin.cluster.net dnsmasq[13943]: bad name at /etc/hostnames.txt line 51456
May 07 07:30:30 admin.cluster.net dnsmasq[13943]: bad name at /etc/hostnames.txt line 51471
May 07 07:30:30 admin.cluster.net dnsmasq[13943]: bad name at /etc/hostnames.txt line 51472
May 07 07:30:30 admin.cluster.net dnsmasq[13943]: bad name at /etc/hostnames.txt line 51473
May 07 07:30:30 admin.cluster.net dnsmasq[13943]: bad name at /etc/hostnames.txt line 51474
May 07 07:30:30 admin.cluster.net dnsmasq[13943]: bad name at /etc/hostnames.txt line 51479
May 07 07:30:30 admin.cluster.net dnsmasq[13943]: bad name at /etc/hostnames.txt line 51480
May 07 07:30:30 admin.cluster.net dnsmasq[13943]: bad name at /etc/hostnames.txt line 51485
May 07 07:30:30 admin.cluster.net dnsmasq[13943]: bad name at /etc/hostnames.txt line 51486

Cheers!
Mike

**Comment by two-dogs** [comment]
https://git.io/fjBz5 , me too
i dont see any logic to it

**Comment by MR-Diamond** [comment]
Same here:

dnsmasq[18243]: bad name at /etc/AdBlock/ads.hosts line 52898
dnsmasq[18243]: bad name at /etc/AdBlock/ads.hosts line 52913
dnsmasq[18243]: bad name at /etc/AdBlock/ads.hosts line 52914
dnsmasq[18243]: bad name at /etc/AdBlock/ads.hosts line 52915
dnsmasq[18243]: bad name at /etc/AdBlock/ads.hosts line 52916
dnsmasq[18243]: bad name at /etc/AdBlock/ads.hosts line 52921
dnsmasq[18243]: bad name at /etc/AdBlock/ads.hosts line 52922
dnsmasq[18243]: bad name at /etc/AdBlock/ads.hosts line 52927
dnsmasq[18243]: bad name at /etc/AdBlock/ads.hosts line 52928
dnsmasq[18243]: read /etc/AdBlock/ads.hosts - 77748 addresses

However, these entries reported as bad name, are blocked as expected.
EG: line 52898:

ping r11.cooleremail.com
PING r11.cooleremail.com (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.062 ms
64 bytes from localhost (127.0.0.1): icmp_seq=2 ttl=64 time=0.069 ms
64 bytes from localhost (127.0.0.1): icmp_seq=3 ttl=64 time=0.070 ms

**Comment by achilleas-k** [comment]
I have the same issue.  Here's a list of the domains that are causing the issue:
```
:: r.twimg.com
0.0.0.0 r.voila.fr
:: r.voila.fr
0.0.0.0 r.xcycm.com
:: r10.cooleremail.com
0.0.0.0 r11.cooleremail.com
:: r2---sn-vgqs7n7k.googlevideo.com
0.0.0.0 r2.cooleremail.com
:: r2.cooleremail.com
0.0.0.0 r20---sn-vgqs7ne7.googlevideo.com
:: r20.sn-vgqs7ne7.googlevideo.com
0.0.0.0 r3.cooleremail.com
:: r3ny9p.ndc.northern-dishedends.co.uk
0.0.0.0 r4---sn-8pgbpohxqp5-ac5e.googlevideo.com
```

The only thing they seem to have in common is they all start with `r.` or `r[number]`, but this doesn't happen for all hostnames which match that pattern.

**Comment by notracking** [comment]
I'm still not experiencing this behavior on my instances of dnsmasq, could you share the versions you are using? This smells like a dnsmasq issue.

```
# dnsmasq --version
Dnsmasq version 2.76
```

**Comment by MR-Diamond** [comment]
dnsmasq --version
Dnsmasq version 2.80  Copyright (c) 2000-2018 Simon Kelley
Compile time options: IPv6 GNU-getopt DBus i18n IDN2 DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC loop-detect inotify dumpfile

**Comment by achilleas-k** [comment]
Dnsmasq version 2.80  Copyright (c) 2000-2018 Simon Kelley
Compile time options: IPv6 GNU-getopt DBus i18n IDN2 DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC loop-detect inotify dumpfile

**Comment by notracking** [comment]
Did anyone check the dnsmasq bugtracker? I really cannot find anything wrong with the syntax of this list. This issue seems to be related to the latest stable release of dnsmasq..

**Comment by notracking** [comment]
I cannot reproduce this behavior with version 2.80 on Debian. Maybe it's something with the locale settings?

> /# locale
> LANG=en_US.UTF-8
> LANGUAGE=
> LC_CTYPE="en_US.UTF-8"
> LC_NUMERIC="en_US.UTF-8"
> LC_TIME="en_US.UTF-8"
> LC_COLLATE="en_US.UTF-8"
> LC_MONETARY="en_US.UTF-8"
> LC_MESSAGES="en_US.UTF-8"
> LC_PAPER="en_US.UTF-8"
> LC_NAME="en_US.UTF-8"
> LC_ADDRESS="en_US.UTF-8"
> LC_TELEPHONE="en_US.UTF-8"
> LC_MEASUREMENT="en_US.UTF-8"
> LC_IDENTIFICATION="en_US.UTF-8"
> LC_ALL=
> 
>

**Comment by two-dogs** [comment]
https://git.io/fjDUz , some info related to the package installed, my locale and journalctl dump specific to dnsmasq, btw, the errors seems to me to have zero ill effect on the intended purpose of the process, still, that is one hell of a puzzle.

**Comment by sanzxip** [comment]
Can any one make host file for pubg game no banned no tracks

**Comment by notracking** [comment]
There is nothing I can do about this from within the blocklists, the syntax is fine. I advise you to contact your package maintainers (or dnsmasq directly if build from source) about this behavior.
