### ISSUE TITLE
Duplicate entries in domains.txt

### ISSUE THREAD

**Issue by drduh** [notracking/hosts-blocklists#148]
There's no need to have two lines per domain for A and AAAA records pointing to localhost. Just a single address line per domain is enough for dnsmasq to return `NXDOMAIN` instead, e.g.:

`address=/example.com/`

**Comment by notracking** [comment]
This does not work on older versions of dnsmasq nor does it work for hostnames. The gains are not measurable in my experience, see also: https://github.com/notracking/hosts-blocklists/issues/124

Having 'dupe' entries in this case has no real life downsides and avoids backwards compatibility issues.

**Comment by drduh** [comment]
Not sure what you mean by, it doesn't work work for hostnames - it does work for single TLDs or any number of sub-domains. You should at least make a note that the entries don't need duplication for newer dnsmasq versions, and let others decide about the implications themselves.

**Comment by notracking** [comment]
What I mean is that the 'add-hosts' config option to block certain hostnames has a different purpose than using the 'conf-file' options in DNSmasq.

Blocking a hostname like sub.maindomain.com is not possible with the 'conf-file' options, without blocking all subdomains of that rule eg: *.sub.maindomain.com. For the 'addn-hosts' to be able to block both A and AAAA requests it requires 2 lines per hostname, one for A and one for AAAA requests.

I will see if I can add a note somewhere in the readme / header of the blocklists.

**Comment by notracking** [comment]
The new dnsmasq 2.80+ '#' formatting is now supported by a new list I'm generating, see: https://raw.githubusercontent.com/notracking/hosts-blocklists/master/dnsmasq/dnsmasq.blacklist.txt
