### ISSUE TITLE
white list api.segment.io

### ISSUE THREAD

**Issue by two-dogs** [notracking/hosts-blocklists#149]
api.segment.io is needed by 8X8 voip apps on both imac and ios (only two OS i can test on), segment.io is present in list domains.txt.
I have added api.segment.io to local white list

**Comment by notracking** [comment]
I strongly prefer not to whitelist this globally for the few apps that have a crappy implementation of a data hungry 3rd party tracker.

If for you whitlisting is the only option, I recommend to stick to a local whitelist for this entry.
