### ISSUE TITLE
Question: Do I need to restart dnsmasq after updating files?

### ISSUE THREAD

**Issue by Carl-Robert** [notracking/hosts-blocklists#15]
As the title stands, if overwriting the files without restarting the dnsmasq service, will they still be read or is it impossible to retain the cache and still get updates to the rules (which would obviously only work once the ttl of the dns in the cache expires)? 

Just unsure how this thing works, never used dnsmasq quite this way.

**Comment by notracking** [comment]
If you use a init system, you can use "sudo service dnsmasq reload" to reload the updated lists. The cache will be updated, however I'm not sure if dnsmasq will retain the non-affected existing entries in the cache.

**Comment by Carl-Robert** [comment]
Tested it with "dig www.google.com" to be thorough, it indeed does not maintain the cache after restarting the service! So if dnsmasq only reads this blocklist on startup, updating it turns to be rather annoying, as losing the big cache built up and starting from scratch.

I take it there isn't a way to have some sort of scheduled re-reading of these files without restarting the whole service? Seems now this way of blocking is slightly less effective from the simple user's perspective than pi-hole, as ending up losing cache all the time or not updating the lists.

**Comment by notracking** [comment]
Pi-hole is nothing more than a small layer of scripts and a UI around dnsmasq. If pi-hole is able to reload lists without flushing the cache it should also be possible with a 'bare' dnsmasq setup.
