### ISSUE TITLE
suspicious domain hklong.weixin.qq.com

### ISSUE THREAD

**Issue by beenotung** [notracking/hosts-blocklists#150]
I'm not sure if this domain is doing tracking, but it's accessed from my mobile phone when I'm not actively using wechat (I've not even installed qq)

**Comment by Atavic** [comment]
Weixin.qq.com has 8.90M visitors and 33.3M pageviews daily.

It appears to have various APIs in its subdomains, URLVoid and other scans consider it as safe.

**Comment by notracking** [comment]
Did you check what happens if you block this locally? I know from past experience that WeChat refuses to work properly when blocking overly aggressive.

Could you check this? I'm not using WeChat anymore.
