### ISSUE TITLE
Request for Change

### ISSUE THREAD

**Issue by tw-e** [notracking/hosts-blocklists#151]
Hello notracking,

@notracking 

1.Please unblock this: sp.aifei0755.net

2.Please block the following addresses:
api.zhy333.com
m.yyfymj.com
vj.quanjingpay.com
www.khlgauqt2000.com
www.tuigang1999.com

thanks!

**Comment by notracking** [comment]
Can you give some more info on why this should be done?

**Comment by tw-e** [comment]
> Can you give some more info on why this should be done?
https://sp.aifei0755.net/123/9.js
https://sp.aifei0755.net/123/24.js
https://sp.aifei0755.net/123/25.js
https://sp.aifei0755.net/123/26.js
https://sp.aifei0755.net/123/27.js
Because its ad server source is these codes. So I hope you can modify it, thank you.

**Comment by notracking** [comment]
sp.aifei0755.net is marked as serving malware and you just gave some examples that it's doing that as well, why should this be removed from the blocklist?

**Comment by tw-e** [comment]
Because its website article is still available for browsing.

**Comment by beerisgood** [comment]
I also don't understand about which website we're talking here about?
