### ISSUE TITLE
Please investigate/unblock the following...

### ISSUE THREAD

**Issue by dragon2611** [notracking/hosts-blocklists#152]
https://cdn-eu-ec.yottaa.net/ - Breaks https://www.screwfix.com (DIY/parts site) by preventing any images loading and causing the site not to render correctly.

https://johnlewis.scene7.com/ - Breaks the website johnlewis.com (Site of a UK retailer) by blocking various assets used in the site.

**Comment by dragon2611** [comment]
mobile.pipe.aria.microsoft.com - I'm not 100% sure about this one but I think it breaks the outlook app for android's connectivity to office365

**Comment by notracking** [comment]
Thanks for your feedback!

First 2 have been whitelisted, changes will be visible with the next autoupdate.

Regarding the MS one, not so sure about that one. I cannot test unfortunately. It's a hit from Steveblacks list which is also properly maintained. Maybe someone else can confirm or else I will leave it blacklisted.

**Comment by dragon2611** [comment]
sp1004e3b6.guided.lon5.atomz.com - breaks https://www.carphonewarehouse.com/mobiles/sim-free.html

**Comment by notracking** [comment]
whitelisted atomz.com.
