### ISSUE TITLE
ejquo23388.i.lithium.com, star.c10r.facebook.com

### ISSUE THREAD

**Issue by HellboyPI** [notracking/hosts-blocklists#157]
Fake positives in the hostnames list:
ejquo23388.i.lithium.com - blocks forums from displaying correctly. Example: community.netgear.com

star.c10r.facebook.com - blocks some Facebook functionality. This domain is already whitelisted at the Pihole forum under [Commonly Whitelisted Domains](https://discourse.pi-hole.net/t/commonly-whitelisted-domains/212).

**Comment by notracking** [comment]
Thanks for the feedback. Whitelist updated, changes will be visible with the next auto update!
