### ISSUE TITLE
pmenboeqhyrpvom. - weird hosts in domains.txt

### ISSUE THREAD

**Issue by larryhynes** [notracking/hosts-blocklists#16]
Hi

domains.txt contains the following entries:

```
pmenboeqhyrpvom.
pmenboeqhyrpvom.v
pmenboeqhyrpvom.w
```

which don't seem to correspond to FQDNs?

**Comment by notracking** [comment]
Should be fixed with the next autoupdate, thanks for reporting!

**Comment by larryhynes** [comment]
And so it is -thank you.
