### ISSUE TITLE
msftconnecttest.com blocked

### ISSUE THREAD

**Issue by Majr-** [notracking/hosts-blocklists#162]
This domain is used by Windows to check if the connection has internet access. With it blocked the connection will shown as "no internet access" for awhile (it must eventually try something else as it does go away eventually). This would be a minor annoyance except some applications either use the domain or Windows' internet status to tell if internet access is available, such as the Netflix app which refuses to do anything until Windows reports there's an internet connection.

**Comment by notracking** [comment]
That's a new one to me, already had msftncsi.com on the whitelist. Added this one, changes will be visible with the next auto update.

Thanks!
