### ISSUE TITLE
This seems breaks Google Home?

### ISSUE THREAD

**Issue by Originalimoc** [notracking/hosts-blocklists#165]
After disabled it Google Home BASIC FUNCTIONS can work again.
Need more people test on this.

**Comment by notracking** [comment]
I need more info on what hostname or domain names are causing this. I cannot test it because I do not own any of those Google spyware devices.

**Comment by Originalimoc** [comment]
I just manually removed all Google-owned domains now all is good.
google-analytics.com
googleapis.com
gvt*.com

**Comment by notracking** [comment]
The first 2 domains will not be whitelisted as they are the worlds largest ad injectors, tracking and malware serving domains.

what happens if you only whitelist the *.gvt2.com hostnames?

**Comment by notracking** [comment]
I've whitelisted the .gvt2.com from quidsup's list. These should be for the Google store to operate properly. As stated above the other 2 domains will not be whitelisted.
