### ISSUE TITLE
rqmob.com

### ISSUE THREAD

**Issue by 3xploiton3** [notracking/hosts-blocklists#166]
![](https://i.imgur.com/5s3SiZa.jpg)
![](https://i.imgur.com/3EQqkEO.jpg)

Add blocklist
[rqmob.com](*.rqmob.com)

From shareit android

**Comment by notracking** [comment]
The domain rqmob.com is not resolving and tracker.rqmod.com is already in hostnames.txt.

```
$ grep rqmob.com hostnames.txt 
0.0.0.0 adcs.rqmob.com
:: adcs.rqmob.com
0.0.0.0 tracker.rqmob.com
:: tracker.rqmob.com
```
