### ISSUE TITLE
Add use-application-dns.net for network wide disabling of DOH

### ISSUE THREAD

**Issue by notracking** [notracking/hosts-blocklists#169]
Mozilla did not roll out DOH by default, but it will soon. This will prevent local network clients from using your local dnsmasq (bypassing any configured blocklists).

I've updated the readme with [instructions](https://github.com/notracking/hosts-blocklists/blob/master/README.md#dns-over-https-doh) on how to disable this feature network wide.

This ticket is a placeholder to make a decision later if this domain should be part of the default blocklists.

**Comment by beerisgood** [comment]
Can you please add a example how this need to be configured?


address=/use-application-dns.net/

Doesn't sound correctly

**Comment by notracking** [comment]
That is actually how it's done. Firefox checks if that domain resolves with a valid a or aaaa record, if not it will disable DOH and defaults to standard dns.

**Comment by notracking** [comment]
Added by default to the list
