### ISSUE TITLE
Report Tracker for Windows App

### ISSUE THREAD

**Issue by DRSDavidSoft** [notracking/hosts-blocklists#170]
These domains belong to [FlashGet](http://flashget.com), which is a Windows download manager app:

### Trackers
```
stat.flashget.com
supertracker.flashget.com
cplog.flashget.com
```

Could you please consider adding them to your list?

**Comment by notracking** [comment]
Did you test that the app still works if you block these?

**Comment by DRSDavidSoft** [comment]
@notracking Yes, of course! It runs fine without these domains.

I also tried with blocking `*.flashget.com`. That also does not reduce the app's functionality in any way.

**Comment by notracking** [comment]
supertracker.flashget.com
cplog.flashget.com
have been added to the blacklist. 

stat.flashget.com is not resolving, could you double check on that one?

**Comment by DRSDavidSoft** [comment]
I'm sure about stat.flashget.com since I saw it in my DNS logs when the app starts.
It could be dead, but since it's hardcoded into the app, I'd appreciate if you also add this one. Thanks!

**Comment by notracking** [comment]
And stat is also added, thanks again! Changes will be visible with the next auto update.
