### ISSUE TITLE
unpkg.com is blocked 

### ISSUE THREAD

**Issue by Homas** [notracking/hosts-blocklists#171]
unpkg.com which hosts a lot of JS libraries is blocked.

Recently I see increased numbers of false positives like habrahabr.ru, mail.ru, salesforce.com and some other I'm lazy to check. Looks like some source may be compromised or some issues with data processing.

BR,
Vadim

**Comment by notracking** [comment]
unpkg.com
 habrahabr.ru
 salesforce.com (only main domain)

 Have been whitelisted, mail.ru is not in our lists. All false calls came from various list, it's not a single list going rogue or anything. Thanks for the feedback! Changes will be visible with the next auto update.

**Comment by notracking** [comment]
This caused me to remove the lightswitch05 list. It was not actually causing your specific false positives, but it continues to cause many, many others.

**Comment by Homas** [comment]
Thanks!

**Comment by lightswitch05** [comment]
> This caused me to remove the lightswitch05 list. It was not actually causing your specific false positives, but it continues to cause many, many others.

@notracking I appreciate feedback and respond promptly to issues in my project. Although, not sure what I could have done differently here since my list wasn't the problem.
