### ISSUE TITLE
(whitelist) olymtrade app

### ISSUE THREAD

**Issue by 3xploiton3** [notracking/hosts-blocklists#177]
Cannot open chat support in olymptrade android
I do not know which DNS is blocked

![](https://i.imgur.com/jQEL11U.jpg)

**Comment by notracking** [comment]
You will need to find the host causing this yourself, as I do not use that application.

Enabling logging in your `dnsmasq.conf` will get you a long way..!

```
# For debugging purposes, log each DNS query as it passes through
# dnsmasq.

log-queries
log-facility=/var/log/dnsmasq.log

```

**Comment by 3xploiton3** [comment]
@notracking i just use android, how to use that?

If u can convert domain to filter adblock, maybe i can look into adguard android
