### ISSUE TITLE
Pubg host file 

### ISSUE THREAD

**Issue by sanzxip** [notracking/hosts-blocklists#179]
Sir i m ur big fan sir please make a host file for pubg game without banned pubg hostfile sir please make a host file for pubg game no banned no tracking

**Comment by sanzxip** [comment]
Sir i m ur big fan can u make a hostfile for pubg game without banned no tracking  sir plz

**Comment by sanzxip** [comment]
My android phone

**Comment by sanzxip** [comment]
Sir how can i create a host file for pubg game in android phone

**Comment by notracking** [comment]
Sorry, this is not how this works.
