### ISSUE TITLE
Duplicated domains.

### ISSUE THREAD

**Issue by Maelstorm1973** [notracking/hosts-blocklists#182]
Domains psma01.com and psma02.com are duplicated in the domains.txt file.

**Comment by notracking** [comment]
Nice catch!

They are actually not dupes, but malformed domains.
Two of these domains are ending with a dot
```
psma01.com.
psma02.com.
```

Will update the filter for that..

**Comment by notracking** [comment]
Found plenty more of these, filters have been updated.

Changes will be visible with the next autoupdate..!
