### ISSUE TITLE
Add an additional list for Smart TVs

### ISSUE THREAD

**Issue by unimarijo** [notracking/hosts-blocklists#183]
It is probably a good idea to add a new list which contains a lot of domains related to Smart TVs: https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV.txt

**Comment by notracking** [comment]
Nice one, tested and added..!

**Comment by nymitr** [comment]
Broke Samsung smart TV: 
- youtube app;
- time synchronization.
