### ISSUE TITLE
remove from list

### ISSUE THREAD

**Issue by M1Aston** [notracking/hosts-blocklists#187]
banners.wunderground.com

Ads or something? But also images with info from selected weather stations (for websites. For example:
http://banners.wunderground.com/cgi-bin/banner/ban/wxBanner?bannertype=wxstnsticker_metric&weatherstationcount=ILONDON59

**Comment by notracking** [comment]
These are injected as 3rd party trackers in other websites. Their TOS even states that they sell your personal (incl. ip address) data. I cannot whitelist this one.
