### ISSUE TITLE
community.ubnt.com forum 

### ISSUE THREAD

**Issue by tunip** [notracking/hosts-blocklists#19]
Hi,

the community forum (e.g. https://community.ubnt.com/t5/UniFi-Wireless/bd-p/UniFi) from Ubiquiti looks strange and not fully loaded. Some images are missing if I enable the filter.

example image which could not be loaded:
https://ubnt.i.lithium.com/skins/images/7BF878847945715876D00678EDFE35E4/base/images/icon_thread_new_hot.png

![ubnt](https://user-images.githubusercontent.com/11404472/28705814-c36fd830-7371-11e7-969b-7560eaf889cd.jpg)
![ubnt2](https://user-images.githubusercontent.com/11404472/28705816-c4c16690-7371-11e7-9ad3-63a1728d2c7a.jpg)

Workaround was to whitelist "lithium.com" in domains.txt.

**Comment by notracking** [comment]
Thank you for the detailed report! Issue will be solved with the next auto-update.
