### ISSUE TITLE
Replace duplicate IPv4/IPv6 domains with a single null entry

### ISSUE THREAD

**Issue by craigbarnes** [notracking/hosts-blocklists#191]
I noticed that `domains.txt` has 2 entries for each domain (for IPv4/IPv6). According to the `dnsmasq(8)` man page these duplicate entries can be changed to a single entry for each domain by using `#` instead of an address:

> An address specified as `#` translates to the NULL address of `0.0.0.0` and its IPv6 equivalent of `::` so `--address=/example.com/#` will return NULL addresses for example.com and its subdomains. This is partly syntactic sugar for `--address=/example.com/0.0.0.0` and `--address=/example.com/::` but is also more efficient than including both as seperate[sic] configuration lines.

I was going to send a pull request changing the file itself, but I guess it would be too long to audit/review. However, this `sed` script replaces each double entry with a single `#` entry:

```sed
#!/usr/bin/sed -f
/^address=.*::$/d
s|^\(address=/.*/\)0.0.0.0$|\1#|
```

**Comment by notracking** [comment]
You are correct, though this has been discussed before. See ticket https://github.com/notracking/hosts-blocklists/issues/124

**Comment by craigbarnes** [comment]
Ah my bad, I should have searched first.
