### ISSUE TITLE
Broken domains.txt @ Line 22220 [2019/11/19]

### ISSUE THREAD

**Issue by thomaschampagne** [notracking/hosts-blocklists#193]
Hi

My dnsmasq failed to start today because of this characters in domains.txt line 22220 

```
address=/bittrêx.com/0.0.0.0
address=/bittrêx.com/::
address=/bittrẹx.com/0.0.0.0
address=/bittrẹx.com/::
```

It's quite blocking :/ 

Thanks for this repo and your help!!

Thomas

**Comment by notracking** [comment]
Good catch. Those should have been converted to punycode, will check asap!

**Comment by thomaschampagne** [comment]
Any fast rollback/revert possible on master as tmp workaround?

Thx!!!!

**Comment by notracking** [comment]
No, I already found the issue. running a manual update now. Will take ~30mins to complete.

**Comment by thomaschampagne** [comment]
You're the man !! Thanks for this fast fix!!

**Comment by thomaschampagne** [comment]
It works! Thx !
