### ISSUE TITLE
nrdp.nccp.netflix.com needs to be removed from your Hosts file, because the newest Netflix update on the PS4 and certain Smart TVs needs to connect to it in order to play movies/TV shows.

### ISSUE THREAD

**Issue by YattaMike** [notracking/hosts-blocklists#195]
Hello,

I registered on GitHub just to tell you this:

Netflix pushed out an update for my LG Smart TV today, and now it seems as though nrdp.nccp.netflix.com is required for Netflix to play a movie/TV show.  At first, I thought the issue was related to one of your recent Netflix-related commits, but after going through all of the "netflix.com" related lines in your hosts file and manually whitelisting them until it worked, I can confirm that "nrdp.nccp.netflix.com" is the culprit.

Whitelisting nrdp.nccp.netflix.com fixes the issue.  I'm not sure why this all of a sudden needs to be done, since I _think_ that's been in your hosts file for quite some time.  It could be because Netflix pushed out an app update on today (the app update was built on Monday, but I just received it)...  Maybe the latest app requires connecting to that server first for some reason - I'm not sure, but I figured I'd bring this to your attention.  I haven't yet seen if the app on my Fire TV requires nrdp.nccp.netflix.com to be whitelisted, but it definitely does for both of my LG Smart TVs.

Doing some research, I found that this update is being pushed out slowly for at least the last month:

https://www.reddit.com/r/pihole/comments/dhj3mz/netflix_on_ps4/

I currently don't need to whitelist "ichnaea.netflix.com" - but I wouldn't be surprised if I needed to in the future.

Considering this app update was just pushed out, a lot of other people may not have noticed yet that their Netflix isn't working, but I'm betting that they will - with the holiday coming up tomorrow.  Would you kindly remove nrdp.nccp.netflix.com (and possibly ichnaea.netflix.com since that affects the PS4 and possibly other Netflix apps) from your hosts file so as to not inconvenience everyone else watching Netflix via certain Smart TVs?

Thanks!

**Comment by notracking** [comment]
Thanks for the report! Item is whitelisted. Changes will be visible with the next autoupdate.

**Comment by YattaMike** [comment]
You are the best.  I really appreciate the hard work you do in maintaining these blocklists.  Incredible.  Happy Thanksgiving!
