### ISSUE TITLE
Blocking necessary domains

### ISSUE THREAD

**Issue by kornik30** [notracking/hosts-blocklists#197]
HI,
This domains file is Blocking necessary domains because I have noticed a problem with presentation my weather on https://www.wetteronline.de. 
Before usage domain.txt file it was OK.
I cannot recognize what records are problematic

**Comment by notracking** [comment]
I cannot whitelist those extremely widely used tracking domains (google, amazon) , this site works fine if you also use a browser adblocker on top. I strongly advice using "uBlock Origin".

For Firefox: https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/
For Chrome: https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm

**Comment by kornik30** [comment]
I cannot agree. It was checked on Chrome and Firefox, the domainsfile i set up on router.
I've attached two screen without this domains.txt and with it

Domains OFF
![OFFDOMAIN](https://user-images.githubusercontent.com/58479418/70217575-b712d800-1741-11ea-96f3-8cf6697a2f85.jpg)

Domains ON
![DOMAIN](https://user-images.githubusercontent.com/58479418/70217590-bc702280-1741-11ea-9515-13bd2603a291.jpg)
