### ISSUE TITLE
"Dead" hosts removal

### ISSUE THREAD

**Issue by Homas** [notracking/hosts-blocklists#198]
1. I've just found that you removed "dead" hosts. It is good but I think that you need to change the way you detect the "dead" hosts. 
NXDOMAIN in the response doesn't mean that the request/user was not tracked. 
Anyway the request was delivered to the 3rd party DNS server which hosts a DNS zone. An FQDN can be up to 255 chars and about 230 chars (depending on a length of a domain name) can be used to exfiltrate data/pass user id. 
To be more "precise" it will be better to validate if a domain is currently registered or not.

2. I'm using your lists to generate RPZ zone (https://ioc2rpz.net). I'm considering to include "dead" hosts to the existing RPZ or create a new one. Are you going to continuously update the "dead" list? 

Thanks for your hard work!

**Comment by notracking** [comment]
Thanks for the feedback!

The deadhosts file will always be automatically updated, so no worries about that.

Regarding the dead hosts marking criteria, I will need to do some more reading (especially on how exactly dnsmasq will deal with this). Will get back to you on that!

**Comment by Homas** [comment]
Thanks.
You also may consider moving "deadhosts.txt" to the "hosts-blocklists" repository. Right now it is located in "hosts-blocklists-scripts".

**Comment by notracking** [comment]
What if: A, AAAA, CNAME and NS records are empty. In that case the domain might still be registeren, but it would be non-functional having no risk of leaking info.

I put any supporting files in the scripts report, because I want to keep this repos as simple as possible to avoid confusion. Any supporting files will be committed to the scripts repos.

**Comment by Homas** [comment]
Checking the non existing NS records should eliminate possibility to track via DNS but if there is no name servers other records should not exists (probably except glue records)

**Comment by notracking** [comment]
Rebuilding the database, adding ns records...

The deadhosts file is going to be split up into domains and hostnames variants.

**Comment by notracking** [comment]
Thank you sir, scripts have been update. deadhosts file will expand over time.

dead domains: no registar info (unregistered via whois)
dead hostnames: NXDOMAIN on A, AAAA, CNAME, NS

**Comment by notracking** [comment]
The new dnsmasq 2.80+ '#' formatting is now supported by a new list I'm generating, see: https://raw.githubusercontent.com/notracking/hosts-blocklists/master/dnsmasq/dnsmasq.blacklist.txt
