### ISSUE TITLE
Request dnscrpyt-proxy support

### ISSUE THREAD

**Issue by sivajipro** [notracking/hosts-blocklists#199]
Request list designed for use with dnscrypt-proxy.

Thanks

**Comment by notracking** [comment]
Testing this at the moment, because of all the news about cnames. I dont expect support for cname blocking on short notice in dnsmasq, thus dnscrypt-proxy is the better solution now.

**Comment by notracking** [comment]
5d4a56b added new combined list for dnscrypt-proxy.
update readme / wiki is still todo

**Comment by notracking** [comment]
fixed
