### ISSUE TITLE
File retrieval URL incorrect?

### ISSUE THREAD

**Issue by rotational467** [notracking/hosts-blocklists#2]
I'm not sure if this is a pi-hole specific issue, however I needed to change the URLs in pi-hole's default list file from:

`https://raw.github.com/notracking/hosts-blocklists/master/...`

to 

`https://raw.githubusercontent.com/notracking/hosts-blocklists/master/...`

to get pi-hole to actually pull the lists.  The URL as is just causes pi-hole to report no changes and not download anything.

**Comment by notracking** [comment]
Thanks for the feedback, readme has been updated!
