### ISSUE TITLE
jdownloader.org blocked

### ISSUE THREAD

**Issue by kokspflanze** [notracking/hosts-blocklists#20]
hi,
big thanks to the list=]
my question is why jdownloader.org is blocked, maybe it can be removed,
i have a vm wich use the jdownloader api `api.jdownloader.org` and found that problem with that list.

thanks=]

**Comment by notracking** [comment]
You are correct, this is a false call caused by the fake domains list on hosts-list.net

Thank you for using this list and submitting a bugreport!
