### ISSUE TITLE
blocking too many domains

### ISSUE THREAD

**Issue by kornik30** [notracking/hosts-blocklists#200]
**wp.pl** is blocking 

and  problem with  **https://www.wetteronline.de**.
Before usage domain.txt  file on my router it was OK.
This below example was checked on Chrome and Firefox, the domains file i set up on router.
I've attached two screens without this domains.txt and with it

Domains OFF
![1](https://user-images.githubusercontent.com/58479418/70694691-8510f100-1cc0-11ea-9b02-12c3135ed17f.jpg)

Domains ON
![2](https://user-images.githubusercontent.com/58479418/70694713-90fcb300-1cc0-11ea-962d-efcae28dbe73.jpg)

**Comment by notracking** [comment]
I've whitelisted wp.pl and v.wpimg.pl, changes will be visible with the next autoupdate.

Regarding the weathers site, I can only advice you to install a browser based adblocker (uBlock Origin) on top of your local dns filters and the site will function again. I cannot unblock those intruding trackers as they are way to widely used on other websites (where blocking them does not break the site).

Thanks for the feedback!

**Comment by smokingwheels** [comment]
They Triangulate you ip with 2 dns servers. Be ware.

**Comment by kornik30** [comment]
Thank you
