### ISSUE TITLE
A much better way to format lists

### ISSUE THREAD

**Issue by Yunogamer** [notracking/hosts-blocklists#203]
Why dont we use "/" instead of "/0.0.0.0" and "/::"? Example "address=/doubleclick.net/" will return NXDOMAIN for *.doubleclick.net for both ipv4 and ipv6 in one line, reducing size by half or more and significantly reducing load on those running dnsmasq blocklists on weaker CPUs.

NXDOMAIN also is more compatible than returning 0.0.0.0 or :: as some clients keep trying when they get a null IP, or some picky sites detect a null IP and load wrong, where as NXDOMAIN it just gives up quickly and keeps going.

Change 
address=/doubleclick.net/0.0.0.0
address=/doubleclick.net/::

into

address=/doubleclick.net/

and so on.

**Comment by notracking** [comment]
Thanks for the suggestion, but this has been discussed before, see: #124 #148.

**Comment by notracking** [comment]
The new dnsmasq 2.80+ '#' formatting is now supported by a new list I'm generating, see: https://raw.githubusercontent.com/notracking/hosts-blocklists/master/dnsmasq/dnsmasq.blacklist.txt
