### ISSUE TITLE
CERT-PPa

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#206]

**Comment by scafroglia93** [comment]
These are the other list from CERT-PA

https://infosec.cert-pa.it/analyze/listip.txt
https://infosec.cert-pa.it/analyze/listurls.txt

**Comment by notracking** [comment]
Already checked those, but they are not suitable.
First one only holds ip addresses and the second one is the 'detailed' list of their main domain list, all of them are already covered.
