### ISSUE TITLE
Additional Filter

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#208]
1-https://data.netlab.360.com/dga/
(What do you think of including the whole range in order to increase protection ?)

2- https://threatfeeds.io/
(A list of up-to-date feeds, take what you think will suit the cause)

3- https://isc.sans.edu/suspicious_domains.html
https://isc.sans.edu/feeds/suspiciousdomains_Low.txt
https://isc.sans.edu/feeds/suspiciousdomains_Medium.txt
https://isc.sans.edu/feeds/suspiciousdomains_High.txt
(These are from SANS, look if there are something that would be interesting for you

4- Enjoy Donation from -> scafroglia57@gmail.com

**Comment by notracking** [comment]
Thanks you for the support!

I've updated the DGA feeds, added several usefull ones.
Rest is work in progress

**Comment by notracking** [comment]
And added a couple more from the threatfeed, thanks again! Changes will be visible with the next auto update.
