### ISSUE TITLE
Two to block

### ISSUE THREAD

**Issue by edentw** [notracking/hosts-blocklists#209]
Hi,
Could you please block these two?

yep.video.yahoo.com
stg.truvidplayer.com

thank you!

**Comment by notracking** [comment]
can you give an example of a site where these are included?

**Comment by edentw** [comment]
Hi,
From these two sites:

https://tw.news.yahoo.com/video/%E9%87%91%E6%AD%A3%E6%81%A9%E8%88%87%E6%9D%8E%E9%9B%AA%E4%B8%BB%E9%A8%8E%E9%A6%AC%E5%86%8D%E7%99%BB%E9%95%B7%E7%99%BD%E5%B1%B1-%E5%BC%B7%E8%AA%BF-%E9%A0%98%E8%A2%96%E8%A1%80%E7%B5%B1-%E8%99%9F%E5%8F%AC%E5%9C%8B%E6%B0%91%E6%94%BB%E5%85%8B%E9%9B%A3%E9%97%9C-075114041.html
https://m.ettoday.net/news/20200105/1618186.htm

Suspected advertising video.

**Comment by edentw** [comment]
Hi,
This URL is not needed, please skip the cancellation directly.
stg.truvidplayer.com
thank you!

**Comment by notracking** [comment]
That yahoo domain is used for actual content delivery. I'm not getting any video ads btw, could also be region locked.
