### ISSUE TITLE
pastebin.com is blacklisted

### ISSUE THREAD

**Issue by kokspflanze** [notracking/hosts-blocklists#21]
hi,

is there a reason to block https://pastebin.com ?

thanks =], i hope i dont spam with that

**Comment by notracking** [comment]
Hi kokspflanze,

Thanks for the feedback, but pastebin.com is not in our lists.
You might have another issue locally.

**Comment by kokspflanze** [comment]
funny it was in the list, but with last update it was removed.
looks someone already removed it=]

**Comment by notracking** [comment]
Oh, thanks. Didn't notice that! I will whitelist it so this cannot happen again in the future.
