### ISSUE TITLE
More Additional Host

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#210]
I spent an hour to find some additional hosts to be included in the list.
Take your time of course :)

1- https://github.com/mlsecproject/combine/issues/25

2- https://github.com/mlsecproject/combine/blob/master/inbound_urls.txt

3- https://github.com/mlsecproject/combine/blob/master/outbound_urls.txt

4- https://github.com/stamparm/maltrail/tree/master/trails/static
(there are txt inside dir)

5- http://www.covert.io/threat-intelligence/
(there are a lot of hostfile under ioc feeds

Thanks

**Comment by scafroglia93** [comment]
This is from italian infosec community
https://infosharing.cybersaiyan.it/feeds/CS-PIHOLE

**Comment by notracking** [comment]
Thanks!

1, 2, 3 mostely dead or ip based lists.
4, 5 todo

https://infosharing.cybersaiyan.it/feeds/CS-PIHOLE has been added, nice find!
