### ISSUE TITLE
(whitelist) https://prf.hn/

### ISSUE THREAD

**Issue by 3xploiton3** [notracking/hosts-blocklists#211]
https://prf.hn/click/camref:1011l7Ae7/adref:30970/pubref:5476e62bf84d4ea0a8aa256fcf078602/destination:https%3A%2F%2Fshopee.co.id%2Fsearch%3Fcategory%3D134%26facet%3D15956%26keyword%3Dultrabook%26page%3D0%26sortBy%3Drelevancy%26subcategory%3D1367

Source link
https://youtu.be/8sCa2HrWO4A

**Comment by 3xploiton3** [comment]
Ping @pengelana

**Comment by notracking** [comment]
Youtube does not work because of the block on prf.hn?
prf.hn is a tracker for https://partnerize.com/

**Comment by 3xploiton3** [comment]
https://www.youtube.com/redirect?redir_token=pt8_PcVKYAAdW0bdFeHMK83PCDV8MTU3ODcyNjU2OUAxNTc4NjQwMTY5&q=http%3A%2F%2Fbit.ly%2F36tsB8o&v=8sCa2HrWO4A&event=video_description
or
http://bit.ly/36tsB8o

![image](https://user-images.githubusercontent.com/19517680/72133228-80208980-33b3-11ea-861a-45b7e6490eb2.png)

**Comment by notracking** [comment]
Now I get it! ;)

Kinda sux to whitelist these linkshorteners, especially this one..
They are the #1 reason for linkrot, nevertheless I've whitelisted it, changes will be visible with the next auto update..!
