### ISSUE TITLE
Adding List

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#215]
- NextDNS CNAME Cloaking Blocklist
https://github.com/nextdns/cname-cloaking-blocklist

- MobileAdTrackers
https://github.com/jawz101/MobileAdTrackers

- Motomo's Referrer Spam Blacklist
https://matomo.org/blog/2015/05/stopping-referrer-spam

- fakenews
https://github.com/marktron/fakenews

**Comment by scafroglia93** [comment]
Spam404
https://github.com/Spam404/lists

**Comment by scafroglia93** [comment]
OpenPhish
https://openphish.com/feed.txt

**Comment by notracking** [comment]
NextDNS cname cloacking: (i'm checking out dnscrypt-proxy for cname blocking atm), added.
MobileAdTrackers already know, not very accurate (and non-maintained).
Spam404: updated existing link (repos moved) and added the domain variant.

Referrer lists are not suited for dns blocking I've found in the past and fakenews is out of scope.

**Comment by notracking** [comment]
Url lists like openphish cause too many false calls unfortunately..
