### ISSUE TITLE
Whitelist Viglink.com

### ISSUE THREAD

**Issue by 3xploiton3** [notracking/hosts-blocklists#216]
https://redirect.viglink.com/?key=e164e26dfb5274d06a0fe10b82774dc2&u=https%3A%2F%2Fgithub.com%2Ftopjohnwu%2FMagisk%2Freleases%2Fdownload%2Fmanager-v7.5.1%2FMagiskManager-v7.5.1.apk&type=ap&loc=https%3A%2F%2Fforum.xda-developers.com%2Fapps%2Fmagisk%2Fofficial-magisk-v7-universal-systemless-t3473445%2Famp%2F&ref=https%3A%2F%2Fwww.google.co.id%2F

Source:
https://forum.xda-developers.com/apps/magisk/official-magisk-v7-universal-systemless-t3473445

**Comment by 3xploiton3** [comment]
Google amp
https://www.google.co.id/amp/s/forum.xda-developers.com/apps/magisk/official-magisk-v7-universal-systemless-t3473445/amp/

**Comment by notracking** [comment]
whitelisted, thanks!

**Comment by 3xploiton3** [comment]
https://redirect.viglink.com/?key=eb2a339ada55034330f10e63d50e9cf6&u=https%3A%2F%2Fforum.xda-developers.com%2Fshowthread.php%3Ft%3D2422061&type=ap&loc=https%3A%2F%2Fforums.androidcentral.com%2Fgeneral-news-discussion%2F350531-any-android-apps-can-record-internal-audio.html%3Famp&ref=https%3A%2F%2Fwww.google.co.id%2F
