### ISSUE TITLE
Refactor List

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#217]
Hi, you have to delete this add
https://raw.githubusercontent.com/scafroglia93/hosts-blocklists/master/feeds.txt

**Comment by scafroglia93** [comment]
Keep me updated ;)

**Comment by notracking** [comment]
Thanks for the heads up, but all the new lists seem to be empty?

**Comment by scafroglia93** [comment]
Yes but don't worry i will fill it with domain from italian cert and other society

**Comment by notracking** [comment]
Just give me a trigger when you added content.
I will keep the old list in for now, the scripts will load the last known valid version from backup.

**Comment by scafroglia93** [comment]
https://github.com/scafroglia93/hosts-blocklists/blob/master/cert-pa.txt
https://github.com/scafroglia93/hosts-blocklists/blob/master/yoroi.txt

This two are ok, ready for merge

**Comment by notracking** [comment]
Looking very good sir! links have been updated, thanks!
