### ISSUE TITLE
List

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#219]
- New List TGSoft (Italian Counterspam)
https://github.com/scafroglia93/hosts-blocklists/blob/master/tgsoft.txt

- Iran IOC by Palo Alto
https://github.com/scafroglia93/hosts-blocklists/blob/master/pan-unit42/iran-linked-operators.txt

- Mirai IOC by Palo Alto
https://github.com/scafroglia93/hosts-blocklists/blob/master/pan-unit42/mirai.txt

- https://openphish.com/
Tested and now there are CERT of different govs for better detection with lower impact in terms of false detection

More list is coming !

**Comment by scafroglia93** [comment]
Maybe ?
https://phishing.army/download/phishing_army_blocklist_extended.txt

I'm working hard with other list made by me

**Comment by scafroglia93** [comment]
Zscaler
https://github.com/scafroglia93/hosts-blocklists/blob/master/zscaler.txt

**Comment by notracking** [comment]
Added all your lists up to here.
Phishing army is already tracked

I'm familiar with the openphish database, their domain list will cause too many false positives, but I'm looking into extracking all full domain filters from the sourcefeed, thos should be safe to add (requires some additional parsing though): https://openphish.com/feed.txt

**Comment by notracking** [comment]
openphish feed also added (full domain filters only).

You can open a new ticket if you have more lists to add :)

**Comment by scafroglia93** [comment]
Have you miss iran ioc from pan-unit42 ?

**Comment by notracking** [comment]
i forgot to add that one to the readme, fixed!
