### ISSUE TITLE
domains for the whitelist?

### ISSUE THREAD

**Issue by HellboyPI** [notracking/hosts-blocklists#22]
Hello!
I'm not sure why these domains are blocked. Maybe there was some problem before, bum not now.
tenforums.com - Forum
eightforums.com - Forum
jwplatform.com	 - [The JWPlayer](https://www.jwplayer.com/) video platform
ooyala.com - [The Ooyala Player](http://www.ooyala.com/resources/video-player). Example, used on accuweather.com to play videos.

The next one is problematic.
googletagmanager.com

Example, go to https://www.asus.com/Laptops/N550JX/HelpDesk_Download/.
Choose operating system. The drivers list won't show up. Removing the googletagmanager from the blacklist solves the problem.

Suggestions for your list:
1. [Airelle](http://rlwpx.free.fr/WPFF/hosts.htm) Trackers -[ mirror](https://v.firebog.net/hosts/Airelle-trc.txt), [official](http://rlwpx.free.fr/WPFF/htrc.7z)
2. [Shalla](http://www.shallalist.de/) Spyware/ Malicious - [mirror](http://v.firebog.net/hosts/Shalla-mal.txt), [official](http://www.shallalist.de/Downloads/shallalist.tar.gz)
3. [AdguardDNS](https://github.com/AdguardTeam/AdguardDNS) list - [mirror](http://v.firebog.net/hosts/AdguardDNS.txt), [official](https://filters.adtidy.org/extension/chromium/filters/15.txt)
4. [Fabrice Prigent's](https://dsi.ut-capitole.fr/blacklists/index_en.php) ads, malware and phishing lists - [mirror-ads](https://v.firebog.net/hosts/Prigent-Ads.txt), [mirror-malware](https://v.firebog.net/hosts/Prigent-Malware.txt), [mirror-phishing](https://v.firebog.net/hosts/Prigent-Phishing.txt), [official-ads](http://dsi.ut-capitole.fr/blacklists/download/publicite.tar.gz), [official-malware](http://dsi.ut-capitole.fr/blacklists/download/malware.tar.gz), [official-phishing](http://dsi.ut-capitole.fr/blacklists/download/phishing.tar.gz)
5. [BarbBlocks](http://bblck.me/) list - [official](https://ssl.bblck.me/blacklists/hosts-file.txt)
6. [Joe Wein](http://www.joewein.de/sw/bl-text.htm) spam list - [official](http://www.joewein.net/dl/bl/dom-bl-base.txt)
7. [bkrcrc turk](https://github.com/bkrcrc/turk-adlist) adlist - [official](https://raw.githubusercontent.com/bkrcrc/turk-adlist/master/hosts)

**Comment by notracking** [comment]
Hi!

Thanks for the feedback!

I've started with checking and whitelisting your suggestions, with exception of googletagmanager. I will leave this ticket open for now as I will verify the new lists when I have a bit more time.

To be continued...

**Comment by HellboyPI** [comment]
For some reason emptyloop.com is on the [Google Safe Browsing blacklist](https://transparencyreport.google.com/safe-browsing/search?url=emptyloop.com%2Funlocker%2F).  So I removed it from my 1st post.
Thank you for your effort! Your domains and hostnames lists are very helpful!

**Comment by notracking** [comment]
1. ~~[Airelle](http://rlwpx.free.fr/WPFF/hosts.htm) Trackers -[ mirror](https://v.firebog.net/hosts/Airelle-trc.txt), [official](http://rlwpx.free.fr/WPFF/htrc.7z)~~ Focussed on content blocking, ads list has a lot of non-invsive domains blocked. will not add
2. [Shalla](http://www.shallalist.de/) Spyware/ Malicious - [mirror](http://v.firebog.net/hosts/Shalla-mal.txt), [official](http://www.shallalist.de/Downloads/shallalist.tar.gz) **adv and tracking lists look suitable, needs sample test**
3. [AdguardDNS](https://github.com/AdguardTeam/AdguardDNS) list - [mirror](http://v.firebog.net/hosts/AdguardDNS.txt), [official](https://filters.adtidy.org/extension/chromium/filters/15.txt) **looks ok, needs sample test**
4. [Fabrice Prigent's](https://dsi.ut-capitole.fr/blacklists/index_en.php) ads, malware and phishing lists - [mirror-ads](https://v.firebog.net/hosts/Prigent-Ads.txt), [mirror-malware](https://v.firebog.net/hosts/Prigent-Malware.txt), [mirror-phishing](https://v.firebog.net/hosts/Prigent-Phishing.txt), [official-ads](http://dsi.ut-capitole.fr/blacklists/download/publicite.tar.gz), [official-malware](http://dsi.ut-capitole.fr/blacklists/download/malware.tar.gz), [official-phishing](http://dsi.ut-capitole.fr/blacklists/download/phishing.tar.gz)
5. [BarbBlocks](http://bblck.me/) list - [official](https://ssl.bblck.me/blacklists/hosts-file.txt)
6. [Joe Wein](http://www.joewein.de/sw/bl-text.htm) spam list - [official](http://www.joewein.net/dl/bl/dom-bl-base.txt)
7. [bkrcrc turk](https://github.com/bkrcrc/turk-adlist) adlist - [official](https://raw.githubusercontent.com/bkrcrc/turk-adlist/master/hosts)

**Comment by notracking** [comment]
**Added:**
1. Fabrice Prigent's only ads list (rest are old domains or already covered)
2. BarbBlocks list (most where already in the list, added for autoupdates)

**Comment by notracking** [comment]
Did a test run and everything is ok, changes will be visible after the next auto update!
