### ISSUE TITLE
new list + refactor

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#220]
Hi, i made a new list and for a better integration i removed some dir to unify all the ioc inside one list

To remove
scafroglia93/hosts-blocklists:pan-unit42/iran-linked-operators.txt@master (raw)
scafroglia93/hosts-blocklists:pan-unit42/mirai.txt@master (raw)

to add
https://github.com/scafroglia93/hosts-blocklists/blob/master/citizenlab.txt

https://github.com/scafroglia93/hosts-blocklists/blob/master/malware-traffic-analysis.txt

https://github.com/scafroglia93/hosts-blocklists/blob/master/pan-unit42.txt

All IoC is made with source for minor false positive

Cheers

**Comment by scafroglia93** [comment]
Only domains, really awesome
- https://github.com/stamparm/blackbook

Take what may be useful, maybe let's talk about the incidence 

- https://github.com/stamparm/maltrail/tree/master/trails/static/malware
- https://github.com/stamparm/maltrail/tree/master/trails/static/suspicious
- https://github.com/stamparm/maltrail/tree/master/trails/static/malicious

**Comment by notracking** [comment]
I've updated the lists you maintain and the blackbook is an absolute beauty, thanks!

Some issues i've found:
 - citizenlab.txt, check `waradena.com 	Waradana`.
 - malware-traffic-analysis.txt, has a false positive: api.ipify.org

**Comment by scafroglia93** [comment]
have you solved or do I have to modify the list ?

as you can see I try to refer everything with authoritative sources

**Comment by notracking** [comment]
I would see those fixes as an improvement for your list :) 

For the notracking list it does not matter, as long as the number of false positives remains under control. These type of errors are corrected automatically.

**Comment by scafroglia93** [comment]
Fix incoming
