### ISSUE TITLE
Further optimization of the domains.txt file

### ISSUE THREAD

**Issue by adworacz** [notracking/hosts-blocklists#221]
While reading the dnsmasq documentation, I noticed something that should allow for cutting the domains.txt file size in half.

> An address specified as '#' translates to the NULL address of 0.0.0.0 and its IPv6 equivalent of :: so --address=/example.com/# will return NULL addresses for example.com and its subdomains. This is partly syntactic sugar  for  --address=/example.com/0.0.0.0  and --address=/example.com/::  but  is  also  more efficient than including both as seperate configuration lines.

So instead of the current format:
```
address=/0--e.info/0.0.0.0
address=/0--e.info/::
address=/000359.xyz/0.0.0.0
address=/000359.xyz/::
```

Things could be shortened to just:
```
address=/0--e.info/#
address=/000359.xyz/#
```

**Comment by notracking** [comment]
This has been suggested before, but the current formatting is on purpose, since the above method will not work reliably (/at all) on slightly older builds of dnsmasq and the performance gain is very, very small (could not even tell the difference).
