### ISSUE TITLE
duplicate entry `queda212..duckdns.org`

### ISSUE THREAD

**Issue by pengelana** [notracking/hosts-blocklists#224]
hostname.txt with duplicate entry:

~~~
0.0.0.0 queda212..duckdns.org
:: queda212..duckdns.org
0.0.0.0 queda212.duckdns.org
:: queda212.duckdns.org
~~~

**Comment by notracking** [comment]
Nice catch! This is actually an invalid hostname (double ..), fixed it in the filter. Changes will be visible with the next autoupdate..!
