### ISSUE TITLE
Misc List

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#227]
ADS
-https://stanev.org/abp/adblock_bg.txt
-http://margevicius.lt/easylistlithuania.txt
-https://raw.githubusercontent.com/tomasko126/easylistczechandslovak/master/filters.txt
-https://notabug.org/latvian-list/adblock-latvian/raw/master/lists/latvian-list.txt
-https://easylist.to/pages/other-supplementary-filter-lists-and-easylist-variants.html

This are for my friend come from other state

Security
-https://github.com/parseword/nolovia/blob/master/skel/hosts-government-malware.txt

**Comment by notracking** [comment]
https://stanev.org/abp/adblock_bg.txt - took one host from this one, remaining fulldomain filters are already covered
https://raw.githubusercontent.com/tomasko126/easylistczechandslovak/master/filters.txt - added
http://margevicius.lt/easylistlithuania.txt - no full domain filters
https://notabug.org/latvian-list/adblock-latvian/raw/master/lists/latvian-list.txt - added

https://github.com/parseword/nolovia/blob/master/skel/hosts-government-malware.txt - added a few manually, mostly already covered.

Thanks!
