### ISSUE TITLE
Hasdd

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#228]
Turning around the web I came across this automatic service
https://hashdd.com/

Some services are already present in the list; 
some of them are really interesting since they are totally automated

We can evaluate the addition

**Comment by notracking** [comment]
I don't want to use services that require registration.

**Comment by scafroglia93** [comment]
No need to register, it's free

Example:

https://hashdd.com/hashdd/cybercrimetracker/

There's a download button, you can grab the feeds for free

**Comment by scafroglia93** [comment]
![Schermata da 2020-02-08 14-43-00](https://user-images.githubusercontent.com/8227101/74086242-f975cf80-4a78-11ea-9c03-a09b0a13e62d.png)

**Comment by notracking** [comment]
Then there still is the problem with these feeds that most of the hosts are hacked websites on shared webhosts. I did some sample checks, but must site have already been cleaned. These feeds give too many false calls. They are way better suited as a threat indicator (as most of them also advertise).
