### ISSUE TITLE
cks-filterlist

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#233]
Really impressive
https://gitlab.com/CHEF-KOCH/cks-filterlist

and it's mantained

**Comment by scafroglia93** [comment]
As always I am available for tests, comparisons and exchange of opinions

**Comment by beerisgood** [comment]
Well Chef-Koch doesn't make any useful stuff in past, but only copy stuff from other people - without any credits.

So what does this list do what other doesn't?

**Comment by scafroglia93** [comment]
There are various list with different type of stat and tracking like qualcomm exc exc

**Comment by scafroglia93** [comment]
https://gitlab.com/CHEF-KOCH/cks-filterlist/-/tree/master/Anti-Corp/hosts
(not all)

https://gitlab.com/CHEF-KOCH/cks-filterlist/-/tree/master/hosts

**Comment by notracking** [comment]
I am familiar with these lists, as you can also see [here](https://github.com/notracking/hosts-blocklists/search?q=KOCH&type=Issues). I'm not sure what the policies are that they use, but almost all of their lists cause heaps and heaps of false positives. 

I did cherry pick some samples (in the past) out of there but those lists are not suited for automated inclusion.

**Comment by beerisgood** [comment]
> 
> Ps. having items list these in your hosts file shows me that the maintainer does not have a basic level of knowledge of dns.
> 

That's strange. Chef-Koch write:

> According to my own security expertise

xD
So nothing change. He only move to Gitlab, start some random new projects and still doesn't know what he do.
It's hard to believe that so much people follow him.
