### ISSUE TITLE
kaspersky + other list

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#234]
This is mine

https://github.com/scafroglia93/hosts-blocklists/blob/master/kaspersky.txt

**Comment by scafroglia93** [comment]
1- https://v.firebog.net/hosts/Prigent-Malware.txt

2- https://github.com/finnish-easylist-addition/finnish-easylist-addition

3- https://raw.githubusercontent.com/lassekongo83/Frellwits-filter-lists/master/Frellwits-Swedish-Hosts-File.txt

Hope will be helpful for scandivanian friends

**Comment by scafroglia93** [comment]
What's the issue with infosec feeds from cert and other security company ?

**Comment by notracking** [comment]
https://v.firebog.net/hosts/Prigent-Malware.txt - see: https://dsi.ut-capitole.fr/blacklists/download/malware.tar.gz (no longer maintained)
https://github.com/finnish-easylist-addition/finnish-easylist-addition - no full domain filters
https://raw.githubusercontent.com/lassekongo83/Frellwits-filter-lists/master/Frellwits-Swedish-Hosts-File.txt - added!
