### ISSUE TITLE
I ask you to make a filter optimized for mobile.

### ISSUE THREAD

**Issue by 7nani4u** [notracking/hosts-blocklists#235]
I am a user of the AdGuard application.
I'm using multiple site references and adding only the filters I need.
(Referenced Sites : https://github.com/EnergizedProtection/block)

https://raw.githubusercontent.com/EnergizedProtection/block/master/spark/formats/filter

https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt

https://raw.githubusercontent.com/theel0ja/CrapBlock/master/block-googlefonts.txt

https://easylist-downloads.adblockplus.org/yt_annoyances_full.txt

https://raw.githubusercontent.com/jawz101/MobileAdTrackers/master/hosts

https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/MobileFilter/sections/specific_app.txt

https://280blocker.net/files/280blocker_domain_ag.txt

https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/badware.txt

https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/resource-abuse.txt

https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/unbreak.txt

https://raw.githubusercontent.com/Yhonay/antipopads/master/popads.txt

https://filters.adtidy.org/android/filters/11_optimized.txt

https://filters.adtidy.org/android/filters/242_optimized.txt

https://filters.adtidy.org/android/filters/3_optimized.txt

https://raw.githubusercontent.com/austinheap/sophos-xg-block-lists/master/steven-blacks-ad-hoc-list.txt

http://malwaredomains.lehigh.edu/files/justdomains

https://raw.githubusercontent.com/mitchellkrogza/The-Big-List-of-Hacked-Malware-Web-Sites/master/hacked-domains.list

https://www.squidblacklist.org/downloads/dg-ads.acl

https://www.jabcreations.com/downloads/adblock-filters.php

Please slow down your browser or exclude and create filters that are not recommended.
(Referenced Sites : https://malwaretips.com/threads/free-system-wide-adblocking-without-adguard.66870)

Social filter (optional)
Do not select Region, Language Filter, or Multi-Purpose Filter (if necessary).
Conflict with other lists.

My guess is that the browser won't slow down until the total number of filters is less than 80,000.
To do so, we may be able to replace "https://raw.githubusercontent.com/EnergizedProtection/block/master/spark/formats/filter" instead of "https://raw.githubusercontent.com/badmojr/1Hosts/master/mini/adblock.txt"

And I'll tell you what filter it would be good to use.

https://hostfiles.frogeye.fr/firstparty-only-trackers-hosts.txt
https://cdn.statically.io/gl/curben/urlhaus-filter/raw/master/urlhaus-filter-online.txt

I hope you can create a filter that is optimized for many filter users, including me.

**Comment by scafroglia93** [comment]
Urlhaus was integrated by default inside Adguard, maybe the problem with AWS was gone
https://twitter.com/abuse_ch/status/1227238713979068419

**Comment by notracking** [comment]
No, I cannot maintain mobile only lists. The coverage should be the same for all generated formats.
