### ISSUE TITLE
whitelist www.kayak.com

### ISSUE THREAD

**Issue by adworacz** [notracking/hosts-blocklists#236]
As a travel planning site, this has great utility and should not be blocked.

I also had to whitelist content.r9cdn.net to get it to work.
```
@@||www.kayak.com^
@@||content.r9cdn.net^
```

**Comment by notracking** [comment]
Thanks!

kayak.com has been whitelisted, r9cdn.com must be blocked by some other list as it's not in ours..
Changes will be visible with the next auto update..!
