### ISSUE TITLE
cedexis.net should be removed from domains.conf

### ISSUE THREAD

**Issue by ext32** [notracking/hosts-blocklists#24]
Breaks mozilla things
 
dig download.cdn.mozilla.net

; <<>> DiG 9.10.3-P4-Debian <<>> download.cdn.mozilla.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 45094
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1

;; ANSWER SECTION:
download.cdn.mozilla.net. 19    IN      CNAME   2-01-2967-001e.cdx.cedexis.net.
2-01-2967-001e.cdx.cedexis.net. 20 IN   CNAME   wildcard.cdn.mozilla.net.edgesuite.net.
wildcard.cdn.mozilla.net.edgesuite.net. 4942 IN CNAME a1284.dscg.akamai.net.
a1284.dscg.akamai.net.  20      IN      A       194.177.211.136
a1284.dscg.akamai.net.  20      IN      A       194.177.211.139

**Comment by notracking** [comment]
Thanks for the submit! Will be removed with the next autoupdate.
