### ISSUE TITLE
amazon-adsystem.com

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#240]
Do you report any problems?
(android 10, Pixel 2 XL)

amazon-adsystem.com

**Comment by scafroglia93** [comment]
![photo_2020-02-18_15-30-15](https://user-images.githubusercontent.com/8227101/74745080-9e579000-5263-11ea-83e1-56e75c432ad5.jpg)

**Comment by scafroglia93** [comment]
![amazon](https://user-images.githubusercontent.com/8227101/74745292-f7272880-5263-11ea-9abb-cc1fa2a1c75f.PNG)

**Comment by notracking** [comment]
I don't seem to have any issues with the exact same search query on amazon.it, can anyone confirm?

**Comment by scafroglia93** [comment]
The issue is for amazon it apps (android).

You can close this issue, i've inserted this domain inside nextdns whitelist

**Comment by josefwells** [comment]
This is breaking my amazon app on android connected to my wifi.  I don't see an easy way of whitelisting this after applying the blacklist.
