### ISSUE TITLE
More List

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#242]
Blog managed by italian infosec researcher
https://www.andreadraghetti.it/block-list-e-white-list-per-pi-hole-e-ad-blocker/

Ads
https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt (full domain)
https://filtri-dns.ga/filtri.txt (full domain)

Malware
- https://mirror1.malwaredomains.com/files/justdomains (full domain)
- https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt (full domain)

**Comment by notracking** [comment]
https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt - too many false calls
https://filtri-dns.ga/filtri.txt - added, though they should not add ips to their hostlist..
https://mirror1.malwaredomains.com/files/justdomains - original is already included
https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt - too many false calls

**Comment by beerisgood** [comment]
> https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt - too many false calls
>
Any example?

>
> https://mirror1.malwaredomains.com/files/justdomains - original is already included
>
Which one is the original?

**Comment by scafroglia93** [comment]
osint.digitalside.it/Threat-Intel/lists/latestdomains.txt

Sure ? False calls ?

**Comment by notracking** [comment]
@beerisgood, https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt it did improve though. I do understand that some of these whitelist entries are in the grey area.
```0.0.0.0 gstaticadssl.l.google.com
0.0.0.0 loggly.com
0.0.0.0 arc.msn.com
0.0.0.0 vidible.tv
0.0.0.0 assets.adobedtm.com
0.0.0.0 c.evidon.com
0.0.0.0 v20.vortex-win.data.microsoft.com
0.0.0.0 v10.vortex-win.data.microsoft.com
0.0.0.0 etl.tindersparks.com
0.0.0.0 hello.myfonts.net
0.0.0.0 s.click.aliexpress.com
0.0.0.0 yui.yahooapis.com
0.0.0.0 msedge.net
0.0.0.0 v10.vortex-win.data.microsoft.com
0.0.0.0 v10.events.data.microsoft.com
0.0.0.0 jwpltx.com
0.0.0.0 bestfwdservice.com
0.0.0.0 s0.2mdn.net
0.0.0.0 graph.instagram.com
0.0.0.0 schibsted.io
0.0.0.0 sentry.io
0.0.0.0 hockeyapp.net
0.0.0.0 cdns.gigya.com
0.0.0.0 s.zkcdn.net
0.0.0.0 manifest.auditude.com
0.0.0.0 cdn-gl.imrworldwide.com
0.0.0.0 seccdn-gl.imrworldwide.com
```
https://mirror1.malwaredomains.com/files/justdomains, see: http://malwaredomains.lehigh.edu/files/BOOT

@scafroglia93: As explained before, hosts files that are based on malware url's are tricky and should mostly be used in detection systems. I would like to avoid having to whitelist sites like `pastebin.com` `cdn.discordapp.com` `googleusercontent.com` etc.

**Comment by scafroglia93** [comment]
don't worry, the second one was mantained manually.

It's not a honeypot of host, you can add it without any issue

**Comment by beerisgood** [comment]
> 
> https://mirror1.malwaredomains.com/files/justdomains, see: http://malwaredomains.lehigh.edu/files/BOOT
> 
Well the "original" then doesn't use TLS: https://www.ssllabs.com/ssltest/analyze.html?d=malwaredomains.lehigh.edu so i stay with the mirror

**Comment by notracking** [comment]
@scafroglia93, it's good that it's manually maintained, but their moderation policy does not match ours if they include hosts as described in my previous reply. I will not add this one.

@beerisgood , I do trust my upstream providers not to inject/manipulate anything but I will update it!
