### ISSUE TITLE
ajax.cloudflare.com is bad to add to the list. 

### ISSUE THREAD

**Issue by mverrilli** [notracking/hosts-blocklists#25]
https://github.com/notracking/hosts-blocklists/blob/a6c5beab048b049cf0513554d69f6a5215c0e043/hostnames.txt#L5372

**Comment by mverrilli** [comment]
Looks like it is coming from: 

https://raw.githubusercontent.com/k2jp/abp-japanese-filters/master/abpjf.txt

**Comment by notracking** [comment]
You are correct, thanks for the submit! Host will be removed with the next auto update.

**Comment by mverrilli** [comment]
Thanks! I also reported it to k2jp/abp-japanese-filters however after looking over their other issues... they seem quite happy with being overly aggressive in their selection criteria killing standard website functionality because it might be used in ads.

They also only support Japanese speaking people or folks who live in Japan and point to this support policy often.

**Comment by notracking** [comment]
I keep track of the sources for false positives; this list will get some extra attention ;)
