### ISSUE TITLE
Remove all *.salesforce.com

### ISSUE THREAD

**Issue by milue** [notracking/hosts-blocklists#252]
several Salesforce.com subdomains (e.g. partners.salesforce.com) are blocked. I think this is a false positive

**Comment by notracking** [comment]
What does it break for the end user? Do you have some site(s) as an example?

**Comment by milue** [comment]
Can't login to the respective salesforce org, as a partner user the partner portal from salesforce can't be opened. This is e.g. the partners.salesforce.com
It's a huge business platform with billions of users and if they are located on one of the servers they can't use it.

**Comment by notracking** [comment]
Whitelisted all *partners.salesforce.com hostnames, that should do. Thanks for the feedback!
Changes will be visible with the next auto update.
