### ISSUE TITLE
Tracker Radar

### ISSUE THREAD

**Issue by pengelana** [notracking/hosts-blocklists#253]
https://spreadprivacy.com/duckduckgo-tracker-radar/

**Comment by beerisgood** [comment]
Or better link:
https://github.com/duckduckgo/tracker-radar/issues/2#issuecomment-595807504
;)

**Comment by notracking** [comment]
I noticed this one as well, will need to parse it (properly), but first sanity checks do not look promising because of all the listed cdns. Will followup!

**Comment by notracking** [comment]
Checked it, but it's simply not suited for dns level blocking. Would be a nice addition for content (Adblock Plus plus) style blockers though (set everything as 3rd party request block).
