### ISSUE TITLE
Country Adblock

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#254]
This is the entire list of source form energized, I have used it for a week but the lists block too many legitimate sites and in addition the support is very lacking

There would be a list called regional where adblocks are placed by country ->

Regional ->
ABPindo, AdBlockID, Adblock Estonian & Iran, Adguard Dutch, English, French, German, Japanese, Russian, Turkish & Spanish - Portuguese Filter, Easylist Brasil, Bulgarian, China, Czech & Slovak, Dutch, French, Germany, Hebrew, Italy, India, Korea Latvian, Polish, Romanian, Russian, Spanish and Thailand, Fanboy's Indian & Vietnamese, HostsVN, Liste AR, Polish Adblock & Privacy Filters, RUAdList and Thai Ads Filter

Source -> 
https://github.com/EnergizedProtection/block/blob/master/assets/sources/sources.json
https://github.com/EnergizedProtection/block/blob/master/extensions/regional/build.sh

Tell if you found someone 

PS
Enjoy donation

**Comment by notracking** [comment]
Thanks again for your donations, this really helps covering the costs of the server!

Splitting up the blocklist in country categories will never happen, since there is no use doing so. It is simply not possible to define a reliable set of criteria to sort them. 

I will look into those to see if there are any lists that could be a nice addition..!

**Comment by scafroglia93** [comment]
take your time as always

**Comment by notracking** [comment]
Thanks! I've added the following:

https://gurud.ee/ab.txt
https://raw.githubusercontent.com/farrokhi/adblock-iran/master/filter.txt
https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/SpywareFilter/sections/tracking_servers_firstparty.txt
https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/SpywareFilter/sections/tracking_servers.txt
https://easylist-downloads.adblockplus.org/adwarefilters.txt
https://www.zoso.ro/pages/rolist.txt
https://raw.githubusercontent.com/HexxiumCreations/threat-list/gh-pages/hexxiumthreatlist.txt
https://raw.githubusercontent.com/olegwukr/polish-privacy-filters/master/adblock.txt
https://gitlab.com/Kurobeats/phishing_hosts/raw/master/hosts
https://raw.githubusercontent.com/bigdargon/hostsVN/master/option/hosts-VN
