### ISSUE TITLE
whilelist zoho

### ISSUE THREAD

**Issue by paolostivanin** [notracking/hosts-blocklists#258]
Hello,
I saw that zoho has been blaclisted and, thus, zoho email can no longer be accessed. 
Could you please whitelist it?

Thanks

**Comment by scafroglia93** [comment]
@notracking 

debug -> https://www.stopforumspam.com/downloads/toxic_domains_whole.txt

zoho.com
zoho.in

**Comment by notracking** [comment]
Fixed, thanks!
