### ISSUE TITLE
I may have used your lists.

### ISSUE THREAD

**Issue by smokingwheels** [notracking/hosts-blocklists#26]
I followed the advise of W3K it makes it easer to download for the Pi-Hole.

W3K said.
We’d suggest checking out GH pages. It’s free and PH won’t redownload the blocklist if there’s no new changes - W3K
[https://twitter.com/The_Pi_Hole/status/920758922121641984](https://twitter.com/The_Pi_Hole/status/920758922121641984)

If you would like to have a special note could you create an issue, I have also done work on you list to make it more acceptable for the Pi-hole.
[https://github.com/smokingwheels/smokingwheels.github.io](https://github.com/smokingwheels/smokingwheels.github.io)
At the moment I need a bit of time to relax and have a rest.

**Comment by notracking** [comment]
Hi there,

Thank you for forking our repository! We encourage anyone to re-use the hosts-blocklist files. If you happen to find any issues with our list, feel free to create a ticket or a pull request.

Good luck with the fork!
