### ISSUE TITLE
new list

### ISSUE THREAD

**Issue by notracking** [notracking/hosts-blocklists#261]
https://raw.githubusercontent.com/smed79/blacklist/master/hosts.txt

**Comment by scafroglia93** [comment]
Have you seen this ?
https://github.com/Ultimate-Hosts-Blacklist

**Comment by notracking** [comment]
https://raw.githubusercontent.com/smed79/blacklist/master/hosts.txt: added

@scafroglia93 Yes I have :) thanks for notifying though.
