### ISSUE TITLE
Remove coronavirus.app

### ISSUE THREAD

**Issue by srett** [notracking/hosts-blocklists#264]
https://coronavirus.app is just a crowd-sourced map, no malware. However it's pulled in via https://infosharing.cybersaiyan.it/feeds/CS-PIHOLE (I think). I didn't immediately find how to reach out to the owner of that list though, so I'm opening an issue here.

**Comment by notracking** [comment]
Super, thanks! Added to whitelist, changes will be visible after the next auto update..
