### ISSUE TITLE
CDN from LocalCDN (FF Addons)

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#268]
* ajax.googleapis.com 
* ajax.aspnetcdn.com 
* ajax.microsoft.com
* cdnjs.cloudflare.com 
* code.jquery.com 
* cdn.jsdelivr.net
* yastatic.net 
* yandex.st
* apps.bdimg.com 
* libs.baidu.com
* cdn.staticfile.org
* cdn.bootcss.com 
* mat1.gtimg.com
* lib.baomitu.com 
* lib.sinaapp.com
* upcdn.b0.upaiyun.com 
* stackpath.bootstrapcdn.com 
* maxcdn.bootstrapcdn.com 
* netdna.bootstrapcdn.com 
* use.fontawesome.com 
* ajax.cloudflare.com
* akamai-webcdn.kgstatic.net 
* sdn.geekzu.org 
* ajax.proxy.ustclug.org 
* unpkg.com

**Comment by notracking** [comment]
dns blocking these is not a good idea, as it will break many, many sites.

A better solution is to use Decentralize (browser addon), that will dynamically detect CDNs and cache their content on your local pc.
