### ISSUE TITLE
Add CoinBlockerLists

### ISSUE THREAD

**Issue by ZeroDot1** [notracking/hosts-blocklists#27]
Simple lists that can help prevent cryptomining in the browser or other applications.
https://github.com/ZeroDot1/CoinBlockerLists

**Comment by notracking** [comment]
Thank you for your submission!

I recently added another coin miner list. As soon as I can find the time I will compare and add the one(s) that are best suited. To be continued...

**Comment by notracking** [comment]
I submitted a ticket to your repos with some hosts that you might consider to check again:

https://github.com/ZeroDot1/CoinBlockerLists/issues/50

**Comment by notracking** [comment]
I've replace the original anti webminer list with your webbrowser list. I did hoever whitelist the domains that I noted in the submitted ticket.
