### ISSUE TITLE
block domain request

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#273]
took from work so it's not reccomended create a list

northcountrysocial.com
burtontracks.com
tvfconnections0.us-south.cf.appdomain.cloud
live.investtoimpressclub.com
hellokittyvietnam.com
offplanetthemovie.com
weddingphotographernorwich.com
pool.minexmr.com
mypolkadotphoto.com
headclosesamsiah.workforcefinder.co.uk
i-jjj.tk
blog.diogene-atmosphere.com
www.hellasportal.com
autocraftmedia.com
diabeteshelptoday.com
assomise.com.br
63notes.com
animaskin.no
aldgateeastescorts4u.eu
crumerycpa.com
10bestdatingsites.dev.belugalab.com
abrtl.com
anime-tuner.square7.ch
abisoglu.com
atcoghost.com

**Comment by notracking** [comment]
I will check and add them to the custom list.

**Comment by notracking** [comment]
Added to the custom list.., thanks!
