### ISSUE TITLE
walgreens website blocked

### ISSUE THREAD

**Issue by emlimap** [notracking/hosts-blocklists#279]
The following filter is blocking access to walgreens.com

`||inscname.net^`

The domain appears to be part of instart logic and walsgreen main domain is using them as CNAME

```
$ dig +short www.walgreens.com
www.walgreens.com.inscname.net.
pciins-041.inscname.net.
a-walgreens-001.insnw.net.
159.180.84.17
```

**Comment by notracking** [comment]
Had to whitelist both `inscname.net insnw.net`, changes will be visible with the next auto update.

Thanks!
