### ISSUE TITLE
Remove pr0gramm from hostnames.txt

### ISSUE THREAD

**Issue by zwiebelchen** [notracking/hosts-blocklists#28]
Could you remove pr0gramm.com from hostnames.txt?

**Comment by notracking** [comment]
Hi there,

Thanks for the feedback!

I've already added some pr0gramm.com entries to the whitelist this morning. They should be removed with the next auto update. The source causing this is the new adminer list, where I also created a ticket. Please validate that list and let me know if there are more false positives releated to the programm.com domain. Ticket: https://github.com/ZeroDot1/CoinBlockerLists/issues/50

**Comment by notracking** [comment]
And programm is working again, only left the mining address blocked.
