### ISSUE TITLE
Halve domain.txt size

### ISSUE THREAD

**Issue by giovannikraushaar** [notracking/hosts-blocklists#280]
According to https://wiki.archlinux.org/index.php/Dnsmasq it is enough to insert address=/blacklisted.example/ without specifying the IP address to block it. Using this approach would reduce the file size since it avoids to block the same domain twice (once for IPv4 and once for IPv6).

**Comment by notracking** [comment]
This has been discussed several times before, see https://github.com/notracking/hosts-blocklists/issues/191
