### ISSUE TITLE
newlist -> bitdefender

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#281]
https://github.com/scafroglia93/hosts-blocklists/blob/master/bitdefender.txt

**Comment by notracking** [comment]
The content is good, keep it up! But would it be possible to merge all these types of list into a single one? That would save me a lot of hassle updating the scripts every time.. Plus it would be easier to report back false calls.

**Comment by scafroglia93** [comment]
My strategy was the following:

- single list if the site provides constant information

- common list where you can enter the information I find for the internet

The methodology is the same

**Comment by scafroglia93** [comment]
I'm working on the common list, bitdefender will come in with that
