### ISSUE TITLE
(whitelist) tokopedia.app.link

### ISSUE THREAD

**Issue by 3xploiton3** [notracking/hosts-blocklists#282]
![](https://i.imgur.com/KiyslYH.jpg)

Priceza app didn't work

**Comment by notracking** [comment]
I cannot find this domain in the list..?

> grep tokopedia.app.link * |wc -l
> 0

**Comment by notracking** [comment]
Whitelisted `app.link`, changes will be visible with the next autoupdate..!

Thanks!
