### ISSUE TITLE
Online betting site blocked

### ISSUE THREAD

**Issue by K2rool** [notracking/hosts-blocklists#29]
Hi, the online betting site Bet365 is currently getting blocked due to being listed.
<pre>address=/bet365.com/0.0.0.0 </pre>

Many thanks for the blocklist not seen many fp over the last few days of using it.

**Comment by notracking** [comment]
Thanks for the feedback! It's much appriciated; in case you find more please let me know.
bet365.com domain and www.bet365.com are added to the whitelist; changes will be visible with the next auto update.

badboyz.txt:0.0.0.0 bet365.com
someonewhocares.txt:0.0.0.0 www.bet365.com
steveblack.txt:0.0.0.0 bet365.com
steveblack.txt:0.0.0.0 www.bet365.com
