### ISSUE TITLE
Carrefour.es don't work (uqsxy.x.incapdns.net)

### ISSUE THREAD

**Issue by Dragonfir3** [notracking/hosts-blocklists#291]
Hi,

This supermarket website is blocked.

I found that static.carrefour.es have CNAME to uqsxy.x.incapdns.net (listed). Also vofcw7x.x.incapdns.net is listed, I don't know if this affect to other clean websites.

I checked domains in last sources added without success.

**Comment by notracking** [comment]
Thanks for the feedback! Items have been added to the whitelist. Changes will be visible after the next auto update.
