### ISSUE TITLE
www.hcaptcha.com

### ISSUE THREAD

**Issue by emlimap** [notracking/hosts-blocklists#295]
Access to www.hcaptcha.com is blocked by the following filter when the list is used with any DNS based adblocker that enforces CNAME blocking

`proxy-ssl.webflow.com`

webflow seems to be SaaS CMS similar to square space

```
❯ dig +short www.hcaptcha.com
proxy-ssl.webflow.com.
76.223.9.102
13.248.141.96
```

**Comment by notracking** [comment]
Excellent find, thanks! Added to the whitelist, changes will be visible after the next auto update.
