### ISSUE TITLE
nextdns.io blocked

### ISSUE THREAD

**Issue by crssi** [notracking/hosts-blocklists#296]
I am not saying that `nextdns.io` should or should not be on the list.

But just a question where did it come from?

Thank you and cheers

**Comment by notracking** [comment]
Thanks! The 280 list got removed, had too many false positives. Should not have added that one in the first place..

Changes will be visible after the next auto update!

**Comment by crssi** [comment]
Thank you 😄

**Comment by scafroglia93** [comment]
@notracking 
I don't have find nextdns.io insde 280 maybe i miss someone ?
