### ISSUE TITLE
Single tar.gz file 

### ISSUE THREAD

**Issue by mmatczuk** [notracking/hosts-blocklists#30]
Would it be possible to provide a single tar.gz file containing `domains.txt` and `hostnames.txt`?

**Comment by notracking** [comment]
Hi,

What would be the usecase for that?

**Comment by mmatczuk** [comment]
This would simplify the download process. It could work like `curl | tar`, single command, single connection, less resources needed.

**Comment by notracking** [comment]
You can already download both files with a single curl command:

`curl -O https://raw.githubusercontent.com/notracking/hosts-blocklists/master/hostnames.txt -O https://raw.githubusercontent.com/notracking/hosts-blocklists/master/domains.txt`

**Comment by mmatczuk** [comment]
That's cool didn't know that.

**Comment by Crazy-Hopper** [comment]
Or even easier ;-)

curl 'https://raw.githubusercontent.com/notracking/hosts-blocklists/master/{hostnames,domains}.txt' -o "#1.txt"

**Comment by notracking** [comment]
Like a boss!
