### ISSUE TITLE
False positive - geoloc.arte.tv

### ISSUE THREAD

**Issue by lyrad87** [notracking/hosts-blocklists#301]
Hello there, I found a false positive. If "geoloc.arte.tv" is blocked then the Arte media library on tvOS (I'm running tvOS 13.4) cannot be started. This may apply to the website or other official apps from Arte as well but I haven't tested it.

ARTE (Association relative à la télévision européenne) is a Franco-German free-to-air television network that promotes cultural programming and has many documentaries, concerts and series available online in its media library.

I manually whitelisted it right now but thought I ask if you could remove this domain from your list instead.

**Comment by notracking** [comment]
Nice one, thanks! I've whitelisted it, changes will be visible after the next auto update.
