### ISSUE TITLE
new lists -> scafroglia93 blocklists

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#302]
As per request I have created a single list, I will make two more in order to have more control so I can also insert IoCs that do not have a defined group.

Everything will be managed as before, with references

Link ->
https://github.com/scafroglia93/blocklists/blob/master/blocklists-main.txt

You can delete the others without problems

**Comment by notracking** [comment]
Thank you sir, I will merge soon when I have some spare time..!

**Comment by scafroglia93** [comment]
Check out the other lists when you have time.

Hope you liked it

**Comment by scafroglia93** [comment]
It's all ok ?
Please stay safe

**Comment by scafroglia93** [comment]
Major clean done !

https://github.com/scafroglia93/blocklists/commit/ad6697d5e8b8ae4b8a487f80b55b7b62713c1bd7

**Comment by notracking** [comment]
Many thanks sir, again. Sorry for the delay (busy times offline...). Lists have been updated!

**Comment by scafroglia93** [comment]
It is a pleasure to be able to collaborate for a common project
