### ISSUE TITLE
Add support for unbound.conf format?

### ISSUE THREAD

**Issue by agrajag9** [notracking/hosts-blocklists#308]
Any chance of revealing how the lists are actually built? I see what they're aggregated from in the sources file, but there's clearly some magic still happening inbetween the original sources and the actual configs here.

I was able however to whip up an awk script to convert `domains.txt` and `hostnames.txt` into a format consumable by unbound:

```
#!/usr/bin/awk
# To convert dnsmasq domains and hostnames files to unbound confs
# Adjust SINKHOLE4 and SINKHOLE6 as needed

BEGIN {
	FS=" "
	SINKHOLE4 = "0.0.0.0"
	SINKHOLE6 = "::"
	TTL = 86400
	print "server:"
}
{
	if ($1 == "0.0.0.0") {
		print "\tlocal-zone: \""$2".\" redirect"
		print "\tlocal-data: '"$2". "TTL" IN TXT \"Redirected per https://github.com/notracking/hosts-blocklist\"'"
		print "\tlocal-data: \""$2". "TTL" IN A "SINKHOLE4"\""
	}
	else if ($1 == "::") {
		print "\tlocal-data: \""$2". "TTL" IN AAAA "SINKHOLE6"\""
	}
	else if ($0 ~ /^address=\/.*\/0\.0\.0\.0$/) {
		split($0, domain, "/")
		print "\tlocal-zone: \""domain[2]".\" redirect"
		print "\tlocal-data: '"domain[2]". "TTL" IN TXT \"Redirected per https://github.com/notracking/hosts-blocklist\"'"
		print "\tlocal-data: \""domain[2]". "TTL" IN A "SINKHOLE4"\""
	}
	else if ($0 ~ /^address=\/.*\/::$/) {
		split($0, domain, "/")
		print "\tlocal-data: \""domain[2]". "TTL" IN AAAA "SINKHOLE6"\""
	}
	else {
		print $0
	}
}
```

**Comment by mpoletiek** [comment]
A quick google and I found this: https://gist.github.com/christoph-frick/b7d1d09c6fab55c9946284b73975a547

`curl https://raw.githubusercontent.com/notracking/hosts-blocklists/master/hostnames.txt | grep '^0.0.0.0' | awk '{ print "local-zone: \"" $2 "\" refuse" }' > ad-blocking-data.conf`

**Comment by notracking** [comment]
I still need to look into the details of ubound filtering capabilities. This requires some effort setting up a test bench etc.. This will be addressed in time, but not the highest prio item on the list now.

By the first looks of it I think we can support it with an official list, give it some time.. ;)

@mpoletiek Please be aware that hostnames,txt should alway be combined with domains.txt. Or just parse the dnscrypt version of the list.

**Comment by mpoletiek** [comment]
@notracking Are you referring to this? https://github.com/notracking/hosts-blocklists/blob/master/dnscrypt-proxy/dnscrypt-proxy.blacklist.txt

**Comment by notracking** [comment]
@mpoletiek yes

**Comment by mpoletiek** [comment]
Ended up going with the following...

`curl https://raw.githubusercontent.com/notracking/hosts-blocklists/master/dnscrypt-proxy/dnscrypt-proxy.blacklist.txt | sed '/^#.*/d' | awk '{ print "local-zone: \"" $1 "\" redirect \r\n local-data: \"" $1 " CNAME blocked.example.com\"" }' > /etc/unbound/unbound.conf.d/blacklist.conf`

One could also use the following.

`curl https://raw.githubusercontent.com/notracking/hosts-blocklists/master/dnscrypt-proxy/dnscrypt-proxy.blacklist.txt | sed '/^#.*/d' | awk '{ print "local-zone: \"" $1 "\" redirect \r\n local-data: \"" $1 " A 127.0.0.1\"" }' > /etc/unbound/unbound.conf.d/blacklist.conf`

**Comment by notracking** [comment]
Should the correct format no be like (for NXDOMAIN returns)?
```
local-zone: "ads.adhost.com" static
local-zone: "evilhost1.com" static
local-zone: "evilhost2.com" static
```

From [unbound documentation](https://nlnetlabs.nl/documentation/unbound/unbound.conf/)
```
            static
                 If  there  is a match from local data, the query is answered.
                 Otherwise, the query is answered  with  nodata  or  nxdomain.
                 For  a  negative  answer  a  SOA is included in the answer if
                 present as local-data for the zone apex domain.
```

**Comment by mpoletiek** [comment]
@notracking 

I'm using the redirect statement in order to present my users with a page that informs them why this particular domain is not being resolved as they might expect.

**Comment by agrajag9** [comment]
Yes, we would want to use a static local-zone in the server options, but we should also have local-data for the A and AAAA records. It triples the output filter size and adds a tiny bit of complexity, but in the long run it makes it easier to redirect to a blockpage/sinkhole.

e.g.:

```
server:
    local-zone: "ads.adhost.com" static
    local-data: "ads.adhost.com IN A 0.0.0.0"
    local-data: "ads.adhost.com IN AAAA ::0"
```

And if a user wants to redirect to a custom sinkhole they just replace `0.0.0.0` and `::0` with the sinkhole address.

**Comment by mpoletiek** [comment]
@agrajag9 What if I didn't want to send the user to an IP Address as the blockpage/sinkhole, but a domain name instead? 

Could I use the following?

`
local-zone: "ads.adhost.com" static`
`
local-data: "ads.adhost.com" CNAME sinkhole.example.com
`

**Comment by agrajag9** [comment]
I don't see anything obviously wrong with it, but this will mask all your sinkhole hits. Using the example above, if you were logging on your sinkhole then you may not know that the client was attempting to query for `ads.adhost.com` unless you're also logging all DNS queries in unbound as well as in your sinkhole.

**Comment by mpoletiek** [comment]
Understood,

Yeah, I want my sinkhole to report back to the user what domain was blocked for awareness and to potentially identify false positives. 

So I'll continue to use `redirect`.

**Comment by agrajag9** [comment]
We should also test with `inform_redirect` as that will generate more log events. It will incur some performance impact on the nameserver itself as it adds disk iops, but that may be asynchronous and as such not impact clients. That said, I think that's mostly going to be impactful to larger implementations with thousands of clients, not your typical home lan with a few laptops and phones.

**Comment by agrajag9** [comment]
Also be sure to append a `.` to the end of the zone/domain as that's the appropriate way to anchor it. For example `example.com.`

**Comment by mpoletiek** [comment]
Do we need the `.` in the `local-zone:` or the `local-data:` step or both?

**Comment by agrajag9** [comment]
Both is ideal

**Comment by Yunogamer** [comment]
just

local-zone: "domain.here" static

is needed. adding a local-data for each local-zone will eat a ton of ram, with my 4gb ram x86 router unbound wont even start with that method, with 1.16m lines. with just the example above, it uses only 548mb ram (3 threads set in conf), and returns nxdomain which is better than 127.0.0.1 anyway.

for whitelist just do

local-zone: "whitelist.here" transparent

the quotes and spaces must be as displayed. add all local-zone to a separate empty file and add the include: to unbound conf. mine for example is include: "/jffs/etc/adblock.conf".

this is also far faster than dnsmasq. with 1.16m lines on dnsmasq "address=/domain.here/" method on a i3 4150 locked at 3.5ghz i was getting +95ms added to every query, with the cpu allowed to idle at 800mhz, that was +180ms. on my netgear r7800 back when my list was 1m lines, and it's cpu maxed at 1.7ghz, i had >+350ms per query cause ARM sucks, and thats a high end ARM router...

with unbound method i listed above using my same converted list, i get +<1ms per query with the cpu allowed to idle at 800mhz, not needed to always run at max freq anymore to help reduce lookup overhead.

**Comment by agrajag9** [comment]
>just
>
>local-zone: "domain.here" static
>
>is needed

Yes, from the client perspective. But you still need the `local-data` lines if you intend to redirect clients to a sinkhole instead of just squashing the request entirely.

>with my 4gb ram x86 router unbound wont even start with that method, with 1.16m lines. with just the example above, it uses only 548mb ram (3 threads set in conf), and returns nxdomain which is better than 127.0.0.1 anyway.

Do you mind sharing your full conf in a gist? I've been running this list with a sinkhole now since before my first post with all the `local-data` lines, on an even more resource-constrained system than this, with absolutely no problems. It does take some time to start the `local_unbound` service, but once it's up it's incredibly performant. I can go back and pull more stats from my system, but what you're describing sounds more like an issue elsewhere in your conf or a memory leak in your build.

>netgear r7800
>high end ARM router

I would not recommend running any sort of caching nameserver on a platform like the R7800. This model uses a IPQ8065, based on the Krait 300, which is different from but similar to the Cortex-A15. Compare that to the RPi4 which has 4x full Cortex-A72 cores. Then look at things Arm platforms like MACHIATTObin and Layerscape, the latter of which can even move 100Gbps.

**Comment by Yunogamer** [comment]
> 
> 
> > just
> > local-zone: "domain.here" static
> > is needed
> 
> Yes, from the client perspective. But you still need the `local-data` lines if you intend to redirect clients to a sinkhole instead of just squashing the request entirely.

i suppose only if the user wants a redirect to a blank pixel or something but other than that, everyone wanting nxdomain, dont need local-data. some devices and software go into a loop of retries when they notice a domain exists, but gets no reply from it vs "domain does not exist".

> 
> > with my 4gb ram x86 router unbound wont even start with that method, with 1.16m lines. with just the example above, it uses only 548mb ram (3 threads set in conf), and returns nxdomain which is better than 127.0.0.1 anyway.
> 
> Do you mind sharing your full conf in a gist? I've been running this list with a sinkhole now since before my first post with all the `local-data` lines, on an even more resource-constrained system than this, with absolutely no problems. It does take some time to start the `local_unbound` service, but once it's up it's incredibly performant. I can go back and pull more stats from my system, but what you're describing sounds more like an issue elsewhere in your conf or a memory leak in your build.
> 

https://gist.github.com/Yunogamer/ebb3fc46b7ea78d2cf39a5522d24b83a

**Comment by notracking** [comment]
Thanks all for lookiung in to this, there is quite some options in unbound I notice ;)

Please correct me if I'm wrong, but I always prefer to 0.0.0.0 route blocked queries (or send a valid record witout data, as dnscrypt-proxy does) to prevent browsers from automatically searching for similar domains (feature for typo's) when receiving a NXDOMAIN return.

Can unbound do something similar as dnscrypt-proxy does (HEADER status -> NOERROR)?

```
; <<>> DiG 9.11.5-P4-5.1+deb10u1-Debian <<>> 002it.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 59752
;; flags: qr ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;002it.com.                     IN      A

;; ANSWER SECTION:
002it.com.              1       IN      HINFO   "This query has been locally blocked" "by dnscrypt-proxy"

;; Query time: 0 msec
;; SERVER: 10.9.0.1#53(10.9.0.1)
;; WHEN: Tue Jun 09 09:19:29 CEST 2020
;; MSG SIZE  rcvd: 104

```

**Comment by Yunogamer** [comment]
> 
> 
> Thanks all for looking in to this, there is quite some options in unbound I notice ;)
> 
> Please correct me if I'm wrong, but I always prefer to 0.0.0.0 route blocked queries (or send a valid record without data, as dnscrypt-proxy does) to prevent browsers from automatically searching for similar domains (feature for typo's) when receiving a NXDOMAIN return.
> 
> Can unbound do something similar as dnscrypt-proxy does (HEADER status -> NOERROR)?
> 
> ```
> ; <<>> DiG 9.11.5-P4-5.1+deb10u1-Debian <<>> 002it.com
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 59752
> ;; flags: qr ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
> 
> ;; OPT PSEUDOSECTION:
> ; EDNS: version: 0, flags:; udp: 4096
> ;; QUESTION SECTION:
> ;002it.com.                     IN      A
> 
> ;; ANSWER SECTION:
> 002it.com.              1       IN      HINFO   "This query has been locally blocked" "by dnscrypt-proxy"
> 
> ;; Query time: 0 msec
> ;; SERVER: 10.9.0.1#53(10.9.0.1)
> ;; WHEN: Tue Jun 09 09:19:29 CEST 2020
> ;; MSG SIZE  rcvd: 104
> ```

try

local-zone: "domain.here" refuse

**Comment by agrajag9** [comment]
@Yunogamer I don't see anything immediately wrong with your conf, but it still seems weird that it's balooning so much in memory. That's definitely not normal and might be worth asking about over in NLnet's repo.

Also don't forget to append a `.` to domains in your `local-zone` lines or unbound may treat it as a relative domain rather than absolute.

**Comment by Yunogamer** [comment]
> 
> 
> Also don't forget to append a `.` to domains in your `local-zone` lines or unbound may treat it as a relative domain rather than absolute.

whats the difference? i tried it when i was converting the list to unbound format, but it seemed to do nothing? currently my list is

local-zone: "first.domain" static
local-zone: "second.domain" static

etc, whitelists using transparent instead of static, without a period, functioning as expected.

**Comment by agrajag9** [comment]
This will prevent unbound from attempting other local zones as well. For example, say we have the local zone `example.com.` and a client does a lookup for `ad-cdn.net`. In some situations, unbound may attempt to query `ad-cdn.net.example.com` UNLESS the local zone data is anchored with a trailing `.`.

**Comment by rbugajewski** [comment]
The version with `local-zone` and `local-data` takes approximately 2.1 GB on my machine which is perfectly fine in my opinion. My version takes everything into account from this discussion so far, adds the trailing dot, uses `\n` as a line break, and removes some misalignment:

```
curl https://raw.githubusercontent.com/notracking/hosts-blocklists/master/dnscrypt-proxy/dnscrypt-proxy.blacklist.txt | sed '/^#.*/d' | awk '{ print "\tlocal-zone: \"" $1 ".\" static \n\tlocal-data: \"" $1 ". IN A 0.0.0.0\"" }' > blacklist.conf
```

I also wrote a short script (located at `/usr/local/etc/unbound/update_blacklist.sh`) which automatically updates the blacklist. I call this script every night via a cron job. The script also dumps the current cache before unbound is restarted and loads it afterwards:

```
#!/bin/sh

BLKLST="blacklist.conf"
CACHE="unbound_cache.dump"

unbound-control dump_cache > $CACHE
curl https://raw.githubusercontent.com/notracking/hosts-blocklists/master/dnscrypt-proxy/dnscrypt-proxy.blacklist.txt | sed '/^#.*/d' | awk '{ print "\tlocal-zone: \"" $1 ".\" static \n\tlocal-data: \"" $1 ". IN A 0.0.0.0\"" }' > blacklist.conf
{ printf 'server:\n'; cat $BLKLST; } > tmp.txt && mv tmp.txt $BLKLST
service unbound restart
unbound-control load_cache < $CACHE
rm $CACHE
``` 

The `server` directive is also prepended. In order to use the blacklist you need to add the following directive to `unbound.conf`:

```
include: "/usr/local/etc/unbound/blacklist.conf"
```

The cron job looks like this:

```
42 3 * * *  cd /usr/local/etc/unbound && ./update_blacklist.sh
```

**Comment by brodyhoskins** [comment]
I wrote a small Ruby gem that accomplishes this (it uses the NXDOMAIN method). It might be pretty heavy to install on something like a router though.

https://github.com/brodyhoskins/dns-sniper

**Comment by notracking** [comment]
Thanks all! I've added an unbound list, based on @rbugajewski parser.

**Comment by mpoletiek** [comment]
Thank you!
