### ISSUE TITLE
More to whitelist.

### ISSUE THREAD

**Issue by Crazy-Hopper** [notracking/hosts-blocklists#31]
Hi, blocking graph.facebook.* and graph.instagram.* breaks these mobile clients.
Also, blocking the whole kiev.ua zone is definitely an overkill.

**Comment by notracking** [comment]
Added kiev.ua to the whitelist. I should still check the FB domains, as far as I know those app still work with these blocked. I will verify later.

thanks for the feedback!

**Comment by notracking** [comment]
Also the graph hostnames have been remove, thanks for the suggestions!

**Comment by Crazy-Hopper** [comment]
It seems graph hosts sneaked into the files anyway. ;-)

**Comment by notracking** [comment]
Ow, I see. Good call! Next update they will be gone (I promise ;))

**Comment by Crazy-Hopper** [comment]
Another domain to whitelist: netlify.com :-)

**Comment by notracking** [comment]
And same story as before, only this time i will do it right on the first try ;)
Please create a new ticket the next time, or I will miss your valuable feedback.

Thanks again!
