### ISSUE TITLE
new list -> malware -> azorult-tracker

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#312]
Source ->
https://azorult-tracker.net

List ->
fck (my mistake)

**Comment by notracking** [comment]
Do they supply plain hostfiles with only 'last known online < 24hours ago'?

**Comment by scafroglia93** [comment]
Correct List
https://azorult-tracker.net/api/list/domain?format=plain

**Comment by notracking** [comment]
Thanks for the info, very nice list, well maintained / verified. Added!
