### ISSUE TITLE
new list -> phishing.mailscanner.info

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#315]
http://phishing.mailscanner.info/phishing.bad.sites.conf

**Comment by notracking** [comment]
Though it has some decent content, I'm not so sure about the license and their webservers are not allowing automated get requests..

**Comment by scafroglia93** [comment]
It has been used by nextdns, see if it can be useful to the cause; maximum use that already present within nextdns

**Comment by scafroglia93** [comment]
it's present inside nextdns so at the moment would be useless
