### ISSUE TITLE
new list -> regional addition

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#320]
thai -> https://github.com/kowith337/ThaiConsentHosts/blob/master/ThaiConsentHosts.txt

indo -> https://raw.githubusercontent.com/ABPindo/indonesianadblockrules/master/subscriptions/abpindo.txt

**Comment by notracking** [comment]
For the first one, blocking consent services will break tons of websites unfortunately. Some can be blocked but I'm afraid that this is not the goal of that list.

The second one does not add anything new (that is still alive..)
