### ISSUE TITLE
new list -> osint.bambenekconsulting.com (feedback) 

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#322]
https://osint.bambenekconsulting.com/feeds/

What to add some list?

https://osint.bambenekconsulting.com/feeds/dga-feed.txt

**Comment by notracking** [comment]
The expiry times on most of these dga lists are too short. Besides that, if implemented correctly the dga becomes so extremely huge, that it will be impossible to block these effectively via dns filters. These types of attacks should be approached differently.

`https://osint.bambenekconsulting.com/feeds/c2-dommasterlist-high.txt` is still included though, as stated in their info:
```
## Master Feed of known, active and non-sinkholed C&Cs domain
## names
```
