### ISSUE TITLE
(malware) marcapinyo.pk

### ISSUE THREAD

**Issue by 3xploiton3** [notracking/hosts-blocklists#327]
vcgfdngfsdfvcxsd.ru
dvcfxgcvbbasfsd.ru

 i catch something

![image](https://user-images.githubusercontent.com/19517680/80311368-84a96a80-8809-11ea-9664-744ee72f08a7.png)

**Comment by scafroglia93** [comment]
this domains are not exist

**Comment by 3xploiton3** [comment]
https://i.imgur.com/5Q8DVfZ.png

**Comment by scafroglia93** [comment]
check the whois of these domain

**Comment by 3xploiton3** [comment]
> check the whois of these domain

![image](https://user-images.githubusercontent.com/19517680/80313637-53836700-8816-11ea-82ee-0aa3567001a1.png)
![image](https://user-images.githubusercontent.com/19517680/80313646-6138ec80-8816-11ea-86aa-31fd66934ff6.png)


marcapinyo.pk

**Comment by scafroglia93** [comment]
https://www.virustotal.com/gui/domain/marcapinyo.pk/relations

**Comment by scafroglia93** [comment]
It's a malware but the other are KO domains

**Comment by scafroglia93** [comment]
open an issue for this two domain (malware)

**Comment by notracking** [comment]
Added `marcapinyo.pk`, thanks guys! (the .ru addresses are not registered, as stated they will be automatically removed from this list)
