### ISSUE TITLE
Whitelist paste.ee

### ISSUE THREAD

**Issue by emilstahl** [notracking/hosts-blocklists#329]
paste.ee is not a tracking domain, but a paste site, like pastebin.

**Comment by emilstahl** [comment]
You mentioned this back in 2018, guess some exclude is just misbehaving :)

> One problem that's already popping up, is (and not limited to) the false call rates this list will give on public copy/paste sites, like: https://paste.ee/.
> 
> Overall sample tests, show that simply parsing / extracting the domain names from this list will result in a high false positive rate. I would like to avoid that of course. 
> 
> Will be doing some more sampling to see if I can cherry pick some useful entries, while avoiding the false positives from this list.

_Originally posted by @notracking in https://github.com/notracking/hosts-blocklists/issues/95#issuecomment-425621678_

**Comment by emilstahl** [comment]
Hmm no, must be another list. `paste.ee` is not listed in https://urlhaus.abuse.ch/downloads/hostfile

**Comment by scafroglia93** [comment]
It's under -> checkpoint (my old list)

Can you open an issue inside ->
https://github.com/scafroglia93/blocklists

**Comment by notracking** [comment]
Whitelisted (could likely be added in the future..), and I've merged to your new lists @scafroglia93

**Comment by scafroglia93** [comment]
@emilstahl 
Open an issue in my list, i need to track it for the other people

**Comment by emilstahl** [comment]
@scafroglia93 Pull request created https://github.com/scafroglia93/blocklists/pull/3
