### ISSUE TITLE
settings-win.data.microsoft.com

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#332]
it's legit for whitelist ?
@emilstahl

**Comment by scafroglia93** [comment]
@beerisgood

**Comment by notracking** [comment]
What does this break?

**Comment by beerisgood** [comment]
@notracking it's breaking Microsoft Defender Advanced Threat Protection which also got more and more backported to enduser.

See https://docs.microsoft.com/en-us/windows/privacy/configure-windows-diagnostic-data-in-your-organization

So yes, it's legit for whitelist. Sadly some (even big) maintainer don't care about that but in the same way they don't use Windows at all which make no sense.

It makes generally no sense to block and windows domains on DNS level as everything can be configured in windows itself and some data are important or errors can't be fixed. People need to learn that.

**Comment by scafroglia93** [comment]
If we proceed, start escalating with some maintainers to go even

**Comment by notracking** [comment]
I've whitelisted this one and all it's siblings. 

Even though you can configure 'most' tracking / non-value added communications, problem remains that Windows simply resets most of those settings after certain updates in their favor. I still prefer to keep blocking any of these non-value added hosts, but only if they do not break useful functions in Windows.

Having said that, I'm not an active Windows user (only for work) so I might be missing some false positives, but luckily we have userfeedback supporting the curation.
