### ISSUE TITLE
undue blockage

### ISSUE THREAD

**Issue by clavelc** [notracking/hosts-blocklists#333]
Hi

French website [commentcamarche](https://www.commentcamarche.net/) is not accessible at all with the blocklist enabled (white page)

Not sure if this is the right place to report but couldn't find any better

have a good day

**Comment by scafroglia93** [comment]
It's not present inside this list; i think that will be a site issue

**Comment by notracking** [comment]
Site was broken because of a full domain filter on `ccmbg.com`, I've added it to the whitelist. Changes will be visible after the next auto update.

Thanks for the report!
