### ISSUE TITLE
labs.apnic.net

### ISSUE THREAD

**Issue by emlimap** [notracking/hosts-blocklists#334]
Access to this APNIC Labs website (https://labs.apnic.net/) is blocked by the following filter

```||labs.apnic.net^```

Not sure why this subdomain is blocked, APNIC, regional Internet address registry for the Asia-Pacific region. And this subdomain hosts their technical blog.

**Comment by notracking** [comment]
Thanks for the feedback! Item has been removed, changes will be visible after the next auto update.
