### ISSUE TITLE
Eventbot Trojan

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#336]
Source ->
https://www.cybereason.com/blog/eventbot-a-new-mobile-banking-trojan-is-born

IoC ->
themoil.site
ora.carlaarrabitoarchitetto.com
ora.studiolegalebasili.com
rxc.rxcoordinator.com
Ora.blindsidefantasy.com
Pub.welcometothepub.com
marta.martatovaglieri.it

**Comment by notracking** [comment]
These are already included.
