### ISSUE TITLE
new list -> stamparm malware

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#337]
This is the master of the malware

URL ->
https://raw.githubusercontent.com/stamparm/aux/master/maltrail-malware-domains.txt

**Comment by notracking** [comment]
I already went trough their source files and added everything I found usefull / safe some time ago. This list is massive and I'm not sure yet if I will replace the source files for this.

**Comment by beerisgood** [comment]
I use this list for a while now and doesn't found any false positive yet. Of course that is related to own web usage.

**Comment by notracking** [comment]
```
./test_list.sh https://raw.githubusercontent.com/stamparm/aux/master/maltrail-malware-domains.txt
[+] Downloading list: OK!
[+] Cleaning list.OK!
[+] Preparing cleaned support lists: OK!
[+] Total number of filters (hostnames): 82440
[+] Number of whitelist matches: 1
[+] Matching dead domains (not counting hostnames covered by domains): 2766
[+] Matching dead hostnames: 725
[+] Matching notracking blocklist (not counting hostnames covered by domains): 5352
[+] Preparing unique hostname samples (based on previous results): 73597 entries found!
[+] Checking notracking blacklist status: Unknown (not listed)
[+] Checking other blacklist status: Unknown (not listed)
[+] Resolving 7350(10%) random hosts @1.1.1.1: 2636 alive, 4714 not resolving

```

**Comment by beerisgood** [comment]
Can you share your list_list.sh ?

**Comment by notracking** [comment]
Maybe I will make it into a tool that could be publicly used, but for now it's way to much work for me to get this up and running on other peoples systems. I do not have the time/wish to support my personal tooling codebase with the public. There are database dependencies and tons of small tools that I use for various purposes that this depends on.

Also take into account that you would need to know every single implementation detail to make solid conclusions based on these results, for now they should be treated as an indicator only. I merely pasted the results here, so I will not forget (running took 1+ hour).

**Comment by notracking** [comment]
```
[+] Downloading list: OK!
[+] Cleaning list.OK!
[+] Preparing cleaned support lists: OK!
[+] Removing dupe filters matching existing notracking domain-filters: activ(all) dead(domains) dead(hostnames) OK!
[+] Total number of filters in original list: 82620
[+] Total number of dupes with notracking list (including dead lists): 15416
[+] Total number of unique filters: 67204
[+] Number of whitelist matches: 1
[+] Last 50 whitelist matches:
0.0.0.0 microsoftwindowsupdate.net
[+] Checking notracking blacklist status: Unknown (not listed)
[+] Checking public blacklist status: Unknown (not listed)
[+] Resolving 6720(10%) random hosts @1.1.1.1: 2449 alive, 4271 not resolving

```
