### ISSUE TITLE
Xiaomi Tracking (Mint Browser)

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#339]
Source ->
https://www.youtube.com/watch?v=62kxZunBQyI&feature=emb_title

Domain IoC ->
sa.api.intl.miui.com

We would need everyone's feedback to avoid malfunctions on the device

**Comment by notracking** [comment]
I cannot verify this one.

**Comment by scafroglia93** [comment]
steve has merged this inside list
