### ISSUE TITLE
yhosts new mantainer

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#343]
old list ->
https://raw.githubusercontent.com/vokins/yhosts/master/hosts.txt

new list -> 
https://raw.githubusercontent.com/VeleSila/yhosts/master/hosts.txt

**Comment by notracking** [comment]
Nice find, thanks! Url has been updated.

**Comment by beerisgood** [comment]
For me the top entries are looking strange:

> @direct/1os
#ios
255.255.255.255	broadcasthost
::1             localhost
#common
127.0.0.1 localhost
#android
::1             ip6-localhost
#miwifi
127.0.0.1 XiaoQiang

Shouldn't be exist in a filterlist

**Comment by notracking** [comment]
@beerisgood I agree, but al lot of blocklist define defaults voor local loopbacks. Does not really matter as these will be filtered out automatically.

**Comment by beerisgood** [comment]
> @beerisgood Does not really matter as these will be filtered out automatically.
But only by your script and not PiHole generally?

**Comment by notracking** [comment]
pihole will not exclude these as far as i know
