### ISSUE TITLE
new list covid malware (from nextdns)

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#345]
1-https://blocklist.cyberthreatcoalition.org/vetted/domain.txt

2- https://raw.githubusercontent.com/sophoslabs/covid-iocs/master/malicious_domains.txt (sophos)

3- https://rescure.fruxlabs.com/covid.txt

4- https://managedsentinel.com/downloads/covid19_domains.txt

5- https://kriskintel.com/ktip_corona.txt

**Comment by notracking** [comment]
Thanks! Added the kristintel.com one. Rest is to be tested.

**Comment by notracking** [comment]
1 Was already included
2 looking good, 878 unique hosts. Added!
3 14 unique hosts, Added!
4 too many (bad) false positives (zoom hosts, zoom background hosts provider coronavirus.app etc)
5 Was already included
