### ISSUE TITLE
new list -> malware (rescure fruxlabs)

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#346]
https://rescure.fruxlabs.com/maze.txt (maze ransomware)

https://rescure.fruxlabs.com/rescure_domain_blacklist.txt (malicious domain)

**Comment by notracking** [comment]
https://rescure.fruxlabs.com/maze.txt # Adds nothing new
https://rescure.fruxlabs.com/rescure_domain_blacklist.txt # 60% not resolving and most of the remaining items are already covered
