### ISSUE TITLE
Unblock wns.windows.com (?)

### ISSUE THREAD

**Issue by srett** [notracking/hosts-blocklists#349]
wns.windows.com is blocked with all of its subdomains. I couldn't find it directly in any of the lists from SOURCES.md, [WindowsSpyList](https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt) came closest as it lists a lot of subdomains of it, but some others are used for e.g. push notifications to Windows Store Apps, or winphone.wns.windows.com for the now discontinued Windows Mobile platform. Seeing that google domains with similar purpose are not blocked, you might want to consider removing it.

**Comment by notracking** [comment]
I'm adding this to the whitelist, just in case. But I'm also removing the source list for having too many false positives (20+ now), this list is moderated with incompatible criteria.

https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
