### ISSUE TITLE
Overblocking on web.de because i0.web.de is blocked

### ISSUE THREAD

**Issue by Th3M3** [notracking/hosts-blocklists#35]
I am using your `hostnames.txt` with the Pi-hole software and detected today, that the news-teaser-images on `web.de` are not shown on my mobile, because the domain `i0.web.de` gets blocked.

When I open up `web.de` on the PC, all images gets loaded, because they gets loaded from another domain.

So could you please remove **i0.web.de** from the list?
Thank you very much.

Marry Christmas 🎄🎅

**Comment by Th3M3** [comment]
_Appendum_:
Same issue on `gmx.net`. There **`i0.gmx.net`** gets blocked.
`nslookup` says that both domain names are aliases of `e5416.g.akamaiedge.net` and point to the same IP.

**Comment by notracking** [comment]
Thanks for your feedback! Checked and you are correct, white listed both. Entries will be removed with the next auto update.

Happy holidays!
