### ISSUE TITLE
[Wiki] Install-pi-hole: Link to cronjob corrupt

### ISSUE THREAD

**Issue by beerisgood** [notracking/hosts-blocklists#351]
Under https://github.com/notracking/hosts-blocklists/wiki/Install-pi-hole#how-to-install-using-pi-hole

> Please note that it is required to update the notracking lists automatically by using an external [daily cronjob](https://github.com/notracking/hosts-blocklists#automatic-update-and-whitelist-script) (instructions inside).

& at bottom:
> Add a [daily cronjob](https://github.com/notracking/hosts-blocklists#automatic-update-and-whitelist-script) to automatically update

Both links are only redirect to https://github.com/notracking/hosts-blocklists which doesn't include any instructions for cronjob

**Comment by notracking** [comment]
Thanks! Fixed.

**Comment by beerisgood** [comment]
Thanks!
