### ISSUE TITLE
(whitelist) bukalapak.go2cloud.org

### ISSUE THREAD

**Issue by 3xploiton3** [notracking/hosts-blocklists#352]
https://bukalapak.go2cloud.org/aff_c?offer_id=15&aff_id=13597&url=https%3A%2F%2Fwww.bukalapak.com%2Fp%2Fkomputer%2Flaptop%2F37j170b-jual-acer-predator-nitro-5-an515-54-729j-i7-9750h-8gb-512gb-gtx1650-4gb-w10%3Fho_offer_id%3D{offer_id}%26ho_trx_id%3D{transaction_id}%26affiliate_id%3D{affiliate_id}%26ho_clk_id%3D{aff_click_id}%26aff_sub1%3D{aff_sub}%26aff_sub2%3D{aff_sub2}%26aff_sub3%3D{aff_sub3}%26aff_sub4%3D{aff_sub4}%26aff_sub5%3D{aff_sub5}%26aff_src%3D{source}%26ref%3D{referer}%26utm_source%3Dhasoffers-{affiliate_id}%26utm_medium%3Daffiliate%26utm_campaign%3D{offer_id}

from
https://www.priceza.co.id/search?productdataname=9750h

**Comment by notracking** [comment]
This one was listed, because `go2cloud.org` hosts are very commonly used in phising schemes, blocking the entire domain is a bit overzealous. I've whitelisted it. Thanks again for the feedback!
