### ISSUE TITLE
plex.direct blocked by https://kriskintel.com/ktip_maze.txt

### ISSUE THREAD

**Issue by nlopez** [notracking/hosts-blocklists#353]
`plex.direct` is a domain [used by Plex to provide valid SSL certs for Plex installations out of the box](https://blog.filippo.io/how-plex-is-doing-https-for-all-its-users/).  I'm not sure how it got associated with the [Maze ransomware](https://labs.sentinelone.com/maze-ransomware-update-extorting-and-exposing-victims/), but this will be disruptive to some folks.

[Here](https://pastebin.com/raw/XbALjFRp) is a copy of the ktip_maze.txt list at the time of this report.

**Comment by notracking** [comment]
Thanks! Nice catch, item is whitelisted. Changes will be visible after the next auto update.
