### ISSUE TITLE
new list: AttackVectors-Domain-List

### ISSUE THREAD

**Issue by beerisgood** [notracking/hosts-blocklists#356]
This list is designed to block phishing sites and other fake local journals domains.
These domains are also blocked by third party security extensions, such as Bitdefender Trafficlight but for those that do not want to install these extensions, this list can be used instead.

Found on https://github.com/WaLLy3K/wally3k.github.io/issues/103

**Comment by notracking** [comment]
Nice one, added. Thanks for mentioning this here!
