### ISSUE TITLE
staticxx.facebook.com

### ISSUE THREAD

**Issue by p1r473** [notracking/hosts-blocklists#359]
I believe this domain is a static asset CDN for facebook, and it used to serve photos (not ads)

A CDN, or Content Delivery Network, is a network of different servers used to make sure that your web content is accessed from a server near you, to maintain speed.
Static content is content that does not change, such as uploaded images.
fbcdn.net is the CDN that Facebook owns and uses, and static means that you’re getting static data instead of dynamic data.

**Comment by notracking** [comment]
Thanks for reporting, I think you are correct! I've added this item to the whitelist.
Changes will be visible after the next auto update.
