### ISSUE TITLE
Would you do me a favor?

### ISSUE THREAD

**Issue by lupin92** [notracking/hosts-blocklists#361]
Add dot before domain name in the dnscrypt-proxy.blacklist.txt just like .doubleclick.com.
We may use that in Surge app to REJECT ads.

https://apps.apple.com/us/app/surge-4/id1442620678

- New Feature: DOMAIN-SET
We have added a new type of rule: DOMAIN-SET, which may contain millions of sub-rules. No UI configuration in this version. Please configure with the Text Mode
[Rule]
DOMAIN-SET,hostname.txt,REJECT
Each line in the file is a hostname or an IP address. If the hostname starts with a dot, all sub-domains will be matched.

**Comment by notracking** [comment]
Almost all blockers now use a single line like `evil.host.com` where this would block both `*.evil.host.com` and `evil.host.com`. This way of describing blocklists is also in line with the very widly adopted AdblockPlus standard.

According to the description you gave that tool requires 2 entries to get the same result. `.evil.host.com` and `evil.host.com`. I would say that their implementation is very unpractical and I'm not really enthusiastic for supporting this.

I would recommend asking them to follow the AdblockPlus standards for implementing blocklist support. Or at least just support domain lists and block all subdomains (/hostnames) by default, like most blockers do.
