### ISSUE TITLE
new lists -> italian various -> gioxx

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#366]
These lists are excellently maintained ->

https://github.com/gioxx/xfiles/blob/master/siteblock.txt
https://github.com/gioxx/xfiles/blob/master/filtri.txt

**Comment by notracking** [comment]
I am a bit busy in real life, due to home renovations. The content is looking good, but they are using a strange syntax, I will need to update the parsers for this (and check out in detail how these filters work).

We will get there!

**Comment by notracking** [comment]
Unfortunately both add nothing new.
