### ISSUE TITLE
blocked : ultimedia.com

### ISSUE THREAD

**Issue by clavelc** [notracking/hosts-blocklists#367]
ultimedia.com blocked domain prevents videos from loading in places such as [here](https://www.boursorama.com/videos/actualites/incendie-au-centre-de-paris-suite-a-une-fuite-de-gaz-99bdd592516c249e1ac910a269b736ef)
[Edit]
I have to add, I hated opening this issue because this is a crappy domain. But the main page says the lists are not supposed to break websites.. So I leave it for you to decide :)

**Comment by notracking** [comment]
Thanks for the feedback, really appreciated!

This one was on my personal list and it's not very widespread. I've removed it for now and added some remarks to this entry.
