### ISSUE TITLE
Whitelist Websites that should show Ads

### ISSUE THREAD

**Issue by menzbua** [notracking/hosts-blocklists#37]
Hi,

i have a question. Is it possible to whitelist domains where the blacklist would be ignored? In my case some websites are not callable when they detects that a Adblocker is installed (e.g. www.spiegel.de). Is there any possibility to whitelist www.spiegel.de that on this site the Ads are shown?

Thanks
Regards
Manuel

**Comment by notracking** [comment]
Hi Manuel,

The DNS server has no idea what the source of all the hostname lookups is, therefor it's not possible to whitelist websites in a way that you suggest. When you open spiegel.de, your browser will send a dns query to you server for spiegel.de and also all other links that are opened from the spiegel site. However these requests might also come from different sessions in your browser (other tabs) the DNS server will only see requests like:

<client> resolve spiegel.de
<client> resolve evilads.de
<client> resolve google.de

There are no markers telling him that the request for evilads.de is actually triggered by the source of spiegel.de. I am working on a side project however that will allow you to do whitelisting in the way that you describe, though that project is far from finished (but it is operational!), see nBlock.

Besides the technical side of all of this, personally I think that if websites do not obey the users choice to load or not load certain resources as the way the www is designed, they do not deserve any visitors. I'm quite sure that you can find way better sources for news then spiegel.de.

**Comment by menzbua** [comment]
Okay, i see that this is not a problem of the DNS Server itself. But i thought there would be a hint in dnsmasq to do that.

Thanks for the detailed answer.

Regards
Manuel
