### ISSUE TITLE
New phishing campaign on Facebook

### ISSUE THREAD

**Issue by Avamander** [notracking/hosts-blocklists#370]
I just noticed a new phishing campaign on Facebook that also sends one trough a row of redirects if allowed. Wouldn't hurt to add these to the blocklist.

Beginning: `https://arcade-knight .com/P3BhZ2U9bW9iaU5ldCZsYW5nPWUmaT04MjMwJmtleT01ODU0MTM\=`

Redirect path I got:
```
arcade-knight .com
mobilegames .mobi
www.mobilegames .mobi
lisboa.platiniumlink .com                    
platiniumlink .com
chads-bagel .com
bonus-point .life
pandoragirl1 .live
mobile-app-market-here5 .life
yltenim .com
```
ended with google.com

**Comment by notracking** [comment]
Vey nice finds sir, thanks for reporting! I've added these to the list, changes will be visible after the next auto update.
