### ISSUE TITLE
XLM phishing campaign

### ISSUE THREAD

**Issue by Avamander** [notracking/hosts-blocklists#371]
Some scammers are sending people XLM coins with the description that they should visit sites such as:

```
xlmdrop .org
xlmget .org
xlmgate .org
myxlm .org
```

(The last one is the only one active by now I think, still wouldn't hurt to block)

All the memos that direct people to the scam start with `Airdrop invite✅`, there are quite a few posts online about it if you wish to verify.

**Comment by notracking** [comment]
Thanks! I've added them to the custom list. As soon as these domains are dead (unregistered according to the whois data) the optimizer will remove them automatically, so I've added all of them.
