### ISSUE TITLE
Whitelist https://u1375320.ct.sendgrid.net

### ISSUE THREAD

**Issue by 3xploiton3** [notracking/hosts-blocklists#373]
https://u1375320.ct.sendgrid.net/asm/unsubscribe/?user_id=1375320&data=i-896D-8hNlCW6Rt8_ZJ3rUFwmthXsiWRkUCrpLGssxRIQRwowtE8Hxw2asGDM9EV7nPRF_BLWnnQag-yNN8r2q870DIU9Li179HvNXwYN4GeNimqXM8YLOUIz_GeuzX8NqPtYu9onoJGj5PNCGLHC91u3qWzFrXjEHKm_kms9roGDRnT1s3IcmmqnKlwSBhH1BmkZzZO-u7M7IsuJEKIU6tmbVWNy8gifVKCsNdNlmJdJ1YJ1TOMuHArnJjc0h-LnYFfmGtJ9SeZez03oBCbZDxinpvgm4Q1lpGKEUwzcixvpz2JspFF2Zf5LO-Gd3bhaS3QmkNHnSxzgOzetKQcNqTXcAhrKz4RceCn2kuQi4Ud1xPVEkcYs9EMkYgvFY-X5KSQzmWgvzfizW06KWfcjAh6W4of8nIh3bA8afHnuOKUPX_2ACaaWuMr1QGKTn6r_M30BWeGAt7_oIJu71YE6YtkkvHPkjFhDiXAXJ4MbsEDRVB0hapDc5ZVm9Ry7ISW_i8QfyGoaqnRjvGfTPuE3AlsjAlIlfMETvfja-g_e5uHjvY9VFTKZ4EwDnHab6sC3Lf_d_PAqiOYt7ZTo29wE3krLq4GWGd-p2dpFJSzBFFj9ZS5I-DPbvuOSKLMLgoSS1u5k-9GgaXt3qeF-_DBA== 

That link unsubscribe from stackshare

**Comment by Yunogamer** [comment]
*.ct.sendgrid.net should be, lots of email subscription stuff uses it.

**Comment by notracking** [comment]
Added it to the whitelist, thanks!
