### ISSUE TITLE
disconnect change

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#374]
Source ->
https://github.com/nextdns/metadata/issues/273

**Comment by notracking** [comment]
This new format will be very difficult to support, will have to take a good look at it.
Chances will be that the old list will simply be remove, since I estimate that almost all hosts will be covered by other lists anyway.

**Comment by notracking** [comment]
I will remove the unmaintained list and skip adding their new feeds.
Their new formatting is not suited for parsing here anymore.
