### ISSUE TITLE
Whitelist: nflxvideo.net

### ISSUE THREAD

**Issue by mad-it** [notracking/hosts-blocklists#378]
`nflxvideo.net` is present in `domains.txt`.

Blocking this domain blocks playback from the Netflix android app.

Odly enough its not present in `hostname.txt` 🤔

**Comment by mikalauskas** [comment]
Also blocks playback in ios, who added it?

**Comment by notracking** [comment]
Sorry for the delay, was offline for a couple of days. This item has already been removed from the source list and is currently not present anymore.

I will add it to the whitelist anyway, thanks for the report!
