### ISSUE TITLE
add: in.appcenter.ms

### ISSUE THREAD

**Issue by gingerlime** [notracking/hosts-blocklists#381]
spotted `in.appcenter.ms` used by Airmail (even in privacy mode) sending telemetry about my app usage including detailed actions/event, plus data like carrier country and name, phone model, build, os info, screensize, the app name, timezone, locale etc.

**Comment by beerisgood** [comment]
Why not only use another mail app then?

Domain is from Microsoft

**Comment by gingerlime** [comment]
I'm looking for an alternative mail app, but I'm pretty sure other apps might use this service, and as far as I can tell blocking this has no effect on the app. It's just tracking you unnecessarily (and without consent and against GDPR, at least for European customers like myself).

**Comment by beerisgood** [comment]
Try FairEmail

**Comment by gingerlime** [comment]
> Try FairEmail

I wish it was available for iPhone

**Comment by beerisgood** [comment]
> > Try FairEmail
> 
> I wish it was available for iPhone

For iPhone you can take a look at PEP

**Comment by gingerlime** [comment]
Thank you, but it doesn't look like what I'm after. I'm not looking for encrypted email. Just a regular email client, but hopefully that doesn't track my activity or leaks data.

In any case, I think blocking in.appcenter.ms would be beneficial for other apps that use it for tracking their users.

**Comment by beerisgood** [comment]
In PEP the mail encryption isn't a must. You can disable it ;)

They don't leak or track your data. you can read this German article about: https://mobilsicher.de/ratgeber/pep-sichere-mail-app-fuer-ios

**Comment by gingerlime** [comment]
Thank you, I might consider it, but it doesn't look like what I'm after (plus, app store reviews aren't so great either).

**Comment by notracking** [comment]
Thanks reporting and thanks for the good advise @beerisgood ! I've added this host to the custom list anyways.
