### ISSUE TITLE
Broken Sony TV functionality

### ISSUE THREAD

**Issue by S-a-l-a-d** [notracking/hosts-blocklists#384]
I can't use any app with my TV and I see these hostnames are blocked in my log:
```
reg.biv.sony.tv
service.biv.sony.tv
```
And I found this list that can be helpful: https://gist.github.com/casenjo/586c7b76dd6f7512125fb4e2fb853aae

**Comment by notracking** [comment]
Thanks! I've added those hosts to the whitelist, changes will be visible after the next auto update.

That list is a little outdated though (hasn't been updated in 2 years).

**Comment by S-a-l-a-d** [comment]
I've found one more entry:
```
update.biv.sony.tv
```
which is used for firmware update.

**Comment by notracking** [comment]
also added that last one, thanks!

**Comment by S-a-l-a-d** [comment]
Today I encountered an issue where the Internet content (the list of apps) could not be updated because these hostnames are blocked:
```
ssm1.internet.sony.tv
ssm2.internet.sony.tv
ssm3.internet.sony.tv
```
Can you tell me where these are sourced from so I can report there? `ssm2` and `ssm3` are also present in oisd blocklist.

**Comment by S-a-l-a-d** [comment]
Hi @notracking. Please also whitelist these domains:
```
ssm1.internet.sony.tv
ssm2.internet.sony.tv
ssm3.internet.sony.tv
```
They are used for app list in TVs. `ssm2` will be called if the first one fails. The same for `ssm3`.

**Comment by notracking** [comment]
Thanks! These have been added as well..!
