### ISSUE TITLE
Toutiao blocked

### ISSUE THREAD

**Issue by rockagen** [notracking/hosts-blocklists#386]
Toutiao app use  https://toutiao-frontier.snssdk.com/ws/v2 api now,  According to current rules, all snssdk.com subdomain is blocked, suggest remove this.

**Comment by llacb47** [comment]
Really, as api? In tiktok all `snssdk.com` domains are tracking and not essential for the app to function.

**Comment by rockagen** [comment]
> Really, as api? In tiktok all `snssdk.com` domains are tracking and not essential for the app to function.

but, toutiao go die if block this :joy:

**Comment by notracking** [comment]
I think all (or at least most) of the tracking domains are listed as hostname as well.

I will whitelist the full domain, all listed hostnames below will be added in exchange.

```
adguard_mobile.txt:0.0.0.0 snssdk.com
adguardteam_tracking_servers.txt:0.0.0.0 mcs.snssdk.com
domains.adblock.txt:||snssdk.com^
hostnames.adblock.txt:||tobapplog.ctobsnssdk.com^
hostnames.adblock.txt:||toblog.ctobsnssdk.com^
jdlingyu_adwars.txt:0.0.0.0 is.snssdk.com
jdlingyu_adwars.txt:0.0.0.0 bds.snssdk.com
jdlingyu_adwars.txt:0.0.0.0 mon.snssdk.com
jdlingyu_adwars.txt:0.0.0.0 extlog.snssdk.com
jdlingyu_adwars.txt:0.0.0.0 toblog.ctobsnssdk.com
jdlingyu_adwars.txt:0.0.0.0 tobapplog.ctobsnssdk.com
neohosts_common.txt:0.0.0.0 temai.snssdk.com
neohosts_common.txt:0.0.0.0 analytics.snssdk.com
neohosts_common.txt:0.0.0.0 temai.snssdk.com
neohosts_common.txt:0.0.0.0 extlog.snssdk.com
yhosts.txt:0.0.0.0 analytics.snssdk.com
yhosts.txt:0.0.0.0 temai.snssdk.com
```
