### ISSUE TITLE
False positive: danviet.vn

### ISSUE THREAD

**Issue by S-a-l-a-d** [notracking/hosts-blocklists#387]
It's a news website.

**Comment by scafroglia93** [comment]
https://www.welivesecurity.com/2018/11/20/oceanlotus-new-watering-hole-attack-southeastdanviet.vn-asia/

danviet.vn

it's safe now ?

**Comment by notracking** [comment]
@scafroglia93 it seems to be legit and didn't see anything special besides the tons of fingerprinting going on etc (which seems to be the norm for news websites these days...).

**Comment by scafroglia93** [comment]
Fixed

**Comment by notracking** [comment]
Thanks @scafroglia93 !
