### ISSUE TITLE
Rename blacklist -> blocklist

### ISSUE THREAD

**Issue by fulldecent** [notracking/hosts-blocklists#389]
In text and also filenames

**Comment by notracking** [comment]
I've explicitly choose "blacklist" as the name because it is consistent with dnscrypt-proxy's configuration option (/help).
Changing this will also impact all users who have already added this list. I will avoid breaking other peoples configurations, unless absolutely necessary.

**Comment by fulldecent** [comment]
Got it. Reported upstream: https://github.com/DNSCrypt/dnscrypt-proxy/issues/1402

**Comment by fulldecent** [comment]
Will release in next version upstream // https://github.com/DNSCrypt/dnscrypt-proxy/commit/b089d49d25bf0d35a1a4a7a7637e63e0a3f93501
