### ISSUE TITLE
malicious domain

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#396]
taken from infected pc

joodfbnm29.eu
joodfbnm27.eu
nbrwer27.eu
joodfbnm26.eu
nbrwer26.eu
joodfbnm25.eu
nbrwer25.eu
joodfbnm24.eu
nbrwer24.eu
joodfbnm23.eu
nbrwer23.eu
joodfbnm22.eu
nbrwer22.eu
joodfbnm21.eu
nbrwer21.eu
joodfbnm20.eu
nbrwer20.eu
joodfbnm19.eu
nbrwer19.eu
joodfbnm18.eu
nbrwer18.eu
joodfbnm17.eu
nbrwer17.eu
joodfbnm16.eu
nbrwer16.eu
joodfbnm15.eu
nbrwer15.eu
joodfbnm14.eu
nbrwer14.eu
joodfbnm13.eu
nbrwer13.eu
joodfbnm12.eu
nbrwer12.eu
joodfbnm11.eu
nbrwer11.eu
joodfbnm10.eu
nbrwer10.eu
joodfbnm9.eu
nbrwer9.eu
joodfbnm8.eu
nbrwer8.eu
joodfbnm7.eu
nbrwer7.eu
joodfbnm6.eu
joodfbnm4.eu
nbrwer4.eu
joodfbnm3.eu
nbrwer3.eu
joodfbnm2.eu
nbrwer2.eu
joodfbnm1.eu
nbrwer1.eu
syqydecuupkgikseyxi.eu
pfpvstgcjnxrji.eu
tgujfowebwfglrilnu.eu
sfkkxudmge.eu
xeixtnolvuuwmwy.eu
veidlqdwstqpgrmbs.eu
knkykjvd.eu
cdmgqqdqjwlo.eu
vmfmkxlxyr.eu
bjvbcpwryhtjotxcpur.eu
grxugvrwynyeyh.eu
ilwxedddvolepx.eu
lddskuvswkildob.eu
uvegqgicmwcoywd.eu
emippbnbphyloo.eu
yvxjsixn.eu
shsvveir.eu
vnsylgycmultlwcjnie.eu
nbrwer.eu
joodfbnm.eu

**Comment by scafroglia93** [comment]
veidlqdwstqpgrmbs.eu

**Comment by scafroglia93** [comment]
emippbnbphyloao.eu

**Comment by 3xploiton3** [comment]
analytics.s.id

**Comment by scafroglia93** [comment]
> analytics.s.id

What is this ?

**Comment by notracking** [comment]
Added all, thanks!

@scafroglia93 I think that would be a analytics tracker used on shortened s.id url's.
