### ISSUE TITLE
UrlHaus by Abuse.ch

### ISSUE THREAD

**Issue by zmni** [notracking/hosts-blocklists#398]
Source: https://gitlab.com/curben/urlhaus-filter based on the Database dump (CSV) of Abuse.ch [URLhaus](https://urlhaus.abuse.ch/).

Just a reference, uBlock Origin replace it's malware domains filter lists with this list (https://github.com/uBlockOrigin/uBlock-issues/issues/984, https://github.com/uBlockOrigin/uBlock-issues/issues/1116 and https://github.com/gorhill/uBlock/compare/1.28.0...1.28.2).

Please consider using this list as a source rather than the old one. Or at least as an addition to the existing lists.

Thank you.

**Comment by notracking** [comment]
I've rejected their list in the past, but they now (or I completely missed that) seem to have a curated dns versions as well.
The [hosts based lite](https://gitlab.com/curben/urlhaus-filter/raw/master/urlhaus-filter-hosts-online.txt) version seems to be usable, added it.

Thanks for the suggestion!
