### ISSUE TITLE
request block yuanzhanapp.com

### ISSUE THREAD

**Issue by 3xploiton3** [notracking/hosts-blocklists#399]
catch some suspicious domain

yuanzhanapp.com

https://www.robtex.com/dns-lookup/yuanzhanapp.com

Hangzhou Alibaba Advertising Co.,Ltd.

from emulator ldplayer
https://www.ldplayer.net/

**Comment by notracking** [comment]
I'm thinking about stopping to add individual hosts to the custom list, as that list is more of a personal list filled with items that I can easily check. I'm afraid that blocking this domain will prevent stuff from working, considering `face.yuanzhanapp.com` seems to have an api used for non ad purposes (as said, I cannot really validate).

It might be a good idea to have a look at our sources list to find a list that curates these types of hosts and try to submit it there under their curation.
