### ISSUE TITLE
Youtube is blocked

### ISSUE THREAD

**Issue by pjg** [notracking/hosts-blocklists#4]
```
☺ ping www.youtube.com
PING youtube-ui.l.google.com (216.58.214.238): 56 data bytes
64 bytes from 216.58.214.238: icmp_seq=0 ttl=54 time=25.955 ms
64 bytes from 216.58.214.238: icmp_seq=1 ttl=54 time=24.695 ms
```

And `youtube-ui.l.google.com` is added to the list of blocked hosts.

**Comment by notracking** [comment]
You mean that youtube-ui.l.google.com prevents you from watching videos? Here, youtube still seems to work perfectly with this block in place.

**Comment by pjg** [comment]
Yup, exactly that. On my end, `www.youtube.com` is resolved as `youtube-ui.l.google.com`

**Comment by notracking** [comment]
Ok, I will fix it as soon as I'm home, catching a 14 hours flight now. Thanks for reporting!

**Comment by notracking** [comment]
And fixed! thanks again for the report.

**Comment by pjg** [comment]
Thx!

**Comment by sergeevabc** [comment]
Blocking ```i1.ytimg.com``` breaks loading of videos’ thumbnails.

**Comment by notracking** [comment]
Fixed with the next auto update!
