### ISSUE TITLE
HOSTS file to block all known NSA / GCHQ / C.I.A. / F.B.I. spying servers

### ISSUE THREAD

**Issue by githubcom13** [notracking/hosts-blocklists#40]
Hello,

Would be it possible to add this list? https://raw.githubusercontent.com/CHEF-KOCH/NSABlocklist/master/HOSTS 

( source : https://github.com/CHEF-KOCH/NSABlocklist )

And a list concerning the telemetry of the Microsoft products (Windows, Service(Office), Outlook, Drive) and Apple?

**Comment by notracking** [comment]
Hi there,

Thanks you for your submission, I am familiar with this (and these type of) NSA blocklists. These usually just block anything government related, resulting in a lot of false calls. And believe me a NSA backdoor on your PC will never, ever contact www.nsa.gov ;)

There are already properly curated Windows telementry block lists included. There are only a few decent ones that do not break essentials like live updates. 

I know it's cheesy, but when having Microsoft products installed it's almost inevitable that you will be tracked to some extend as this is part of their core (new) business. Also a lot of the known hosts are hardcoded into the newer Windows kernels making it impossible to do local dns blocking for them (that will only work if you run your dns on a non-windows machine). My advise: use Linux!
