### ISSUE TITLE
some addresses for the custom list

### ISSUE THREAD

**Issue by giovannikraushaar** [notracking/hosts-blocklists#401]
address=/6navi.ch/#
address=/vstera.tech/#
address=/apprefaculty.pro/#
address=/pornn21.com/#
address=/mein-iw-bonus.com/#
address=/greatdexchange.com/#
address=/yoomanies.com/#

**Comment by notracking** [comment]
Thanks for the feedback!

I'm thinking about stopping to add individual hosts to the custom list, since it's hard for me to validate when I'm not familiar with the sources. I've tried to track these items as good as I could and added them for now.
