### ISSUE TITLE
(unblock) adf.ly

### ISSUE THREAD

**Issue by 3xploiton3** [notracking/hosts-blocklists#402]
it just short url

http://adf.ly/1Z6FJM

from
http://ampalusoftware.blogspot.com/2016/04/paragon-extfs-for-windows-21440-full.html

**Comment by notracking** [comment]
It's always very painful to have to whitelist hosts like these.., but I've added it anyway.
Linkshortners should be dealt with on another level, dns blocking is not suited for these..

Thanks for your submission!
