### ISSUE TITLE
False positive: wns.windows.com

### ISSUE THREAD

**Issue by S-a-l-a-d** [notracking/hosts-blocklists#403]
> The following endpoint is used for the Windows Push Notification Services (WNS). WNS enables third-party developers to send toast, tile, badge, and raw updates from their own cloud service. This provides a mechanism to deliver new updates to your users in a power-efficient and dependable way. If you turn off traffic for this endpoint, push notifications will no longer work, including MDM device management, mail synchronization, settings synchronization.

https://docs.microsoft.com/en-us/windows/privacy/manage-windows-2004-endpoints

**Comment by notracking** [comment]
Excellent find sir, thank you! Added to the whitelist, changes will be visible after the next auto update.
