### ISSUE TITLE
Adobe mobile ad domains

### ISSUE THREAD

**Issue by Avamander** [notracking/hosts-blocklists#404]
It would be nice if Adobe's mobile ad/analytic domains were blocked. Lists like Peter Lowe’s Ad and tracking server list block the entire `omniture.com` domain, but I personally saw `hal.testandtarget.omniture.com` and `c00.adobe.com`.

**Comment by notracking** [comment]
Thanks!, I've added `c00.adobe.com` to the blocklist. A full domain block on `omniture.com` already exists.
