### ISSUE TITLE
healthyhome.asia

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#408]
![photo_2020-08-14_16-30-38](https://user-images.githubusercontent.com/8227101/90260220-7ed4a500-de4b-11ea-8a15-ea017bfb5bda.jpg)

**Comment by scafroglia93** [comment]
https://www.virustotal.com/gui/url/d79647d52113fc23e0b66e6c03f8d8739f1d51ccaee05155744bf974cdd53e42/detection

**Comment by notracking** [comment]
Thanks! Added to the custom list, changes will be visible after the next auto update.
