### ISSUE TITLE
Filter lists

### ISSUE THREAD

**Issue by githubcom13** [notracking/hosts-blocklists#41]
Hello,
Here are filter lists : 
https://github.com/CHEF-KOCH/FilterLists/blob/master/data/List.csv
Best regard

**Comment by notracking** [comment]
Thanks! I will scan them as soon as I have a bit more time, though I think I've already checked most of them in the past.

**Comment by notracking** [comment]
Added 4 (ablock based) lists and a heap of entries cherry picked from lists that have too many false calls to include into the automatic update.

Changes will be visible with the next auto-update. Thanks for pointing this out!

**Comment by githubcom13** [comment]
Hello, thank you for your work of great quality and your sharing. best regard
