### ISSUE TITLE
new lists -> adguard dns filter

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#415]
URL ->
https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt

**Comment by notracking** [comment]
This is a combined list, see [here](https://raw.githubusercontent.com/AdguardTeam/AdGuardSDNSFilter/master/configuration.json), giving a lot of false positives.. All of the useful easylist lists have already been included, with exception (missed that somehow) of [this](https://raw.githubusercontent.com/AdguardTeam/AdGuardSDNSFilter/master/Filters/rules.txt) list. Added that one instead :) Thanks!
