### ISSUE TITLE
Joyn.de

### ISSUE THREAD

**Issue by mrxoom1274** [notracking/hosts-blocklists#417]
I couldn't use joyn.de after activating notracking on NextDNS. Please allow

**Comment by lyrad87** [comment]
Works for me and I also use this blocklist and NextDNS. What exactly is not working? Maybe it would help if you mention the device and what exactly the log shows you when you access the service.

**Comment by mrxoom1274** [comment]
I use appleTV,iPhone and iPad  native apps from Joyn. NextDNS setup on a fritzbox. If I activate notracking and start the app and want to begin watching a Episode nothing happens. I have a black screen and playback didn't start. If I disconnect for example my iPhone from NextDNS everything works. Then I remove all block lists in NextDNS an add one for one an Test it. If I add NoTracking Joyn didn't start playback in the apps. After remove NoTracking it works.

**Comment by lyrad87** [comment]
I have the exact same setup as you but it works for me. I'd guess it's related to their app. I've watched a few different shows on their website without any issues. What does the log say? Does it show a specific domain?

**Comment by mrxoom1274** [comment]
Yes. On the website it works for me also. But not in the app.

**Comment by mrxoom1274** [comment]
![Uploading 91496374...]

**Comment by mrxoom1274** [comment]
![image](https://user-images.githubusercontent.com/70346648/91496374-4d80be00-e8bc-11ea-9fd1-7e91b3161dcb.jpeg)

Some pictures from my log by NextDNS

**Comment by lyrad87** [comment]
What does the log say? Does it show a specific domain?

**Comment by mrxoom1274** [comment]
Hello. Ivan stopped using NectDNS. Thank you.
