### ISSUE TITLE
whitelist semawur.com

### ISSUE THREAD

**Issue by 3xploiton3** [notracking/hosts-blocklists#419]
https://semawur.com/xdhE

source:
https://www.youtube.com/watch?v=lTuFsbZfRNo

**Comment by 3xploiton3** [comment]
![image](https://user-images.githubusercontent.com/19517680/91786783-9032f500-ec32-11ea-921e-816e9e74a41c.png)

**Comment by notracking** [comment]
Thanks! Added to the whitelist, changes will be visible after the next auto update.
