### ISSUE TITLE
More to whitelist

### ISSUE THREAD

**Issue by Crazy-Hopper** [notracking/hosts-blocklists#42]
Hi,
samsungrm.net domain is needed for remote management of TV-sets by Samsung support.

**Comment by notracking** [comment]
Will this be leading to any practical issues? Because this host is used as a backdoor rootshell on your local network. I would higly recommend only manually opening this in case of an emergency.

**Comment by Crazy-Hopper** [comment]
Well, if TV set's inexplicable failure (the TV set doesn't show any valuable debug info to understand the failure) to initialize the connection to Samsung support upon users' requests is a practical issue, then yes. :-) On the other hand, you're right, letting anyone inside the LAN is a risk. But I'm not sure we are in position to break functionality or UX, hence this whitelist request. But I'm OK with whatever you decide. ;-)

**Comment by notracking** [comment]
I've upgraded one of the Samsung entries in the list to a domain based one: ads.samsungadhub.com -> samsungadhub.com should give a bit more coverage on that part (unrelated to this ticket).

Although people should not use these kinda of backdoor machines, no real functionality will be broken by this domain block. I think it's not worth having a known backdoor open for an edge case where you device is broken anyway (you should return it to the shop in the end any way). I will leave this filter in place. Thanks for your feedback!
