### ISSUE TITLE
ris.api.iris.microsoft.com

### ISSUE THREAD

**Issue by S-a-l-a-d** [notracking/hosts-blocklists#420]
This seems like a false positive.
> The following endpoints are used to retrieve Windows Spotlight metadata that describes content, such as references to image locations, as well as suggested apps, Microsoft account notifications, and Windows tips. If you turn off traffic for these endpoints, Windows Spotlight will still try to deliver new lock screen images and updated content but it will fail; suggested apps, Microsoft account notifications, and Windows tips will not be downloaded. For more information, see Windows Spotlight.

https://docs.microsoft.com/en-us/windows/privacy/manage-windows-1809-endpoints

**Comment by notracking** [comment]
Thanks! Added to the whitelist, changes will be visible after the next auto update.

**Comment by mtxadmin** [comment]
URL ris.api.iris.microsoft.com seems to be related to Chrome telemetry:
https://brave.com/popular-browsers-first-run/
Very suspicious. As for me, I prefer to block such strange addresses.
