### ISSUE TITLE
(whitelist) go.onelink.me

### ISSUE THREAD

**Issue by 3xploiton3** [notracking/hosts-blocklists#421]
![image](https://user-images.githubusercontent.com/19517680/92243673-09a93c80-eeec-11ea-85b7-220cc7f130fe.png)
![image](https://user-images.githubusercontent.com/19517680/92243715-188fef00-eeec-11ea-9df2-4fe204e8f76d.png)

cannot download tiktok

**Comment by notracking** [comment]
Thanks! Added to the whitelist, changes will be visible after the next auto update.
