### ISSUE TITLE
driftt.com and drift.com rules breaks live chat

### ISSUE THREAD

**Issue by crssi** [notracking/hosts-blocklists#429]
Rule `||driftt.com^` and `||drift.com^` breaks live chat provided by same.

Sample domain where chat breaks is `https://jumpcloud.com/` <- unfortunate the login is required, but there is also a trial version.

If you need, I can make a screen recording for you.

Cheers

**Comment by notracking** [comment]
Thanks! Added to the whitelist, changes will be visible after the next auto update.

**Comment by crssi** [comment]
I don't know how this is possible but, `||drift.com^` is still persistent in the https://raw.githubusercontent.com/notracking/hosts-blocklists/master/adblock/adblock.txt

Thank you mate
