### ISSUE TITLE
False positive: schibsted.io

### ISSUE THREAD

**Issue by alanfranz** [notracking/hosts-blocklists#43]
Although the company seems somehow involved with advertising, it provides a number of services as well; the whole domains is blocked, but I'm quite sure that at least the

```
widget.messaging.schibsted.io
```

domain provides legit functionality.

**Comment by HellboyPI** [comment]
There is a way in dnsmasq to whitelist only "widget.messaging.schibsted.io" and blacklist everything else from "schibsted.io".

https://discourse.pi-hole.net/t/how-do-i-add-wildcard-sites-to-the-blacklist/337

Find the part "**What about exceptions?**" and adapt it to your configuration.

**Comment by notracking** [comment]
Hi,

Can you give me an example that uses this widget address? This company is one of the largest ad providers in Sweden, based on what I could find with a quick search.

@HellboyPI the whitelisting feature is nice, though I cannot tell on forehand what the upstream dns server addresses are from our users. Pointing all exceptions toward the google dns is also not the best solution. 

We might need a better set of filters for this company, but then I first have to be able to see what the current impact is. A lot of these 'usefull' widget are merely there to have an excuse to inject their tracking scripts in more websites (like those weather, this is your IP widgits etc..)

**Comment by alanfranz** [comment]
Hello,
the messaging widget is used by www.subito.it (you need registering, maybe
bugmenot has some logins), which is the largest italian classified ads
provider (think something like craigslist). If the schibsted domain is
blocked, the whole messaging doesn't work, making the site quite hard to
use (it's possible to use the email, but you miss a direct reference to the
ad you answered to).

**Comment by notracking** [comment]
I've whitelisted schibsted.io. the remaining domain filters for this company are left in place:

domains.txt:address=/schibsted.media/0.0.0.0
domains.txt:address=/schibsted.se/0.0.0.0

Changes will be visible with the next auto update, thanks again!
