### ISSUE TITLE
drift.com rules breaks live chat

### ISSUE THREAD

**Issue by crssi** [notracking/hosts-blocklists#430]
Rule `||drift.com^` breaks live support chat provided by same.

Sample domain where support chat breaks is https://jumpcloud.com/ <- unfortunate the login is required, but there is also a trial version.

See also https://github.com/notracking/hosts-blocklists/issues/429#issuecomment-702515257

Thank you mate and cheers

**Comment by notracking** [comment]
And now it's fixed, for sure! Must have forgot to commit the whitelist changes.

Thanks for the feedback!

**Comment by crssi** [comment]
Thank you 🍺 ❤️
