### ISSUE TITLE
Please consider adding REScure Threat Intel Feed

### ISSUE THREAD

**Issue by eshanaswar** [notracking/hosts-blocklists#431]
We have started free malware threat feed (REScure) which is accessible at :

Homepage : https://rescure.me

Feedpath

- https://rescure.me/rescure_blacklist.txt
- https://rescure.me/rescure_domain_blacklist.txt 

The feed is curated form an inhouse threat intelligence solution and is updated at every 24 hours. A blogpost detailing about this is mentioned here :

https://www.theprohack.com/2018/09/rescure-cyber-threat-intelligence-feed.html

Currently we are also publishing IoCs such as malware hashes, domains et al.

Thanks !

**Comment by scafroglia93** [comment]
https://rescure.me/rescure_blacklist.txt ->
useless with DNS

**Comment by notracking** [comment]
How do you plan to deal with these types of blocks?
```
lnkd.in
vk.com
```

And as mentioned by @scafroglia93 ip lists are not suited for dns blocking purposes.

**Comment by eshanaswar** [comment]
We are not providing Adblock list. We are providing malicious domains only.

**Comment by notracking** [comment]
List is added, thanks!

**Comment by notracking** [comment]
And reverted: list removed. Blocked www.google.com even after the previous notes..
