### ISSUE TITLE
more database filter

### ISSUE THREAD

**Issue by 3xploiton3** [notracking/hosts-blocklists#432]
https://www.github.developerdan.com/hosts

`https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt`

Lightswitch05 - Ads & Tracking
A programmatically expanded list of hosts used for advertisements and tracking.

**Comment by scafroglia93** [comment]
too much FP

**Comment by notracking** [comment]
Exactly, too many false positives... will not be included.
