### ISSUE TITLE
Request allow

### ISSUE THREAD

**Issue by ads455** [notracking/hosts-blocklists#434]
geolocation.onetrust.com
error.fc2.com
cafe24.com
ai.yimg.jp
4ix.com
cdn.gotraffic.net
pagead2.googlesyndication.com
<span>www.googletagmanager.com</span>
****
**geolocation.onetrust.com**
`MVPS HOSTS`

Breaks video
https://github.com/EnergizedProtection/block/issues/446
[cbsnews](https://www.cbsnews.com/video/tracking-hurricane-delta-as-it-churns-in-the-gulf-coast/) 
[zdnet](https://www.zdnet.com/video/ibm-open-sources-project-for-space-orbital-predictions/) 
****
**error.fc2.com**
`MVPS HOSTS`

Error page that moves to the top page after 30 seconds
http://error.fc2.com/blog/
http://error.fc2.com/other/404.html
****
**cafe24.com**
`mirror1.malwaredomains.com`

Some sites break
http://jolse.com/
https://www.lotuff.co.kr/
https://www.cafe24corp.com/
****
**ai.yimg.jp**
`yhosts`

Used for some yahoo icons and logos
[block icon 1](https://ai.yimg.jp/c/logo/f/2.0/chiebukuro_r_34_2x.png) 
[block icon 2](https://ai.yimg.jp/images/mtop/icon/newTab/tp.png) 
[block icon 3](https://ai.yimg.jp/c/icon/s/bsc/2.0/y120.png) 
****
**4ix.com**
`mitchellkrogz`

http://4ix.com/archives/160621230001/

> About homepage false detection by security software The problem of false detection of bb4ix website vulnerabilities in certain security software (Avast!) Has been resolved by a software vendor's response.

****
**cdn.gotraffic.net**
`Peter Lowe`

Breaks video
https://www.bloomberg.com/video
****
**pagead2.googlesyndication.com**
`Blocked on many lists`

Used for anti-ad blocking

[link 1](https://280blocker.net/data/weblock20170708.html) 

> pagead2.googlesyndication.com (anti-adblock target)

[link 2](https://www.reddit.com/r/nextdns/comments/g2dzzm/nextdns_and_adblock_warnings/) 

Anti-ad blocking site
[anti adblock 1](https://battlecats-db.com/) 
[anti adblock 2](https://warui.intaa.net/contents/antiadblock/) 
[anti adblock 3](https://freefielder.jp/acb/installation.html) 
****
**<span>www.googletagmanager.com</span>**
`hostsVN`

Some sites may break
[link 1](https://github.com/disconnectme/disconnect-tracking-protection/issues/31) 
[link 2](https://nilead.com/article/google-tag-manager-can-harm-your-business) 

> your site's important functionalities will NOT work as well.

> Since GTM is such a convenient way to inject code, people tend to inject all kinds of Javascript including valid and essential script

**Comment by notracking** [comment]
Thanks, some excellent finds! I've whitelisted all, except for:
pagead2.googlesyndication.com
www.googletagmanager.com

I would recommend adding those to your local whitelist if they break a specific site. These blocks will not harm most of the other sites who use them, while still getting rid of garbage.
