### ISSUE TITLE
||na01.safelinks.protection.outlook.com^ breaks link to another page

### ISSUE THREAD

**Issue by crssi** [notracking/hosts-blocklists#436]
There is a breakage opening a link due to `||na01.safelinks.protection.outlook.com^` rule.

Steps to reproduce:
Open https://support.microsoft.com/en-us/office/send-messages-to-skype-for-business-users-from-teams-990cd8a2-7f9d-4d15-b92e-059b1018fd15
Click on a first link in an article saying
https://docs.microsoft.com/en-us/microsoftteams/coexistence-chat-calls-presence
which leads to same over
https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fmicrosoftteams%2Fcoexistence-chat-calls-presence&data=02%7C01%7Ccbland%40microsoft.com%7Cdb7a3b42252341aa2bcd08d675c30bf7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636825877923191977&sdata=yZH6gEF7S4fVsK4P5%2BjeB%2Bk%2Fa2loy834l9d%2FmwCK0nE%3D&reserved=0

Cheers

**Comment by notracking** [comment]
Thanks! Added to the whitelist, changes will be visible after the next auto update.
