### ISSUE TITLE
Dodi Repacks can't be opened due to DDOS Guard blocking

### ISSUE THREAD

**Issue by jenabaivab** [notracking/hosts-blocklists#438]
Cannot open dodi-repacks.site as the DDOS check can't be completed.

![Screenshot_2020-10-16-15-08-28-62](https://user-images.githubusercontent.com/60446763/96242773-7ae70f80-0fc1-11eb-8bce-2f7e8e6568ed.jpg)

Currently stuck in this page

![IMG_20201016_150955](https://user-images.githubusercontent.com/60446763/96242919-ad910800-0fc1-11eb-8570-cafc9f183611.jpg)

NoTracking is the one blocking the check request.
Could this please be whitelisted?

**Comment by notracking** [comment]
Thanks! Added to the whitelist, changes will be visible after the next auto update.
