### ISSUE TITLE
dansguardian.org

### ISSUE THREAD

**Issue by yodog** [notracking/hosts-blocklists#44]
Hello.

> grep -r dansguardian scripts/rag-adblocker/tld/
> scripts/rag-adblocker/tld/notracking-domains.tld:14792:address=/dansguardian.org/192.168.25.254

Should dansguardian.org really be on the blacklist?

> DansGuardian [...] is content-control software designed to control which websites users can access. It also includes virus filtering and usage monitoring features.

**Comment by notracking** [comment]
Hi,

Thanks for the report! No this does not belong on our list, changes will be visible after the next auto update.
