### ISSUE TITLE
documentforce.com blocked by Notrack Tracker list

### ISSUE THREAD

**Issue by Laurisade** [notracking/hosts-blocklists#440]
Hello!

Seems that this domain
documentforce.com
is linked with salesforce.com account login.

I just got FP with Notrack, while trying to log into the Salesforce.
![image](https://user-images.githubusercontent.com/6094860/96441373-166ebf00-1212-11eb-8db2-f507a2af0d37.png)

Could you please check this? I doubt it is tracking URL.

**Comment by notracking** [comment]
We do not block that host, I think you are looking for a different blocklist maintainer: https://quidsup.net/notrack/
