### ISSUE TITLE
Whitelist: filesusr.com

### ISSUE THREAD

**Issue by Papafox** [notracking/hosts-blocklists#442]
Wix uses <domain-name>.filesusr.com for all the embedded frames on it's webpages. So if some sets up a web site for 'example.com', Wix will automatically generate frames which reference www-example-com.filesusr.com inside each of the webpages.

Domains.txt contains 'address=/filesusr.com/0.0.0.0', with this rule is breaking every website hosted by Wix.  Could this rule be replaced by more specific rules which only match sites serving malware?

**Comment by notracking** [comment]
Thanks! Added to the whitelist, changes will be visible after the next auto update.
