### ISSUE TITLE
whitelist cryptonator.com

### ISSUE THREAD

**Issue by bahamas10** [notracking/hosts-blocklists#445]
i know that a *lot* of crypto or crypto related sites lead to money scams - I currently use this url (specifically api.cryptonator.com) as a source of data for a bitcoin price ticker.  AFAICT this website is safe and is not a scam / an ad.  AFAICT this URL was just added to the blocklist in the last 24 hours.

**Comment by notracking** [comment]
Thanks! Added to the whitelist, changes will be visible after the next auto update.
