### ISSUE TITLE
[ADD TO BLOCK] app-analytics-v2.snapchat.com

### ISSUE THREAD

**Issue by Trepter** [notracking/hosts-blocklists#447]
❌ `app-analytics-v2.snapchat.com`

- _It seems to be the domain of analytics or telemetry. Blocking doesn’t cause problems._

**Comment by notracking** [comment]
Is already blocked.

**Comment by Trepter** [comment]
@notracking - nextDNS doesn’ show that this domain and previous reports by me are blocked by your list.
![Uploading E2E53386-725E-40D5-A5EB-B38A7529541F.jpeg…]()

**Comment by notracking** [comment]
Now it's in permanently, thanks!
