### ISSUE TITLE
[ADD TO BLOCK] Apple domains

### ISSUE THREAD

**Issue by Trepter** [notracking/hosts-blocklists#448]
❌  analytics-events.apple.com
❌  analytics-events.news.apple-dns.net
❌  cstat.apple.com
❌  metrics.apple.com
❌  metrics.icloud.com
❌  metrics.mzstatic.com
- _The above domains for analytical data collection and telemetry_

Already exist on the list:
- [X] iadsdk.apple.com
- [X] cf.iadsdk.apple.com

**Comment by notracking** [comment]
These are already blocked.
