### ISSUE TITLE
Whitelist afraid.org DDNS subdomains

### ISSUE THREAD

**Issue by winduptoy** [notracking/hosts-blocklists#454]
`afraid.org` offers dynamic DNS hosting because home ISPs give users a random dynamic IP address. `afraid.org` lets me point a subdomain domain to my home server. These domains can be used by anyone with an account and are owned by `afraid.org`. The root domain `chickenkiller.com` should not be blocked because it prevents other users of `afraid.org` from creating a new subdomain for their own homeserver. For example, I can sign up for an account and `create my-custom-homeserver.chickenkiller.com`, but the blocklist is preventing me from accessing all subdomains of `chickenkiller.com`.

These domains are managed by `afraid.org`:

```
chickenkiller.com
ignorelist.com
mooo.com
twilightparadox.com
crabdance.com
jumpingcrab.com
strangled.net
```

**Comment by notracking** [comment]
Nice find, thanks for the info! These are added to the whitelist, changes will be visible after the next auto update.
