### ISSUE TITLE
Update : Fix domain name (SA)

### ISSUE THREAD

**Issue by TheJuln** [notracking/hosts-blocklists#457]
Hi,
Domain have changed for SA ;-) 

- simpleanalytics.io (old)
- simpleanalytics.com -> Not blocked
- *.simpleanalyticscdn.com -> Not blocked

*list*
https://raw.githubusercontent.com/notracking/hosts-blocklists/master/dnscrypt-proxy/dnscrypt-proxy.blacklist.txt

**Comment by notracking** [comment]
Thanks! Added to the custom list, changes will be visible after the next auto update.
