### ISSUE TITLE
Whitelisting of google.com interferes with custom blacklist (Adguard Home)

### ISSUE THREAD

**Issue by eggplanting** [notracking/hosts-blocklists#458]
Hello,

since google.com was added to your whitelist, my custom filters (blacklisting google.com for my Chromecast devices) in AdguardHome gets ignored.

Would it be possible to remove google.com from the whitelist and ensure that it just won't get added in the blacklist again?

Thanks for your list, I understand that such issues can happen.

**Comment by eggplanting** [comment]
Also added an issue for AdGuardHome, since custom filtering rules are less prefered than list entries:
https://github.com/AdguardTeam/AdGuardHome/issues/2371

**Comment by notracking** [comment]
Our whitelist is not suited for these cases and is the primary filter to prevent those hosts from entering the generic blocklist. You dns application could solve this though by ensuring that custom filters can never be overruled by any other automated list.

I publish the whitelist for openness and for other list maintainers to help them curating their own lists.
