### ISSUE TITLE
subdomains of domains, in domains.txt

### ISSUE THREAD

**Issue by larryhynes** [notracking/hosts-blocklists#46]
Hi

Examples:

`domains.txt` contains the likes of:

`collect.igodigital.com` and
`igodigital.com`

`c.mystat-in.net` and
`mystat-in.net`

`hit.stat24.com` and
`stat24.com`

As I understand it, you should be just listing the domains, and the subdomains will be automatically blocked. So I'm wondering why you're listing subdomains of domains that are listed in the `domains.txt` file?

**Comment by larryhynes** [comment]
Here's a list of domains that have subdomains listed in `domains.txt`:

```
cardiffwinetasting.co.uk
cardiffwinetasting.org.uk
dreamwithken.com
earnmoneywithken.com
edmontonbrandpartnerevents.com
ejtm.com
enjoyadreamlifestyle.com
enjoyyourdreamlifestyle.com
faststartgameplan.com
gameplansession.com
gameplanwebinars.com
govtax.com
govtax.net
govtax.org
hangoutathome.com
hillsharvest.com
igodigital.com
ku6.com
lifestyleluncheons.com
liveadreamlifestyle.com
lookinggoodlonger.com
mystat-in.net
stat24.com
stat.pl
```

**Comment by larryhynes** [comment]
And here, for completion's sake, is the listing of domains and their subdomains:

```
polo.cardiffwinetasting.co.uk
cardiffwinetasting.co.uk
polo.cardiffwinetasting.org.uk
cardiffwinetasting.org.uk
token.dreamwithken.com
dreamwithken.com
eas.earnmoneywithken.com
earnmoneywithken.com
etc.edmontonbrandpartnerevents.com
edmontonbrandpartnerevents.com
tem.ejtm.com
ejtm.com
zaeb.enjoyadreamlifestyle.com
enjoyadreamlifestyle.com
razer.enjoyyourdreamlifestyle.com
enjoyyourdreamlifestyle.com
plano.faststartgameplan.com
faststartgameplan.com
postal.gameplansession.com
gameplansession.com
play.gameplanwebinars.com
gameplanwebinars.com
gt.govtax.com
govtax.com
gv.govtax.net
govtax.net
gs.govtax.org
govtax.org
polo.hangoutathome.com
hangoutathome.com
zero.hillsharvest.com
hillsharvest.com
collect.igodigital.com
igodigital.com
stat.ku6.com
ku6.com
lop.lifestyleluncheons.com
lifestyleluncheons.com
ser.liveadreamlifestyle.com
liveadreamlifestyle.com
serd.lookinggoodlonger.com
lookinggoodlonger.com
c.mystat-in.net
mystat-in.net
hit.stat24.com
stat24.com
hit.stat.pl
stat.pl
```

**Comment by cbuijs** [comment]
In my <a href="https://github.com/cbuijs/unbound-dns-firewall">unbound-dns-firewall</a> Python module I use a bit of simple <a href="https://github.com/cbuijs/unbound-dns-firewall/blob/master/dns-firewall.py">code</a> to optimize domain-lists and remove sub-domains if the parent exists. See the function **"optimize-domlist"** for more details.

**Comment by larryhynes** [comment]
Thanks. I have no difficulty removing them, but I think it would be better if that was handled as close to the source as possible.

**Comment by cbuijs** [comment]
@larryhynes no worries. It was more as general information to be picked up by @notracking ;-).

**Comment by notracking** [comment]
These pop up in the list due to the way I'm importing custom domains from the scripts that detect re-occurring (random) hostnames, eg: 1.tracker.a.com 2.tracker.a.com 3.tracker.a.com will be combined in one tracker.a.com domain filter. Though I'm not checking if a.com is already in the list when importing those entries.

I'm currently working on this..

**Comment by notracking** [comment]
Really nice case you found there, I would not have noticed myself I think :)
This should be resolved with the next auto update (cron didn't run last night because I was working on this).

[+] Checking for overlapping custom domain filters OK!

**Comment by larryhynes** [comment]
That's great - many thanks for all your work.
