### ISSUE TITLE
suggestion to whitelist vk.cc

### ISSUE THREAD

**Issue by k03mad** [notracking/hosts-blocklists#466]
Hello, not sure what the policy is for link shorteners...
But `vk.cc` is a `vk.com` social network link shortener — users often use it to shorten links for their posts.

<img width="444" alt="vk cc" src="https://user-images.githubusercontent.com/3288444/103591658-d0b4bf00-4f01-11eb-94e6-47115a13a2ae.png">

**Comment by notracking** [comment]
Thanks! Unfortunately link shortners are a necessary evil today, they only cause link rot, but as long as they are not malicious I will add them to the whitelist as I will do with this one. Changes will be visible after the next auto update.
