### ISSUE TITLE
Clarification about tracking links

### ISSUE THREAD

**Issue by k03mad** [notracking/hosts-blocklists#468]
After starting using this block list, I added some links to the whitelist (really very little, compared to the other lists... thank you for your good support!).

Sorry to bother you, just wanted to clarify the policy on this links:

Tracking redirect links: broken links from mailing lists, social networks, etc.
```
go.redirectingat.com
go.skimresources.com
visit.digidip.net
```

Tracking deep links to apps: link from the web to the app does not open or sometimes leads to the wrong app layout
```
api2.branch.io
cdn.branch.io
```

Google ad in search results: this does not block the ad itself.
Advertising is perfectly blocked by the browser extension, is it worth breaking only clicks if ad is already shown?
```
www.googleadservices.com
```

**Comment by notracking** [comment]
Thanks for your feedback!

Sorry for the late reply, It took me a bit longer as I had to spend more time re-evaluating.

Personally I would not mind having these type of link redirectors blocked as I don't care about their 'malicious' intent and I'll just skip that part of the internet.. But considering that this will lead to confusing situations for non-technical users without adblock installed on dns-sinkholed networks, they are whitelisted (same goes for other similar type of redirectors as can be seen in the public whitelist). Still a shame though, they are the #1 cause of linkrot, but dns filtering is unfortunately not the solution to this..

I hope that answered your questions.. changes will be visible after the next autoupdate!
