### ISSUE TITLE
Activate the Wiki

### ISSUE THREAD

**Issue by githubcom13** [notracking/hosts-blocklists#47]
Hello, 
I want to share some code VBScript for:

- automatically update the hosts file (windows)
- to format the Wildcard DNS for the Acrylic_DNS_Proxy AcrylicHosts.txt file
- to format Wildcard DNS for Unbound unbound.conf (DNS server)

is it possible to activate the Wiki? 

Thanks

**Comment by notracking** [comment]
done!
