### ISSUE TITLE
Whitelist www.getmonero.org

### ISSUE THREAD

**Issue by nishaddesilva** [notracking/hosts-blocklists#470]
Please whitelist www.getmonero.org domain as it's a known cryptocurrency

**Comment by notracking** [comment]
This one is not listed in our blocklists.

**Comment by nishaddesilva** [comment]
> This one is not listed in our blocklists.

NextDNS says otherwise. Please refer attached image.
![W6jqJT](https://user-images.githubusercontent.com/74057395/104017988-1b268c00-51df-11eb-8b41-d72f61ef69e1.png)

**Comment by notracking** [comment]
did you try updating the list?

**Comment by nishaddesilva** [comment]
> did you try updating the list?

On NextDNS there's no way to manually update the lists. They take care of the updating part. But as I can see on GitHub the last update is 3 days ago.

**Comment by notracking** [comment]
In that case i cannot do anything about it other then advising you to contact nextdns to increase their update interval. Notracking list is updated every 24hours.

**Comment by nishaddesilva** [comment]
> In that case i cannot do anything about it other then advising you to contact nextdns to increase their update interval. Notracking list is updated every 24hours.

On GitHub too it shows the last update is 3 days ago. Am I missing something?

**Comment by notracking** [comment]
Oh dear! no I completely missed that. There seems to be something wrong with the commits. I'm looking into it, hang on..

**Comment by notracking** [comment]
And it's fixed, commit was silently failing due to some additional security checks. Public repos has been updated, thanks for your feedback!

**Comment by nishaddesilva** [comment]
> And it's fixed, commit was silently failing due to some additional security checks. Public repos has been updated, thanks for your feedback!

Great! Keep up the good work!
