### ISSUE TITLE
stackoverflow.az1.qualtrics.com

### ISSUE THREAD

**Issue by 3xploiton3** [notracking/hosts-blocklists#473]
source link https://stackoverflow.com/survey/site-satisfaction/redirect

![image](https://user-images.githubusercontent.com/19517680/104797490-05255680-57f1-11eb-8dfe-954f2459e0dd.png)

stackoverflow.az1.qualtrics.com

**Comment by notracking** [comment]
Thanks! Added to the whitelist, changes will be visible after the next auto update.
