### ISSUE TITLE
pushwelcome.com (false alarm)

### ISSUE THREAD

**Issue by 3xploiton3** [notracking/hosts-blocklists#476]
pushwelcome.com

break function on https://scribddownloader.org/

**Comment by notracking** [comment]
Please whitelist this one locally to get scribddownloader working again. Pushwelcome is particularly nasty for scamming people into allowing their notifications etc. Better to keep the 99% safe.

https://greatis.com/unhackme/help/remove/pushwelcome-com.htm

**Comment by 3xploiton3** [comment]
thx for advice, ok
