### ISSUE TITLE
www.driverfix.com (false alarm)

### ISSUE THREAD

**Issue by 3xploiton3** [notracking/hosts-blocklists#477]
![image](https://user-images.githubusercontent.com/19517680/105998728-8af1ad80-60df-11eb-8d06-a648d2f013c9.png)

www.driverfix.com

**Comment by notracking** [comment]
Are you sure you would like their software installed..? Look like a scam, smells like a scam and there are a lot of reports telling me they are a scam..

**Comment by 3xploiton3** [comment]
> Are you sure you would like their software installed..? Look like a scam, smells like a scam and there are a lot of reports telling me they are a scam..

ok thx for advice
