### ISSUE TITLE
Turkish National CERT

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#479]
Source ->
https://www.usom.gov.tr/

List ->
https://www.usom.gov.tr/url-list.txt

**Comment by notracking** [comment]
I'm not sure if adding government funded lists would be a good idea.. Their webservers are kinda restrictive too.

**Comment by scafroglia93** [comment]
I don't think it can cause problems with non-malicious sites, the blocks
are imposed by default by the various operators through the government so
you should be calm.

Il giorno sab 30 gen 2021 alle ore 22:02 notracking <
notifications@github.com> ha scritto:

**Comment by scafroglia93** [comment]
It was merged by nextdns inside threat intelligence list

**Comment by notracking** [comment]
That's find, and still thank for submitting. But besides that I cannot even reliably test this list (thanks to their restrictive webservers); Plus I'm not going to add (any) government operated blocklists.
