### ISSUE TITLE
FP: Oukitel OTA domains

### ISSUE THREAD

**Issue by k03mad** [notracking/hosts-blocklists#480]
Found in blocklist `adups.cn/adups.com` domains, which serve OTA updates for Oukitel phones:

hostnames:
```
0.0.0.0 fota4.adups.cn
:: fota4.adups.cn
```

domains:
```
address=/adups.com/0.0.0.0
address=/adups.com/::
```

refs and proof: https://github.com/AdAway/adaway.github.io/issues/205

**Comment by notracking** [comment]
Thanks! Added to the whitelist, changes will be visible after the next auto update.
