### ISSUE TITLE
Adblock rules leaking to dns-rules

### ISSUE THREAD

**Issue by jaketus** [notracking/hosts-blocklists#484]
There are adblock-rules leaking to the dnsmasq-blocklist causing dnsmasq to crash with segfault.

root@hc1:/etc/dnsmasq.d# cat blocklist.conf | grep -v -E "[()]" > blocklist2.conf
root@hc1:/etc/dnsmasq.d# diff blocklist.conf blocklist2.conf 
2d1
< #       / | / /___/_  __/________ ______/ /__(_)___  ____ _
26,27d24
/#address=/.ad-badge)
/#address=/.ad_top_close)
33d29
/#address=/.icon_ad)
43d38
/#address=/.xcybk-adfg)
5297d5291
/#address=/[data-href*="://t.cn/"])
5468,5472d5461
/#address=/a[href*="/lapin."])
/#address=/a[href*="://t.cn/"])
/#address=/a[href*="mmtp.net"])
/#address=/a[href*="tu."])
/#address=/a[href^="http"]:not([href*="cnbeta."])
9441,9443d9429
/#address=/ag_abortonpropertyread('string.fromcharcode');
/#address=/ag_abortonpropertywrite('string.fromcharcode');
< address=/ag_setconstant('property.chain',/#
71555d71540
/#address=/img:not(.avatar)

**Comment by notracking** [comment]
Yes, I noticed this immediately, but was not able to fix it sooner than right now. Changes of last night have been reverted.

**Comment by notracking** [comment]
Issue has been fixed; was a typo when adding a new list :| (should not do that at 2:00 in the night..) I'm going to add some additional automated syntax-sanity checks before running the daily commit, to prevent this from happening in the future.
