### ISSUE TITLE
I have a C program for you to identify the current 3541 duplicate subdomains! Enjoy!

### ISSUE THREAD

**Issue by lukensmall** [notracking/hosts-blocklists#488]
[unbound_servers_deduplicate.txt](https://github.com/notracking/hosts-blocklists/files/5938670/unbound_servers_deduplicate.txt)

**Comment by notracking** [comment]
Hi @lukensmall thanks for your C program :)

It's a good find! These hosts are there for a (legacy) reason. Initially the old (<2.8) dnsmasq list, had a distinction between 'wildcard' hosts and specific domains. '*.ads.google.com' vs 'ads.google.com'. This has an advantage of being able to do more precise blocking (which in practice does not add much).

This is likely the reason that most hostname based blocklists are wild-carding everything '*.anyrule.com'. I will remove these from all lists, except the legacy dnsmasq version (someone might still be using it somewhere..).

**Comment by lukensmall** [comment]
Also, I changed it from “static” to “redirect” because at least in OpenBSD’s unbound.conf manpage, redirect covers all subdomains and I don’t think that static does!

**Comment by notracking** [comment]
Just checked and also that works exactly as you described. statics are now redirects and the dupes will be replaced after the next update. Thanks!
