### ISSUE TITLE
post.spmailtechno.com [false positive]

### ISSUE THREAD

**Issue by 3xploiton3** [notracking/hosts-blocklists#489]
https://github.com/nextdns/metadata/issues/568#issue-802926868

**Comment by StevenBlack** [comment]
Take note that in Issue https://github.com/StevenBlack/hosts/issues/1532 we decided to keep blocking domain `post.spmailtechno.com`

**Comment by notracking** [comment]
Thanks for submitting, but it will remain in place here as well.
