### ISSUE TITLE
should be blocked from chinese apk

### ISSUE THREAD

**Issue by 3xploiton3** [notracking/hosts-blocklists#490]
tclclouds.com
attclouds.com
ads-api.attclouds.com

based on 
[virustotal scan domain](https://www.virustotal.com/gui/file/d43cde31ed08ba7aa73adef6bcca8439def5ed21766bd488714b4b15b20ce61e/detection)
[vpnpro.com](https://vpnpro.com/blog/chinese-company-secretly-behind-popular-apps-seeking-dangerous-permissions/)

**Comment by notracking** [comment]
Both your links do not give an actual correlation, but this one did: https://forums.crackberry.com/blackberry-key2-f472/tcl-preview-app-bloatware-1179515/index2.html

Added to the custom list.
