### ISSUE TITLE
[denylist] bidbarrel.cbsnews.com - tealium.cbsnews.com

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#493]
bidbarrel.cbsnews.com -> is used for real time bidding of ad placement.
tealium.cbsnews.com -> is used for Tealium, a tracking company.

That's come from PGL ->
https://github.com/nextdns/metadata/issues/574#issuecomment-779121198

Sorry for my previous request

**Comment by notracking** [comment]
And fixed, I should have also checked this one better.
