### ISSUE TITLE
[blocklist] fundingchoicesmessages.google.com

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#494]
I found this within the nextdns logs and it actually removes the cookie selection

**Comment by notracking** [comment]
For some people it will also give a un-removable anti-adblock overlay on some site. I've tested it without a content blocker and it seems to be fine to block. Let's give it a try, item will be added with the next auto update. Thanks!

https://postimg.cc/9r5sPyYM
