### ISSUE TITLE
[blocklist] fp.msedge.net

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#496]
Source ->
https://docs.microsoft.com/en-us/windows/privacy/windows-endpoints-1709-non-enterprise-editions

Used by OfficeHub to get the metadata of Office apps

**Comment by notracking** [comment]
I believe that this is just for usage in other app within their ecosystem. Blocking this only reduce usability of MS office. If one does not use office, then there is no need to block this.
