### ISSUE TITLE
[blocklist] images-revi.rcsobjects.it

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#498]
This removes the banner ad without inhibiting access to premium content

![Cattura](https://user-images.githubusercontent.com/8227101/108692036-0afb0f80-74f4-11eb-8910-e0995d72c8a0.PNG)

**Comment by scafroglia93** [comment]
to block images and premium content (digital subscription)  ->
revi.rcsobjects.it

**Comment by notracking** [comment]
Thanks! Added to the custom list, changes will be visible after the next auto update.
