### ISSUE TITLE
[blocklist] multiple malicious domain

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#499]

**Comment by scafroglia93** [comment]
All this malicious domain come from our cert


viteunerecettewca.ru
consuitlng.com
haloopolikosul.xyz
trapolikoliosilios.xyz
online-privati.help
dettrazieni.com
lopppooole.xyz
inps-servizi.com
willeam.org
eclatcollection.com
pklz.xyz
gestiondecorreo.info
3rdcamp.ga
xieliorn.com
danae.to
kavauelo.co
the3rd.ml
piesislel.is
s3.us-west-1.wasabisys.com
bizzznez.com
winntdmnf.club
burtontracks.com
northcountrysocial.com
tvfconnections0.us-south.cf.appdomain.cloud
mamylining.com
live.investtoimpressclub.com
agenziaentrateinformazioni.icu
mazedecrypt.top
siurreje.xyz
13287469.best
egiiuouy.club
newupprolods.club
inbizzzilink.club
aliiuyrt.space
newupprolods.fun
hellokittyvietnam.com
newupprolods.fun
aliiuyrt.xyz
aliiuyrt.space

**Comment by notracking** [comment]
Thanks! Added to the custom list, changes will be visible after the next auto update.
