### ISSUE TITLE
Google hangouts on desktop is blocked

### ISSUE THREAD

**Issue by stacia** [notracking/hosts-blocklists#5]
Hi, this list was working great for me but today I noticed sending messages signed in to my Gmail account via hangouts were not sending (but they sent from my phone, must use different servers). I found out it was related to this hosts file. I am not exactly sure how to find the exact domain that it is blocking, if you help me find out how to do that I will report the domain. Thanks.

**Comment by notracking** [comment]
Sorry for the late reply (kinda on holiday right now). Is it possible for you to provide me with a dns request log when using hangouts?

Otherwise I'll have to debug it beginning of next week (I'm travelling around now with limited internet).

**Comment by notracking** [comment]
Provided solution should work. If not, please open a new ticket.
