### ISSUE TITLE
brain-dead adding of free domains 

### ISSUE THREAD

**Issue by bash-stack** [notracking/hosts-blocklists#500]
Hey congrats, 
you blindly blocked 
`cloudns,cl`
but did not include 
`cloudns.asia` and some other free subdomains

**( that you shall not block since users get the level below and you really steal peoples time when using raspap with this ad-whatever-somehing ( i will not call it list )) , thanks for that 30 minutes .. really ..great**

( separate congrats for blinldy blocking and effectively making people move to nextdns or other stuff , really.. great )

**Comment by notracking** [comment]
whitelisted cloudns.cl
Thanks! Added to the whitelist, changes will be visible after the next auto update.
