### ISSUE TITLE
very clever - scammers can just wait after NXDOMAIN

### ISSUE THREAD

**Issue by bash-stack** [notracking/hosts-blocklists#501]
scammers only need to send NXOMAIN until you pruned them and can easily come back 

congrats , 10/10 p(o)ints

( even worse , once the might see your bot returning , e.g. by controlling multiple malicous domains and checking on dns cron they might just specifically send NXDOMAIN to the bot and laugh and laugh and laugh)

**Comment by notracking** [comment]
Domains are actually checked on registrar data not just NXDOMAIN as most lists do, so I'm not sure what you are talking about.
