### ISSUE TITLE
*-dnsotls-ds.metric.gstatic.com should not be blocked

### ISSUE THREAD

**Issue by pfactum** [notracking/hosts-blocklists#504]
The line:

```
address=/metric.gstatic.com/#
```

breaks new Android connectivity check if DoT (*aka "Private DNS"*) is used because it queries domains like this one:

```
6mwqPF-dnsotls-ds.metric.gstatic.com
```

and bails out in case no response is given.

IMO, `metric.gstatic.com` is too generic and should be split into relevant subdomains.

If it cannot be split, I'll just leave a PowerDNS-based workaround in Lua here in case someone encounters this issue as well:

```lua
function preresolve(dq)
…
    if string.gmatch(dq.qname:toString(), "%w+%-dnsotls%-ds%.metric%.gstatic%.com%.") then
        return false
    end
…
```

Thanks.

**Comment by notracking** [comment]
Thanks! Added to the whitelist, changes will be visible after the next auto update.

**Comment by pfactum** [comment]
Just an update on my previous workaround, because it is screwed. The correct way of handling that is:

```lua
    -- allow Android 9+ connectivity check
    if string.find(dq.qname:toString(), "%w+%-dnsotls%-ds%.metric%.gstatic%.com%.") ~= nil then
        return false
    end
```
