### ISSUE TITLE
[blocklists] cmp.sky.it

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#506]
prevents the opening of the banner for the selection of cookies within ->
https://video.sky.it/diretta/tg24

**Comment by notracking** [comment]
Will this not prevent users from playing video?

**Comment by scafroglia93** [comment]
from the tests I carried out no block was found

**Comment by notracking** [comment]
did you clear your cookies before testing with the block in place? These type of consent requests usually lead to unplayable media if a cookie is not defined

**Comment by scafroglia93** [comment]
Yep, for me it's ok at the moment

**Comment by notracking** [comment]
Thanks! Added to the custom list, changes will be visible after the next auto update.
