### ISSUE TITLE
imedia.cz should be blocked

### ISSUE THREAD

**Issue by pfactum** [notracking/hosts-blocklists#507]
`imedia.cz` is a Czech-focused ad network, and hence it should be blocked.

The following subdomains serve ad and tracking content:

* `i.imedia.cz`
* `h.imedia.cz`
* `ssp.imedia.cz`

Please consider. Thanks.

**Comment by notracking** [comment]
This one is already blocked, see: imedia.cz

**Comment by pfactum** [comment]
Right, sorry, I was fooled by my Lua script. Thanks.
