### ISSUE TITLE
[blocklist] malware

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#510]
this come from our internal cert ->
basilrealty.in
cluebazar.com
daunhotmiendong.vn
mainctional.com
disrulaytin.ru
puldefletat.ru
nvgeeforsegt.ru
sweyblidian.com
verstudiosan.com
beachtreepestcontrol.com

**Comment by notracking** [comment]
Thanks! Added to the custom list, changes will be visible after the next auto update.
