### ISSUE TITLE
Blocking foxnews.com

### ISSUE THREAD

**Issue by CodeSapiens** [notracking/hosts-blocklists#511]
I'm sure this was by accident and not a political statement. :-)
Here is the AdGuard response when using your filter:

Rule(s)
a.a
No-Tracking Blacklist
Response
A: 0.0.0.0 (ttl=10)
Original response
CNAME: www.foxnews.com.edgekey.net. (ttl=201)
CNAME: e4900.dsca.akamaiedge.net. (ttl=201)
A: 104.126.21.2 (ttl=201)

**Comment by notracking** [comment]
Not sure what is going on here. Foxnews is working perfectly and those cnames are not in the current version of the blocklist. Did you try updating it to the latest version?

**Comment by CodeSapiens** [comment]
Yes. 
When I disable your list, then it works.
It must be a CDN or something along those lines.
Mar 6, 2021, 6:09 AM by notifications@github.com:

**Comment by notracking** [comment]
i think that you are using a different list, namely the no-track list. Nothing wrong with our Notracking list :)

**Comment by CodeSapiens** [comment]
Ok. I appreciate you looking into it. I will keep digging and hopefully find what happened.
This is the list I am adding to AdGuard Home:
https://raw.githubusercontent.com/notracking/hosts-blocklists/master/dnscrypt-proxy/dnscrypt-proxy.blacklist.txt

Thanks again for your time. Have a great weekend!

Mar 6, 2021, 9:29 AM by notifications@github.com:

**Comment by CodeSapiens** [comment]
I found the culprit. Your list has an entry for edgekey.net. That is what is causing foxnews.com to be blocked. If you remove that one entry then it works. You must have an exception on your end which causes it to be whitelisted. Hope this helps.


Mar 6, 2021, 9:29 AM by notifications@github.com:

**Comment by notracking** [comment]
Thanks for double checking!

Still strange though, because edgekey.net is also not listed and even has a preventive whitelist entry.
The only edgekey item listed is the one below..

```
> grep edgekey.net dnscrypt-proxy.blacklist.txt 
analytics.edgekey.net
```
