### ISSUE TITLE
nentgroup.com

### ISSUE THREAD

**Issue by gita6t5** [notracking/hosts-blocklists#512]
NextDNS tells me that this list is blocking it.
net-corp-v2.prod-mid-euw3.investis.com
![Zrzut ekranu z 2021-03-09 16-20-24](https://user-images.githubusercontent.com/80338577/110494025-7a2b5300-80f3-11eb-9b38-9bca73bac0a2.png)

**Comment by notracking** [comment]
Thanks! Added to the whitelist, changes will be visible after the next auto update.
