### ISSUE TITLE
[blocklist] malware multiple domain

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#514]
this come from our internal cert ->

sarayutseena-001-site1.gtempurl.com	
sharonbrockway.com
outgrowmeinie.com
oxcoz.com
enel-ei.com
dilloaposteitaliane.it
pagrlbaf24.com
puzzling-strong-bestseller.glitch.me
sharonbrockway.com

**Comment by scafroglia93** [comment]
digitaldays.ro
onealabamasport.com
maxassur.com
iymorenterprizelogs.com

**Comment by notracking** [comment]
Thanks! Added to the custom list, changes will be visible after the next auto update.
