### ISSUE TITLE
[blocklist] stats domain

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#516]

**Comment by scafroglia93** [comment]
analytics.cert.pl
analytics.forthnet.gr
analytics.hchristo.de
analytics.keepassxc.org
analytics.systemli.org
analytics.torguard.net
killtheradiostats.nfshost.com
log.eufylife.com
matomo.a-com.eu
matomo.hetzner.com
matomo.riot.im
matomo.standardnotes.org
matomo.startmail.com
piwik.mailbox.org
piwik.nic.cz
piwik.ovpn.se
piwik.savoirfairelinux.net
stat01.opsanalytics.ch
stats.airvpn.org
stats.azirevpn.com
stats.bahnhof.net
stats.ivpn.net
stats.windscribe.com
thunderbird.innocraft.cloud
webstats.oriented.net

**Comment by scafroglia93** [comment]
stats.controld.com

**Comment by scafroglia93** [comment]
1.e-analytics.eu
azmatomo.service.4matnetworks.com
catalyst-analytics.eu
edp-piwik-l68tf.ebayc3.com
matomo.hactar.is
matomo.ic.training
matomo.ria.ee
piwik.anonymox.net
piwik.everzones.com
piwik.innosabi.net
stats.embarcaderedusavoir.be
stats.myminifactory.com
stats.planespotters.net
tryzens-analytics.com
usertrack.balticlei.ee
web-analytics.uni-muenchen.de
webanalyse.urz.uni-heidelberg.de

**Comment by notracking** [comment]
Thanks! Added to the custom list, changes will be visible after the next auto update.
