### ISSUE TITLE
Please add support for repique

### ISSUE THREAD

**Issue by AZ-X** [notracking/hosts-blocklists#518]
https://github.com/AZ-X/pique

Thanks.

**Comment by notracking** [comment]
You do not support the dnscrypt-proxy style formatting?

**Comment by AZ-X** [comment]
> dnscrypt-proxy style

Dnscrypt-proxy style is so naive :bowtie: to use.

You can find the [repique style here](https://github.com/AZ-X/pique/blob/master/examples/configuration/black_cloaking_routine.txt.example).
