### ISSUE TITLE
Special Character Causing Load to Fail on CentOS 6.9

### ISSUE THREAD

**Issue by crunchmouth** [notracking/hosts-blocklists#52]
Greetings,

When attempting to start dnsmasq after following the instructions, the following error is returned:

Starting dnsmasq:
dnsmasq: error at line 59565 of /etc/dnsmasq.d/domains.txt [FAILED]

This corresponds to the entry address=/streamillimité.com/0.0.0.0. I believe the special char is causing it to fail. If I comment the entry out it works fine.

Great project

**Comment by notracking** [comment]
I’ve sent an email to the list maintainer containing this iten, excellent find! I will look into fixing this in my filter later on (have to do some more testing)

**Comment by notracking** [comment]
Fix turned out in a change of list sources. See commit: https://github.com/notracking/hosts-blocklists/commit/7f0720db457a96fb64a95c642e4677b94fc69ce5

Changes to the list will be visible with the next auto update.

Thanks!
