### ISSUE TITLE
new list malware

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#520]
Made by ->
https://twitter.com/cyb3rops

https://github.com/Neo23x0/signature-base/blob/master/iocs/c2-iocs.txt

**Comment by scafroglia93** [comment]
bambenek (sunburst)
https://raw.githubusercontent.com/bambenek/research/main/sunburst/uniq-hostnames.txt

**Comment by notracking** [comment]
This is not really actively maintained, is it? Last commit is from 3 months ago.

**Comment by scafroglia93** [comment]
this is because at the moment the Sunburst IoCs are these; there is nothing else to report (SolarWinds Attack)

**Comment by scafroglia93** [comment]
They are managed by two major cybersecurity firms, at most if they are not good you take them off in the future
