### ISSUE TITLE
[blocklist] stats domain

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#522]
2004cx.com
analys.eslov.se
analytics01.meride.tv
analytics.allkeyshop.com
analytics.anton.ch
analytics.aquakori.hr
analytics.avatrade.io
analytics.bit.admin.ch
analytics.enisa.europa.eu
analytics.finna.fi
analytics.foodgeek.dk
analytics.govinfo.gov
analytics.instantsystems.se
analytics.milkman.it
analytics.mymovies.tools
analytics.pilatus-aircraft.com
analytics.prodalet.ru
analytics.studio.az
analytics.tekfixweb.fi
analytics.ti-edu.ch
analytics.trackingb2b.com
analytics.ubicross.net
analytics.vco24.it
analyzeit.itu.dk
dtstats.mediolanum.it
eu1.analytics.psb.f-secure.com
icewear.innocraft.cloud
jospos.innocraft.cloud
loendaja.eenet.ee
log-sdk.shopfully.tech
logservice1.hicloud.com
logservice.hicloud.com
matomo.a1.by
matomo.courier.no
matomo.forte.kz
matomo.helpdesk.is
matomo.ipag.by
matomo.miraheze.org
matomo.pureref.com
matomo.ria.ee
matomo.ruc.dk
matomo.srce.hr
matomo.stil.dk
matomo.x-srv.de
metrics1.data.hicloud.com
metrics2.data.hicloud.com
metrics3.data.hicloud.com
metrics4.data.hicloud.com
metrics5.data.hicloud.com
metrics.data.hicloud.com
metrics.icloud.com
piwik-ext.vgregion.se
piwik.aipi.de
piwik.app.jyu.fi
piwik.estudio.am
piwik.fairdanmark.dk
piwik.iligsoft.hr
piwik.kk.dk
piwik.lnf.infn.it
piwik.musik-meyer.net
piwik.smit.ee
piwik.stuff.is
piwik.uet.edu.al
portainer.cloud.mechta.kz
regstat.regeringen.se
ssl-metrics.tim.it
stat-aarau.backslash.ch
stat.aaltospaino.fi
stat.aaniraatali.fi
stat.envir.ee
stat.shamsasoft.ir
stat.uueduudised.ee
stats.fn.sportradar.com
stats.gmdigital.it
stats.gouv.mc
stats.gstu.by
stats.konsept-it.no
stats.ksearchnet.com
stats.newave.fi
stats.newsfront.no
stats.w3b.fi
tilastot.gaselli.software
tracking.gdatasoftware.com
ugla-stat.hi.is
uxmetrics.unipolsai.it
vik-analytics.moonactive.net
was-stats.wondershare.com
webanalytic.aalborg.dk
webanalytics.digiaiiris.com
webanalytics.garr.it
webanalytics.prod.ooda-health.io
webstats.cloud.ictmedia.hr
webstats.forsakringskassan.se

**Comment by scafroglia93** [comment]
Apple ->
metrics.icloud.com

Huawei ->
metrics.data.hicloud.com
metrics1.data.hicloud.com
metrics2.data.hicloud.com
metrics3.data.hicloud.com
metrics4.data.hicloud.com
metrics5.data.hicloud.com
logservice.hicloud.com
logservice1.hicloud.com

**Comment by iam0day** [comment]
I also suggest you the domains `v1.telemetry.coder.com`
`telemetry.coder.com`
`statsapi.tiendeo.it`
`dtstats.mediolanum.it`
`statsdigital.com`

**Comment by scafroglia93** [comment]
2004cx.com
analys.eslov.se
analytics.aquakori.hr
analytics.finna.fi
analytics.foodgeek.dk
analytics.instantsystems.se
analytics.prodalet.ru
analytics.studio.az
analytics.tekfixweb.fi
analytics.trackingb2b.com
analytics.ubicross.net
analyzeit.itu.dk
eu1.analytics.psb.f-secure.com
icewear.innocraft.cloud
jospos.innocraft.cloud
loendaja.eenet.ee
matomo.a1.by
matomo.courier.no
matomo.forte.kz
matomo.helpdesk.is
matomo.ipag.by
matomo.miraheze.org
matomo.pureref.com
matomo.ria.ee
matomo.ruc.dk
matomo.srce.hr
matomo.stil.dk
matomo.x-srv.de
piwik-ext.vgregion.se
piwik.aipi.de
piwik.app.jyu.fi
piwik.estudio.am
piwik.fairdanmark.dk
piwik.iligsoft.hr
piwik.kk.dk
piwik.musik-meyer.net
piwik.smit.ee
piwik.stuff.is
piwik.uet.edu.al
portainer.cloud.mechta.kz
regstat.regeringen.se
stat.aaltospaino.fi
stat.aaniraatali.fi
stat.envir.ee
stat.shamsasoft.ir
stat.uueduudised.ee
stats.gouv.mc
stats.gstu.by
stats.konsept-it.no
stats.newave.fi
stats.newsfront.no
stats.w3b.fi
tilastot.gaselli.software
ugla-stat.hi.is
webanalytic.aalborg.dk
webstats.cloud.ictmedia.hr
webstats.forsakringskassan.se

**Comment by notracking** [comment]
Added all unique hosts to the custom list.
