### ISSUE TITLE
[blocklist malware] multiple domain

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#526]
alaseeldates.com
alwayscomply.com
aprilstudios.in
arnoldinum.cloud
chamkoon.com
cluebazar.com
daunhotmiendong.vn
emiratesminning.com
gruporhynous.com
livenetworks.com.br
locequipamentosbh.com.br
museubandasfilarmonicas.pt
nepila.com
rgstage.com
runolfssonbecker.icu

**Comment by notracking** [comment]
Thanks! Added to the custom list, changes will be visible after the next auto update.
