### ISSUE TITLE
stats domain

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#527]
aews-analytics.sogei.it
analytics.callplus.co.nz
analytics.milankragujevic.com
fastmail.innocraft.cloud
goodcoffee.innocraft.cloud
logging.je-apps.com
logonrealmegovtnz.innocraft.cloud
matomo-tracking.fia.com
matomo.apps.paris.fr
matomo.greenleft.org.au
matomo.savoryandpartners.com
matomo.sostariffe.it
metrics.fadv.com
pi-ogp.coi.gov.pl
pi.coi.gov.pl
piwik.blue.pl
piwik.datalandsoftware.com
piwik.drivek.com
piwik.hidester.com
piwik.nowoczesnapolska.org.pl
piwik.vls.icm.edu.pl
piwik.zu.ac.ae
stat.szybszy.net
statistiche.unica.it
statistics.cmre.knowledgearc.app
stats-web.polytechnique.fr
stats.antarctica.gov.au
stats.come.uw.edu.pl
stats.koolinus.net
stats.vikidia.org
stats.whiteready.com
telemetry.hbbtv.sky.it
wmrs.innocraft.cloud

**Comment by scafroglia93** [comment]
piwik.hidester.com
matomo.sostariffe.it
statistiche.unica.it
aews-analytics.sogei.it
statistics.cmre.knowledgearc.app
matomo-tracking.fia.com
stats-web.polytechnique.fr
matomo.apps.paris.fr
piwik.drivek.com
stats.whiteready.com
stats.vikidia.org

**Comment by scafroglia93** [comment]
analytics.callplus.co.nz
fastmail.innocraft.cloud
goodcoffee.innocraft.cloud
logonrealmegovtnz.innocraft.cloud
matomo.greenleft.org.au
metrics.fadv.com
pi-ogp.coi.gov.pl
pi.coi.gov.pl
piwik.blue.pl
piwik.nowoczesnapolska.org.pl
piwik.vls.icm.edu.pl
stat.szybszy.net
stats.antarctica.gov.au
stats.come.uw.edu.pl

**Comment by scafroglia93** [comment]
piwik.zu.ac.ae
matomo.savoryandpartners.com
piwik.datalandsoftware.com
wmrs.innocraft.cloud
analytics.milankragujevic.com

**Comment by notracking** [comment]
Thanks! Added to the custom list, changes will be visible after the next auto update.
