### ISSUE TITLE
False positive: viewpoint.com blocked

### ISSUE THREAD

**Issue by stupaq** [notracking/hosts-blocklists#529]
Compiled dnsmasq.blacklist.txt contains `address=/viewpoint.com/#` line, which blocks the site. It's a legitimate provider of project management software used by architects.

**Comment by scafroglia93** [comment]
it's blocking also in steven black and oisd (source -> nextdns)

**Comment by notracking** [comment]
It's removed from Steve's list by now, item is whitelisted. Thanks!
