### ISSUE TITLE
Pure Domains Version?

### ISSUE THREAD

**Issue by hl2guide** [notracking/hosts-blocklists#531]
Please consider a version that just contains purely one domain per line, no extra info.

**Comment by notracking** [comment]
The header remains, also for license info. You could try `curl https://raw.githubusercontent.com/notracking/hosts-blocklists/master/dnscrypt-proxy/dnscrypt-proxy.blacklist.txt | grep -v '#' > dnscrypt-proxy.blacklist.txt` or something like that..
