### ISSUE TITLE
False positive: Domain oasis.opstatics.com is blocked

### ISSUE THREAD

**Issue by torabkheslat** [notracking/hosts-blocklists#532]
Hi Guys

why oasis.opstatics.com is blocked ?

**Comment by iam0day** [comment]
It's my fault (https://github.com/notracking/hosts-blocklists/issues/522#issuecomment-803194612) but on my One Plus it hasn't caused any kind of problem, have you? I've had it blacklisted for a few weeks now and haven't experienced any issues. Anyway it should be a telemetry domain.

**Comment by iam0day** [comment]
![Screenshot_20210326-122553~2](https://user-images.githubusercontent.com/17969978/112624890-7a835800-8e2e-11eb-9ab1-acd8fd0cc66b.png)

Ok it would appear that it is not a telemetry domain but a CDN, I needed to do more checking before proposing it.

The strange thing is that until a few weeks ago (when I added it to the blacklist manually) the official site had no issues.

**Comment by notracking** [comment]
Thanks! Added to the whitelist, changes will be visible after the next auto update.
