### ISSUE TITLE
False positive: f000.backblazeb2.com is blocked

### ISSUE THREAD

**Issue by remyabel** [notracking/hosts-blocklists#534]
This is a Backblaze API domain used for cloud storage. Probably added to the blacklist because cloud storage can be used for malware, but that doesn't mean the API should be blocked.

**Comment by scafroglia93** [comment]
https://www.virustotal.com/gui/domain/f000.backblazeb2.com/detection

**Comment by remyabel** [comment]
Yes and what is your point? Like I said already it's an official Backblaze domain where people sometimes host malware from. No different than Cloudflare or Cloudfront.

**Comment by notracking** [comment]
Thanks! Added to the whitelist, changes will be visible after the next auto update.
