### ISSUE TITLE
[blocklist] phishing urgent

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#535]
119910.xyz
xbtbxggxz.asia
xss.news
145650.xyz
chatwhatsapp.today
cdn-bimi.akamaized.net
www.googles-analytics.com 
ajax.googlescdn.com

**Comment by scafroglia93** [comment]
https://www.virustotal.com/gui/domain/www.googles-analytics.com/details

**Comment by notracking** [comment]
Thanks! Added to the custom list, changes will be visible after the next auto update.
