### ISSUE TITLE
new list -> matomo spammer

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#538]
the list is maintained directly by Matomo, the company that offers a Google Analytics alternative

https://github.com/matomo-org/referrer-spam-list/blob/master/spammers.txt ->
https://raw.githubusercontent.com/matomo-org/referrer-spam-list/master/spammers.txt

**Comment by notracking** [comment]
Too many false positives on this one; referrer spammer lists are also maintained for a different purpose (in this case to clean out Piwik data). This is an issue that will solve itself as browsers are removing the referrer option anyway.
