### ISSUE TITLE
new list -> nolovia

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#539]
https://github.com/parseword/nolovia/blob/master/skel/hosts-nolovia.txt ->
https://raw.githubusercontent.com/parseword/nolovia/master/skel/hosts-nolovia.txt

https://github.com/parseword/nolovia/blob/master/skel/hosts-government-malware.txt ->
https://raw.githubusercontent.com/parseword/nolovia/master/skel/hosts-government-malware.txt

**Comment by notracking** [comment]
First one is relatively high on false positives, but acceptable. Added both and monitoring.
