### ISSUE TITLE
dnsmasq doesn't like 127.0.0.1

### ISSUE THREAD

**Issue by Mausy5043** [notracking/hosts-blocklists#54]
The blocklist seems to contain the localhost. This causes an error:

```
dnsmasq:: ignoring nameserver 127.0.0.1 - local interface
```

**Comment by Mausy5043** [comment]
Please remove these lines from `hostnames.txt`
```
###############################[LOCALHOST]###############################
127.0.0.1 localhost
::1       localhost
```

**Comment by notracking** [comment]
Not only because of the warning, but our list should stick to its main purpose and allocating local domains is not a part of that.

Thanks for the sugestion! localhost will be removed with the next auto update
