### ISSUE TITLE
new list -> Shadow Whisperer

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#541]
https://github.com/ShadowWhisperer/BlockLists/tree/master/Lists ->
https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Ads
https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Malware
https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Scam
https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Shock
https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Tracking
https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Typo

**Comment by notracking** [comment]
https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Ads # overly regressive, not added
https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Malware # Added!
https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Scam # Added!
https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Shock # Not added, also contains politically unacceptable lists, which is out of scope for the notracking list
https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Tracking # Way to many false calls
https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Typo # Too many dead hosts, get the idea but adding any form of typo will increase the list size indefinately

**Comment by notracking** [comment]
The remaining 2 turned out to be pretty unreliable as well, reverting these and blacklisted all of them..
