### ISSUE TITLE
new list -> IOC List

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#542]
https://github.com/Hariharann8175/Indicators-of-Compromise-IOC- ->
https://raw.githubusercontent.com/Hariharann8175/Indicators-of-Compromise-IOC-/master/DNS-BH%20Malware%20Domains%20List
https://raw.githubusercontent.com/Hariharann8175/Indicators-of-Compromise-IOC-/master/Malicious%20Banking%20Sites
https://raw.githubusercontent.com/Hariharann8175/Indicators-of-Compromise-IOC-/master/Malware%20Domain%20List
https://raw.githubusercontent.com/Hariharann8175/Indicators-of-Compromise-IOC-/master/Maze%20Ransomware%20URL%20List
https://raw.githubusercontent.com/Hariharann8175/Indicators-of-Compromise-IOC-/master/Ransomware%20URL's

**Comment by notracking** [comment]
Not actively maintained, last update is from almost a year ago.
