### ISSUE TITLE
new list -> blocklistproject

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#543]
https://github.com/blocklistproject/Lists#lists->
https://blocklistproject.github.io/Lists/abuse.txt
https://blocklistproject.github.io/Lists/ads.txt
https://blocklistproject.github.io/Lists/fraud.txt
https://blocklistproject.github.io/Lists/malware.txt
https://blocklistproject.github.io/Lists/phishing.txt
https://blocklistproject.github.io/Lists/ransomware.txt
https://blocklistproject.github.io/Lists/scam.txt
https://blocklistproject.github.io/Lists/tracking.txt

**Comment by notracking** [comment]
`[+] Number of whitelist matches: 267`

I also believe that this is aggravated list, 75%+ is already covered, without deadhosts. Not added.
