### ISSUE TITLE
more malware

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#550]
0003599.com
2n57.com
77.220.64.132
238olive.com
665asilo.com
4515a.com
100973671.review
aclassapart.in
acmazout.be
adsmat.com
afrimedspecialist.com
afternoontravel.site
agenziecombusti.com
agnostec.com
aguasyaguas.co
algoritas.com
alinkarmay.com
alkiefsaudi.com
alphastand.top
alphastand.trade
alphastand.win
amazon-service-app-account.com
amos524.org
amymako.com
andreabelen.com
andreshconcejal.solucioneslink.com
anezhoney.com
anterongiye.space
ao2aalom.digital
ap-333.com
aprilmarieclaire.com
apsolution.work
aromabiensa.com
artcode-software.com
artebythesea.com
artistascitizen.com
ascentconsultants.in
attorneycruz.com
avantfarme.com
ayescarrental.com
banksblue.com
barryteeling.com
barstyle22.es
bdnextrend.xyz
beautincollagen.rs
becharnise.ir
belenusadvisory.net
benficalovers.com
betteringthehumanexperience.xyz
beveragesmiami.solucioneslink.com
beyoutifulblessings.com
billing.rahitechnosoft.com
binderrulemanes.com.ar
binoy.stalphonsamissionva.org
bizcert360.com
blog.daraisolty.com
boiler-portal.com
bonus4.jlddecora.com.br
buildnextfrc.com
bulksms.xava.co.in
bulkyfoodja.com
careercoachconnection.com
catsorriso.com.br
charutaplus.com
chienluocmarketing.net
citestaccnt1597691130.com
coffeyquiltco.com
cofisconconsultoria.com.br
colinboycemp.net
constipationhub.com
contecoliving.com
course.adsensetech.tech
courtneyrunyon.com
cruiseameroca.com
deerokoj.com
dein-chile.cl
deluxegift.ru
demo-cliente.mindcreative.com.br
denchtraders.co.uk
dent-estet.com
diafir.ro
doctorsdietgulfport.com
dulacon.nject.be
e01eykoc.xyz
ebitit.com
edeny.xyz
edintraining.com
enel-dxx.blogspot.com
enel-iee.blogspot.com
escalezen.be
esdras-almeida.com
esrise.net
estudiarviajando.com
ext-sq.squarespace.com
fairisnotfair.com
fangyu5827.com
farmnatural.in
fasoum.com
findmyautoparts.com
finestfaux.com
flawlessdrinking.com
follower.instantcashback.in
fonderfonds.at
freegeoip.app
frontlearn.co.ke
frontrangetechnologies.com
gdsis.cl
getacademicwriters.savmogroup.com
grandpaurbanfarm.net
greenstavern.com
guide4idiots.com
gyrostoyou.com
happycheftv.com
hauteandcood.com
healthy20.net
healyaanbieding.nl
heritagediscovery.net
heritageivhoa.com
hnzywjz.com
holdergear.com
holisticpacific.com
holofly.eu
hookup-vipclub2.com
houseof2.com
hspcon.com
hybridgroupco.com
ia801408.us.archive.org
icloudcs.in
identityofplace.com
imdead.kalscheur.info
issue72-paypal.com
jjauto.org
kbfvzoboss.bid
klinku.com
lacasadelosalebrijes.com
lanos.in
listbuildingonabudget.com
livinoutthedreamsco.com
lmaancha.co.il
lovewillfindaway.net
lownak.com
magianegramagiablancayamarres.com
manioscinetools.ga
manolab.in
masjidhabeebiyarazviya.mysunni.com
matruchhaya.co.in
maybethescobar.com
medimac.com.au
mersinchk.gov.tr
metabolytix.com
microsoftpods.com
middlehambooks.com
midollan.com
mirrorsmarbella.com
misaludsana.com
model-ing.hr
nashvillegems.com
neopivot.com
neverseenshop.com.mx
newtemplate.testingao.com
norastravel.com
northernlsx.com
nyariorganics.com
odgojnicentartk.ba
ohrchadash.com
okque.com
ombchardin.com
oouuweee.com
opentoronto.org
packtmall.com
pari1.jlddecora.com.br
pari2.jlddecora.com.br
pe-cr.com
personeltrainerbarnsley.com
phantomboxing.co.uk
podcastyourvote.com
prosupport.cl
protocolmodern.com
prueba2.adivertirse.com.mx
prueba.danielluza.com
pubgfrut.com
qzhongkong.com
repatriacioncolombia.com
restoremyorigin.com
retrievingbest.net
riceandginger.com
robertoconceicao.adv.br
royermaldonado.com
s2mmarketing.co.uk
sapanyc.com
sarakem.cl
satyagroup.co
searchkare.com
server.org
sgsnit.com
shops.myshopify.com
shpwmy.com
singlebarrel.net
smritiphotography.in
snowandmotion.com
springwellogistics.com
srubdomaspb.ru
stainlesslion.com
stemschool.net
suafrisolac.com
supportserverhotline23.info
swissbusinessacademy.xyz
tacademicos.com
tazakka.webane.com
tcesingur.com
team5thgroup.com
tententacleshydro.com
test.aflakshoes.ir
test.protocsconnectes.eu
test.studecademy.com
thecraftment.com
themodernspiritualgoddess.com
thepowersinyou.com
tinymodeldiana.com
tomasjehlicka.cz
translucent-hulking-son.glitch.me
tumharimaakachodamarunmain.blogspot.com
ugprs-ubih.org
unequaleducation.com
unlock-motorola.com
v-travelclub.com
villasoledadbeachresort.com
vio-enel.blogspot.com
vr.sorfozes.com
vuongcode.com
wbz.xyz
wealthtruckingco.com
woodandresin.club
wzocflfor.com
xyfs360.com
yaxett.net
yi-enel.blogspot.com
yowoit.com
yuksukcu.club
zahidibr.com
zhongsijiacheng.com

**Comment by scafroglia93** [comment]
100973671.review
algoritas.com
artebythesea.com
bizcert360.com
boiler-portal.com
colinboycemp.net
contecoliving.com
doctorsdietgulfport.com
esdras-almeida.com
fairisnotfair.com
frontrangetechnologies.com
gyrostoyou.com
holdergear.com
identityofplace.com
lownak.com
middlehambooks.com
midollan.com
mirrorsmarbella.com
nashvillegems.com
northernlsx.com
nyariorganics.com
oouuweee.com
podcastyourvote.com
qzhongkong.com
restoremyorigin.com
sgsnit.com
snowandmotion.com
tententacleshydro.com
thepowersinyou.com
wealthtruckingco.com
woodandresin.club

**Comment by scafroglia93** [comment]
done for submitting

**Comment by scafroglia93** [comment]
you can put inside your list

**Comment by scafroglia93** [comment]
Another list of ursnif ->
bricworld.it
brt-if.com
ricerco.org
surenoluneer.xyz
durenoluneer.xyz
turenoluneer.xyz
aurenoluneer.xyz
wurenoluneer.xyz

**Comment by notracking** [comment]
Thanks! Added to the custom list, changes will be visible after the next auto update.
