### ISSUE TITLE
[whitelist]  prodxnews1blob.blob.core.windows.net and get.x-link.pl 

### ISSUE THREAD

**Issue by FadeMind** [notracking/hosts-blocklists#553]
Hi
Please add to whitelist two domains
```
get.x-link.pl
prodxnews1blob.blob.core.windows.net
```
WHEN these domains are blocked video content on some polish sites with news cannot be played at all.

AFFECTED
All domains POLSKA PRESS GROUP. 
For example:
`naszemiasto.pl`

Example: https://koscierzyna.naszemiasto.pl/prokuratura-skierowala-do-sadu-wniosek-o-aresztowanie/ar/c1-8213337
Scroll down to player to see.
With unlocked domains play well:
![20210402-1617386698-001](https://user-images.githubusercontent.com/9846948/113441539-c0bc5680-93ee-11eb-8b81-9b271fccc1e0.png)

Regards

**Comment by notracking** [comment]
Thanks! Added to the whitelist, changes will be visible after the next auto update.
