### ISSUE TITLE
Additional file format for dnsmasq

### ISSUE THREAD

**Issue by don922** [notracking/hosts-blocklists#559]
I was looking for a blocklist for dnsmasq and found this site. It looks like a you have a large block list that is well maintained. Is it possible to add a new file format for dnsmasq? this one would have entries that have the following format.

server=/domainname/

this file would be added via the servers-list entry in the config file.

servers-file=/folder/folder/filename

This has two advantages over the current format that uses address=.

1. The server= entries will return nxdomain whereas the address=/domain/# entries return 0.0.0.0 or ::. According the the dnsmasq man page - _An address specified as '#' translates to the NULL address of 0.0.0.0 and its IPv6 equivalent of :: so --address=/example.com/# will return NULL addresses for example.com and its subdomains. This is partly syntactic sugar for --address=/example.com/0.0.0.0 and --address=/example.com/:: but is also more efficient than including both as separate configuration lines. Note that NULL addresses normally work in the same way as localhost, so beware that clients looking up these names are likely to end up talking to themselves._
2.  The file is re-read and the configuration therein is updated when dnsmasq receives SIGHUP. dnsmasq does not have to be restarted.

It appears that DNS lookups will take less time with server= entries as address= entries will get sent back to itself.

Thanks
Don

**Comment by notracking** [comment]
Since what version of dnsmasq is this supported?

**Comment by don922** [comment]
Hi,

I’m not sure. I know I’ve been using it for at least 3 years. The oldest reference I could find to it at https://thekelleys.org.uk/gitweb/?p=dnsmasq.git;a=log;pg=7 was 6 years ago. So it has been around for a while. It is not something new.

Don

**Comment by don922** [comment]
I wound up using sed also. I use the following commands:

/^#/d
s/address=/server=/
s/\/#/\//

I also use an adserver list from https://pgl.yoyo.org/adservers/serverlist.php?hostformat=dnsmasq-server&showintro=1&mimetype=plaintext and combine the two files using:

sort -u file1 file2 > output file

Many of the entries in the adserver file are not in the hosts-blocklist file so the combined file catches even more.

**Comment by nagisa** [comment]
Using `servers-file` is about 3 times more efficient compared to the `address` based approach. `addn-hosts` approach, OTOH, is many many more times more efficient than even that. [reference](https://www.reddit.com/r/sysadmin/comments/beqbcj/dnsmasq_is_very_slow_due_to_adblocking/)

**Comment by roobre** [comment]
+1 to `addn-hosts` approach. Extra config file using `address` causes my dnsmasq server to take ~10s to restart on a Celeron machine, with additional CPU spikes every now and then. Using `addn-hosts` startup time is less than 100ms.

Would it be possible to have a hosts version of https://github.com/notracking/hosts-blocklists/raw/master/dnsmasq/dnsmasq.blacklist.txt @notracking ? Sadly https://github.com/notracking/hosts-blocklists/raw/master/hostnames.txt does not allow this

**Comment by amano-kenji** [comment]
One critical flaw of `addn-hosts` is that it doesn't automatically block subdomains.

Thus, if a hosts file contains `googlesyndication.com`, the file doesn't block subdomains of `googlesyndication.com`.

Thus, I suggest `server` option is the best we have now.

**Comment by eggdropsoap** [comment]
`address=` with the `#` removed from the end also returns NXDOMAIN instead of 0.0.0.0, [per the man page](https://dnsmasq.org/docs/dnsmasq-man.html) (and confirmed by running some tests just now):

> **--address=/example.com/** is equivalent to **--server=/example.com/** and returns NXDOMAIN for example.com and all its subdomains.

I think changing the format of the modern dnsmasq file to just omit the trailing `#` would be an **easy, minimal change** for this project to implement.

I'll be using sed to remove the trailing hashes from my copy. I'd really prefer that my local network's devices not be chattering to themselves trying to GET dozens or hundreds of ad URLs from their port 80 every day—every drop of battery charge is precious, and some without batteries do have services trying to do useful work on 80 and shouldn't be spammed like that. 😊

**Comment by notracking** [comment]
I've updated the syntax by removing the tailing '#' as proposed by @eggdropsoap
Changes will be visible after the next update!
