### ISSUE TITLE
new list -> fakerando

### ISSUE THREAD

**Issue by SoftCreatR** [notracking/hosts-blocklists#560]
https://github.com/SoftCreatR/fakerando-domains

Contains more than 50.000 Domains of so called "Shadow websites" created by Takeaway.com / Lieferando (DACH) / Eat.ch / Thuisbezorgd.nl. Their purpose is to "mimic" the original restaurant's website to steal their customers or at least, gain from their orders.

More Info: https://github.com/SoftCreatR/fakerando-domains/blob/main/README.md

**Comment by notracking** [comment]
This is basically domain squatting. Though I agree that this is not a very healthy way to gain customers, I'm not sure if we should start added squatted domains. The list will in the end be multiple times larger for limited gain. These domains show only a direct link to takeaway etc..

**Comment by SoftCreatR** [comment]
> These domains show only a direct link to takeaway etc..

You are right. But that's new and not what it was, when I've created this list. Consider this as resolved for now.

**Comment by SoftCreatR** [comment]
Follow up: Here's an example reason for that list: https://www.pizzeriaraimondowiesbaden.de

**Comment by notracking** [comment]
This list is no longer being maintained.
