### ISSUE TITLE
unbound Feature 

### ISSUE THREAD

**Issue by gUstrx** [notracking/hosts-blocklists#561]
The new unbound function allows you to cut the block list in half

Unbound 1.13.1
Fix #397: [Feature request] add new type always_null to local-zone similar to always_nxdomain.

local-zone: "doubleclick.net" always_null

**Comment by notracking** [comment]
Thanks for the heads up, but Let's give this a bit of a grace period.. Will add this one.

**Comment by markster101** [comment]
For unbound best you can do is to publish RPZ files. This way the subscribers can set responses re: NXDOMAIN, or DROP in a config file. Also, with RPZ files Unbound takes less memory and it is more efficient to manage. You can enable or disable each zone separately. Check out my github for code to do the conversion and more.

**Comment by renaudallard** [comment]
You can also use something like `local-zone: "0--e.info" static` which will just return NXDOMAIN.

**Comment by Bundy01** [comment]
> You can also use something like local-zone: "0--e.info" static which will just return NXDOMAIN.

This method does not seem to work for subdomains.

**Comment by notracking** [comment]
Updated the format to ```local-zone: "0--0.ml." always_null``` Thanks all!
