### ISSUE TITLE
new list for flubot

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#563]
Source -> 
https://github.com/prodaft/malware-ioc/tree/master/FluBot

List -> 
https://raw.githubusercontent.com/prodaft/malware-ioc/master/FluBot/v3.7_5000_domain.txt
https://raw.githubusercontent.com/prodaft/malware-ioc/master/FluBot/v3.7_germany.txt
https://raw.githubusercontent.com/prodaft/malware-ioc/master/FluBot/v3.8_domains.txt
https://raw.githubusercontent.com/prodaft/malware-ioc/master/FluBot/v3.9_italy.txt

**Comment by notracking** [comment]
Not going to add these type of DGAs anymore, the lists will become way to heavy in comparison to the actual gains.
