### ISSUE TITLE
[whitelist] cdn.tinypass.com, experience.tinypass.com

### ISSUE THREAD

**Issue by gita6t5** [notracking/hosts-blocklists#565]
blocked video
https://www.auto-swiat.pl/wiadomosci/aktualnosci/volvo-xc40-p8-pierwsze-wrazenie/8xflhlz
https://www.przegladsportowy.pl/pilka-nozna/pko-ekstraklasa/jagiellonia-bialystok/wisla-plock-jagiellonia-bialystok-relacja-i-wynik-meczu-pko-ekstraklasy/txh9429
![Zrzut ekranu z 2021-04-18 19-46-52](https://user-images.githubusercontent.com/80338577/115155247-4b53b580-a07f-11eb-972e-6f2252ce8b70.png)

**Comment by notracking** [comment]
Thanks! Added to the whitelist, changes will be visible after the next auto update.
