### ISSUE TITLE
false positive: arkoselabs[.]com

### ISSUE THREAD

**Issue by hyder365** [notracking/hosts-blocklists#572]
I'm using the following list: https://raw.githubusercontent.com/notracking/hosts-blocklists/master/dns
crypt-proxy/dnscrypt-proxy.blacklist.txt

The domain "arkoselabs.com" is present in that file. Refusing to resolve it causes tinder.com to break.

To reproduce, go to tinder.com in a non-mobile web browser, click log in, and click log in with phone number. The resulting dialog never appears due to tinder-api.arkoselabs.com not loading. With that domain removed, it works again.

So please consider removing this domain.

**Comment by notracking** [comment]
Thanks! Added to the whitelist, changes will be visible after the next auto update.
