### ISSUE TITLE
Suspected Xiaomi false positive

### ISSUE THREAD

**Issue by Avamander** [notracking/hosts-blocklists#574]
It's very likely that `awsde0.fds.api.xiaomi.com` is being blocked incorrectly, it's required by Roborock vacuums to work properly. I can't see any other domain being blocked that would break this functionality.

**Comment by notracking** [comment]
Did you test this by locally removing it from the list?

**Comment by Avamander** [comment]
Actually I found that an another list blocked `api.xiaomi.com`, removing that made the subdomain resolve properly and things started working. Thanks for the quick response though.
