### ISSUE TITLE
redefine.hit.stat24.com

### ISSUE THREAD

**Issue by xMaap** [notracking/hosts-blocklists#577]
Blocked video
```
https://interwencja.polsatnews.pl/reportaz/2021-04-29/motocykle-i-halas-nielegalny-warsztat-za-oknami/
https://panstwowpanstwie.polsatnews.pl/odcinek/piec-aut-zniszczonych-w-karambolu-sprawczyni-bezkarna/
```
![Zrzut ekranu z 2021-04-29 22-22-20](https://user-images.githubusercontent.com/36385327/116613765-60f79380-a939-11eb-9cb9-ada4eca8457c.png)

**Comment by notracking** [comment]
Thanks! Added to the whitelist, changes will be visible after the next auto update.
