### ISSUE TITLE
Malware IoC (grab from my email honeypot)

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#578]
5daykitchen.contractors
7alwan.net
7brochasmagicas.com
238olive.com
4515a.com
100973671.review
a3pixels.com
accounts.mytaphouse.com
acuteceramic.in
africaelectronics.co.za
agnostec.com
akbuildersdelhi.com
akhbar-press.net
alainstud.com
albertsonsolutions.com
algoritas.com
alphabrainbalancing.com
alphastand.top
alphastand.trade
alphastand.win
amazontutoringcenter.com
amymako.com
anchalhospital.com
antibuildshop.com
apartmentsecurity.cf
api-ms.cobainaja.id
aplusa.me
aprilmarieclaire.com
areeba.eci7.com
armofmercy.com
artcode-software.com
artebythesea.com
astrologicsolutions.com
atc.iyclm.in
axolc-upoc.xyz
barryteeling.com
bastiontools.net
bbbsportscardz.com
beautiful.tours
beautyblvdca.com
beingthehands.com
benficalovers.com
bestfreedogtraining.com
betteringthehumanexperience.xyz
betyen1.com
bitsell.info
bizcert360.com
bizu.januarioadvocacia.com.br
bleepbloop.agency
blockly.com.br.evandrojunior.pro.br
blog.cebecitekstil.com
bloodtypealpha.com
bobydomain.com
boiler-portal.com
bonzacbdoil.com
brshahed.ir
businessquest.com.my
camaraitainopolis.pi.gov.br
candidanddevout.com
canyibang.com
care-match.com
carewatchsecuritybdi.com
carlitos.com.py
cartrade.co.za
cheap8x10s.com
chefbenhk.com
clg-eg.com
clickable.dwmarketing.us
climarosario.net.ar
codei10.com
codeproper.com
colinboycemp.net
combustibles.idubi.mx
constipationhub.com
constructionjadams.com
consultinggroupwv.com
contecoliving.com
contorig2.com
corporatebusinessmachines.co.in
cubectivel.com
cursosuaslp.com
customessayjojo.com
dangerouslyme.com
depositopalmeiras.com
designmakers.co.in
dgyzgs8.com
diasporalifedominicans.com
dietvex.xyz
diurr.com
doctorsdietgulfport.com
dogscanstay.com
dotgz.com
dueeffepromotion.com
eagle-family.co.uk
eastboundanddowntrucking.com
easytolovehardtodefine.com
ebmulla.com
elearn.scholarsmind.in
emotist.com
en.ioho.me
englishfastfun.com
enigmamedicalsolutions.co.uk
enterrasimonad.com
esdras-almeida.com
etforhartohat.info
ethyi.com
eventandcasino.com
everythingcornea.com
eyecambodia.com
fairchildconsultants.kindnesswrites.com
fairisnotfair.com
fakemoney.website
fangyu5827.com
farrellforcouncil.com
fibergourmetpasta.com
findsaloon.sistemasbrasilonline.com.br
finestfaux.com
fish-gear.com
fixarmobile.com
flawlessdrinking.com
flintjames.com
flyhightraveller.com
foxparanormal.com
frontrangetechnologies.com
fsmxmc.com
fuutu.com
gaminggalaxy.live
ganamcaters.in
gegepaa.com
gemtree.digitalnoirtest.net.au
giapankhang.website
giasigiare.com
giel.shop
gla-edu.com
globacity.my
goldbarrgifts.com
gospelofrecovery.com
gracetab.co.za
grandpaurbanfarm.net
graniterealestategroup.net
greatceremonies.in
grillomarketing.com
guardianangelgifttree.com
guide4idiots.com
gvsme.com
gyrostoyou.com
habitatmendoza.com
haichuanxin.com
halojabar.com
handhi.com
handicapvansnews.info
hazelautocars.co.za
healtybenenfitsplus.com
hello.glamfitters.com
hfhn.mvmms.in
hfrt.mvmms.in
holdergear.com
holidaybooking.mu
holytrinityschoolfoundation.com
hrmompm.com
idaka.co.id
identityofplace.com
iesatnchapter.com
imeraipur.com
influenciadoradesucesso.com
inov8digital.com
intelligentdesigncarpentry.com
intfoodservices.com
investmentfocused.com
iphonelcd-supplier.com
irocomps.co.za
issue72-paypal.com
itsquare.yrcreations.com
izmoo2-hoeiprotein-review.com
jkskylights.com
kbfvzoboss.bid
kidsreliefbags.com
kionline.net
kladki.com
kmatechnicalinno.innodaba.com
kn-security.com
ks6089.com
kumbrescr.webscript.co.in
labkitsforstudents.com
laidbackexcursions.com
lakidsacting.com
lankaplaza.com
laptopsservicecenter.in
leads-that-close.com
leehtourviagens.resultaweb.com.br
lifehakershagirl.online
livinoutthedreamsco.com
lock.omkarfatale.in
login.radikari.co.id
logowholesaler.com
lopva.com
lownak.com
lp-usti.cz
madustag.com
magistv.info
mail.168vitheyrealestate.com
mail.rigid-group.com
mailinno.com
maisondalbon.com
malaya.tv
mankarcrusher.webscript.co.in
medvows.com
megatasktechnologies.com
mejor-producto.com
melaniesalascosmetics.com
mentorbznes.com
mercontech.com
metropolis-roleplay.com
microsoftpods.com
middlehambooks.com
midollan.com
mikkelraunsgaard.dk
militar.januarioadvocacia.com.br
mirrorsmarbella.com
mitwpunwp.mitevents.org
mochila.punto99.website
monikagraphics.in
moodle.prepajilo.mx
mycrc.org
mymilld.com
namastecarrier.com
nashvillegems.com
natsturismo.resultaweb.com.br
nelivo.com
neopivot.com
nobrokerage.online
nocionlinguistica.xyz
nooitmeerblessures.be
northernlsx.com
nyariorganics.com
okque.com
old.leaderbed.fr
online-securegov.com
onlineerp.co.in
onyxcomputing.com
oouuweee.com
open.iyclm.in
organicwellnessfarm.com
orite.lk
packtmall.com
pais.realizartesublimacao.com.br
pano.digitalnoirtest.net.au
paragoncraftevents.com
partnerinyourprogress.com
patostpc.com
pawmawclaw.info
pehchaanlivefoundation.org
pemuda.suraunurulihsan.com.my
pensje.net
plgmap.com
pluxuryclothingboutique.com
pmsatostpc.com
podcastyourvote.com
ponderingelephant.com
preciousmemorabilia.com
printpix.lk
protocolmodern.com
pubgfrut.com
puredropwater.in
qgi1.com
qispiayway.com
qxr33qxr.com
qzhongkong.com
radiocanibal.com
rafbar.com
raiodesolexcursoes.resultaweb.com.br
reservesunbeds.com
restoremyorigin.com
revolutiontourselsalvador.com
rickyg.co.uk
riskmanagementnews.com
romanianpoints.com
romeroexcursoes.resultaweb.com.br
roopknits.com
royermaldonado.com
ryvpro.cl
safeairseal.com
saishaktipatholab.arogyapatholab.in
salondefilipina.com
sanacolitademarijuana.com
santoantoniodelisboa.pi.gov.br.planecomp.com.br
sapanyc.com
sapirdavid.com
sarojgotame.com.np
saveyourgrandchildren.com
scarabmag.com
sensationalcleaningservices.net
servermoov.e-mobiletech.com
sgsnit.com
sheeshamwoods.com
shell-core.com
shiftingbaba.com
shotsbynox.com
shpwmy.com
sierrainfraworks.com
singlebarrel.net
sistemapdv.sistemasbrasilonline.com.br
skatelife.net
skinfolabs.com
slingshotsmd.com
snowandmotion.com
sortl.in
stacyleets.com
statusking.droidiosking.com
studioeats.com
studiovelicham.com
supportserverhotline23.info
surveys-for-money.realcooltips.com
synergy.webscript.co.in
tampasports.net
tapalkoedacoffee.com
tashoku.com
tecnovalores.cl
tententacleshydro.com
terrasimonad.com
test.arogyapatholab.in
teste.omercadonovo.com
teteperformance.com
textdev.cyberbox-ph.com
thecityclub.co.in
thekiranastore.co.in
themoderncolonial.com
themodernspiritualgoddess.com
thepowersinyou.com
thuythuysanvertex.com
tinymodeldiana.com
tiptopvideo.in
travelomatix.co
trichocereususa.com
tstfrigo.com
turendong.com
turkeyvisa-government.com
tvonlinehd.com.br
twoworkers.com
ultimatepoolwater.com
umang.nciinfotech.in
unifipayments.com
universityrating.net
uq6eik5mo4.com
v-travelclub.com
valuedmind.com
vavadadoa3.com
veka-spb.com
vissito.com
vitabenanr.com
vitabenar.com
wealthtruckingco.com
whatsyourmedicine.org
whmznx.club
woodandresin.club
wzocflfor.com
xianqianbao99.com
xn--6j1bs50berk.com
xn--demirelik-u3a.com
xn--ekremimamolu-myb.com
xn--z4qm188e645c.com
xtrator.com
xwjhdjylqeypyltby.ml
yomeactivoxfasan.com
yourstoryplace.com
yowoit.com
zahidibr.com
zhaoshenggroup.com
zioninfosystems.net

**Comment by notracking** [comment]
Thanks! Added to the custom list, changes will be visible after the next auto update.

```Total number of unique filters: 284```
