### ISSUE TITLE
false positive: wire.com

### ISSUE THREAD

**Issue by ripply** [notracking/hosts-blocklists#580]
wire.com is an open source end to end encrypted chat application, the desktop, ios, android and server code are available on github
https://github.com/wireapp

these two domains that are blocked are required for the apps to function
prod-nginz-https.wire.com
prod-nginz-ssl.wire.com

teams.wire.com their enterprise solution, is also blocked
considering the entire application stack is open source its probably ok to unblock everything else, 
account.wire.com
clientblacklist.wire.com

their privacy policy is available here
https://wire.com/en/legal/#privacy

==========================
Our Privacy Commitment

Wire Swiss GmbH ("Wire" "we" "us"), as the responsible party within the meaning of data protection law, is committed to protecting your data. Wire does not rent or sell your data to third parties. Your data is also not used for targeted ads, or any other kind of profiling. This Privacy Policy informs you about how we process your data when you use the app offered by us and/or additional Wire products (together "Wire services") and what rights you have as a data subject towards us. Unless the context indicates otherwise, any reference to "you", "your" or "yourself" in this Privacy Policy includes the respective user of a team management functionality, the respective team admin and the respective team member of the Wire Services (as defined in our Terms of Use).

**Comment by notracking** [comment]
These are from the maltrail_malware list, I've whitelisted them (change will be visible after the next autoupdate.

Thanks for the report!
