### ISSUE TITLE
Phishtank

### ISSUE THREAD

**Issue by tg12** [notracking/hosts-blocklists#581]
If you want to include Phishtank I collate this information from the API. 

https://www.phishtank.com/

https://github.com/tg12/pihole-phishtank-list

**Comment by notracking** [comment]
Unfortunately that list is basically all hostnames extracted from a url based malware list. Their hostname list is a simple 1:1 extraction from the url list, leading to blocks like `doc.google.com` and an entire tdl `.br`. It does not really seem to be moderated well. Will not add.
