### ISSUE TITLE
[blocklist] malware IoC

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#583]
0055game.com
959tremont.com
admins-it.web.app
ansel-homebakery.com
appmc.servertrack.co
arrowbo.com
artinmemory.com
arvacol.com
asapdecor.com
auditionsuite.com
b15.robi2.hu
barkinlot.com
beta.auditionsuite.com
birzulova.com
blog.robi2.hu
bnctly.com
bohnke.nl
bronxantics.com
bullishsoftware.com
buyruon.com
chaytel.com
club-bergwerk.de
cosmicmtn.com
cron.altosaxplayer.com
custom.robi2.hu
d-art.club
desyrnan.com
development.sudburywebdesign.com
drunkpoetsociety.com
enpointe.online
essentiallygaia.com
ferienschweden.com
fpolishedpro.rheemwebsuite.com
fps2020dkasphotoop.com
fptplaybox.website
fuerzaagavera.com
geocache.altosaxplayer.com
gramosindia.com
hostbison.com
houseofsisson.com
instavcard.com
isastyles.com
ixiangzu.com
joysupermarket.com
kerneis.net
kissanime.press
kkkc5.com
knighttechinca.com
lacompagniadelfardello.com
lagrangewildliferemoval.com
ljd.xyz
m1.gameonlinefx2.com
m2.gameonlinefx31.com
mail.izmirfujitsuklimaservisi.com
makemyroom.design
mashroo3i.bh
mayhutchankhong.tv
mentalfreedom.guru
moderndatingcoach.com
mondaysmatters.com
mu-8.com
mujahidservice.online
myaustraliarewards.com
northsytyle.com
nugeneraonline.com
omsamedic.com
onlinehoortoestel.online
outletyana.com
oze-opole.pl
paulpoirier.com
peninsulamatchmakers.net
philreid4cc.com
poweringprogress.today
prestiged.net
privat-livecam.net
radioconexaoubermusic.com
redlightlegal.com
relocatingrealtor.com
rokitreach.com
rowquinte.ca
royalpropertiesgurugram.com
rvvikings.com
sarasvati-yoga.com
sardarfarm.com
schalke04rss.de
seaplanescenics.net
sectorulb.com
shitarpa.net
SiluetaSportsWear.com
sopplugin.com
soukid.com
spacekicker.com
spiritsoundart.net
stameco.com
static.danfosterdesign.co.uk
stroimdomsami.pp.ua
stylezbykay.com
theanimehat.com
umlausa.com
union-green.com
web-30181.web.app

**Comment by notracking** [comment]
Thanks! Added to the custom list, changes will be visible after the next auto update.
