### ISSUE TITLE
Cryptocurrency investment scam redirects

### ISSUE THREAD

**Issue by Avamander** [notracking/hosts-blocklists#585]
If you visit `https://www.hasadom1.com/2LGPHPX/L6ZB557/?sub2=286_15.212.239.184_1_14.50.209.153&sub3=226541581_3117270_3082` then the redirect path makes you visit `www.hasadom1.com`, `fnnt.co` and finally `bitcoincodeworld.com` investment scam page.

Up to you to decide if any of those domains deserve a block.

**Comment by notracking** [comment]
Thanks! Added `bitcoincodeworld.com` to the custom list, changes will be visible after the next auto update.
