### ISSUE TITLE
Please add support for repique

### ISSUE THREAD

**Issue by AZ-X** [notracking/hosts-blocklists#591]
duplicated closed issue:
https://github.com/notracking/hosts-blocklists/issues/518

**Comment by notracking** [comment]
Will not export in this format. 

You have a small user base and adding a different syntax will not get you any more or better coverage from this dnsfilter list. Most of the world is parsing hostname based lists and I recommend your dns solution to also support that simple (though not as theoretically perfect) solution, it will make your life a lot easier and you can support a lot of already existing lists without requesting custom exports.

**Comment by AZ-X** [comment]
Okey.
