### ISSUE TITLE
hostnames.txt with dnsmasq version > 2.80

### ISSUE THREAD

**Issue by mabod** [notracking/hosts-blocklists#596]
The instruction say that the the file `hostname.txt` should only be used with dnsmasq version < 2.80 : 
https://github.com/notracking/hosts-blocklists/wiki/Install-dnsmasq-(old:-pre-v2.80)

Why is that? I see that `hostnames.txt` is blocking more than just `domains.txt`. 

Example: `0.0.0.0.beeglivesex.com`

If I only use `domains.txt` this hostname gets resolved to 88.208.29.90 while with hostname.txt it is blocked as `127.0.0.1`

Why would I not want to use `hostnames.txt`  with newer versions of dnsmasq?

EDIT:
I am on EndeavourOS Linux with dnsmasq 2.85

**Comment by notracking** [comment]
For later versions of dnsmasq you should use this list: https://github.com/notracking/hosts-blocklists/blob/master/dnsmasq/dnsmasq.blacklist.txt with the `conf-file` setting in you dnsmasq configuration. It's a combined list (hostnames+domains) that will get you slightly better coverage as the old 2 lists individually.

The separate `hostnames.txt` and `domains.txt` are mostly there just for backwards compatibility and will be remove in the future.

**Comment by phu9Suop** [comment]
according man dnsmasq
 $0  -v     Dnsmasq Version 2.85  Copyright (c) 2000-2021 Simon Kelley

the conf-file setting makes it not read the default configuration
careful planning is requested
