### ISSUE TITLE
Blocked domain - www.actuabd.com

### ISSUE THREAD

**Issue by F4FPR** [notracking/hosts-blocklists#599]
Dear List Owner,

It seems the list is blocking the domain - www.actuabd.com
What is a legitimate website that talks about comics.

What is the reason for its blocking and its presence in the list?

Can it be unlocked soon?

Thanks in advance.

**Comment by notracking** [comment]
Thanks! This on was blocked by wally. Added to the whitelist, changes will be visible after the next auto update.
