### ISSUE TITLE
Not blocking everything?

### ISSUE THREAD

**Issue by xreeckz** [notracking/hosts-blocklists#6]
Hey,

I've noticed that after applying these to my dns server that it's not blocking a lot of youtube ads and it also breaks log-in through facebook. 

Great work though and thank you so much for maintaining it!

**Comment by notracking** [comment]
Hi there!

Thanks for the feedback. Unfortunately lately not all Youtube ads are blockable anymore using only DNS filters alone. I can recommend using uBlock Origin as a addition to your dns blackhole.

In regard of the Facebook logins, can you give me a more specific example? People are using Facebook on my network and I never had complaints from them.

Thank you.

**Comment by notracking** [comment]
Please create a new ticket if you are still encountering issues with logging in to Facebook.
