### ISSUE TITLE
youtube ads list

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#601]
Source ->
https://raw.githubusercontent.com/kboghdady/youTube_ads_4_pi-hole/master/black.list

**Comment by HellboyPI** [comment]
Such youtube ads block lists are **not** good. To many false positives.
There has been a huge discussion over on pihole forum about this.
[Link](https://discourse.pi-hole.net/t/how-do-i-block-ads-on-youtube/253)

The conclusion is (quote): 
_"It's not likely that you'll be able to block in-video ads with Pi-hole. For that, you'll need something like uBlock origin for desktop, or vanced for android, This thread has been closed as there is not much more discussion to be had around the topic."_

**Comment by scafroglia93** [comment]
Ok, thanks for the feedback
