### ISSUE TITLE
New

### ISSUE THREAD

**Issue by Fede-z8na** [notracking/hosts-blocklists#605]
Tracker from Aqara Home App
datasink.aqara.cn

Tracker from Torrent
tracker.pirateparty.gr
tracker.coppersurfer.tk
tracker.zer0day.to
tracker.leechers-paradise.org
atrack.pow7.com
tracker.appdn.net
p4p.arenabg.com
tracker.openbittorrent.com
tracker.bittorrent.am
tracker.filetracker.pl
tracker.ilibr.org
tracker4.piratux.com
open.acgtracker.com
tracker.dler.org
tracker2.itzmx.com
tracker.neodatagroup.com
bt.xxx-tracker.com

**Comment by notracking** [comment]
No, these are legit torrent trackers will not add.
