### ISSUE TITLE
bad name

### ISSUE THREAD

**Issue by Mausy5043** [notracking/hosts-blocklists#61]
`dnsmasq` complains:
```
dnsmasq:: bad name at /usr/local/etc/dnsmasq.d/hostnames.txt line 75267
dnsmasq:: bad name at /usr/local/etc/dnsmasq.d/hostnames.txt line 75268
```

~~I've_ inspected the file, but can find no problems.~~

**Comment by cbuijs** [comment]
@Mausy5043 Looks like DNSMasq runs out of memory, seen this before when using large lists. Try to remove all IPv6 entries (lines starting with "`::`"), to "half" the list and try again.

**Comment by Mausy5043** [comment]
@cbuijs I'm sorry: I had already kind of concluded that that was **not** the problem. Mainly because I hid (😁 ) another line from the log from you : `dnsmasq:: read /usr/local/etc/dnsmasq.d/hostnames.list - 77148 addresses` which suggested to me that it read everything else. And I've used much, much larger lists in the past on my firewall.
Also I have 6GB of free memory out of 8GB. So, out-of-memory issues where not at the top of my list.

It then occurred to me that `dnsmasq` probably doesn't count the first 15 commented lines. And behold, 15 lines down I find:
```
0.0.0.0 www.turkishạirlines.com
:: www.turkishạirlinesst.com
```

Note two things here:
  - First, that the `a` of "airlines" is a diacritic (that is BTW a translation-artifact from the copy-&-paste process; the actual character is a Unicode one. Please check the source doc to see for yourself). I have seen in the past that characters beyond ASCII 127, Unicode or multi-byte characters in a textfile are poorly understood by `dnsmasq`.
  - And second, that the second line is different from the first. It shouldn't be. Assuming that @notracking  uses code that just copies the first line and replaces the "0.0.0.0" by "::". That suggests to me that the text got garbled due to badly understood/interpreted charactercodes in the file while I was editing it with `nano` to copy out those lines.

Anyway, there's your culprit.

**Comment by cbuijs** [comment]
@Mausy5043 

Ah!

So old fashioned [homograph](https://en.wikipedia.org/wiki/IDN_homograph_attack) attack. Good finding!

Problem is that in HOST files used for DNS purposes (as with DNSMasq), unicode is a no-no. Should be [punycoded](https://en.wikipedia.org/wiki/Punycode) (xn-- format) instead to support [IDN](https://en.wikipedia.org/wiki/Internationalized_domain_name) (allowing for diacritics). 

Note that HOST files when used by the OS/System are fine using unicode, as it is "DNS" that needs resolution of IDN.

Might want the DNSMasq guy to support unicode in HOSTS files and "translate" on the fly during DNS resolution or something.

It is becoming more and more an issue (Steven Black HOSTS files have similar issues reading from sources).

**Comment by Mausy5043** [comment]
I'll see if I can get a parser together in Python and stick that in the downloadscript.

**Comment by notracking** [comment]
Since this is a recurring topic, I've scripted a solution for this in the list updater using a tool named 'idn2'.
This has a nice side effect that it will also filter any illegal hostnames that have for example more than 63 chars in a section.

For your reference, my code section. I'm reading the source file line by line, because idn2 will quit without any output as soon as its found a errornious hostname.

`
while IFS= read -r line; do
  echo $line |idn2 >> $tempdir/hostnames.puny.txt
done < $tempdir/hostnames.txt
cp $tempdir/hostnames.puny.txt $tempdir/hostnames.txt
`
Now running the tests for release; if everything goes according to plan the changes should be visible with the next auto update.

**Comment by notracking** [comment]
No issues with the test runs, closing ticket. Thanks you all for the support!

**Comment by funilrys** [comment]
Hi there,
If someone want to convert them I wrote https://github.com/funilrys/domain2idna ...

Cheers,
