### ISSUE TITLE
[ Threat Intelligence] HP Threat Research -> CryptBot

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#610]
Source ->
https://raw.githubusercontent.com/hpthreatresearch/iocs/main/CryptBot/domains.txt

**Comment by notracking** [comment]
I think that these are very short lived, none of them seem to resolve. Will not add this one as it would not add anything effectively.

**Comment by notracking** [comment]
Should add that the domains that are still valid are already covered via other lists.
