### ISSUE TITLE
[Threat Intelligence] Palo Alto Unit42 SilverTerrier (Nigerian Email Scam)

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#613]
Born from the separation of the main list in order to simplify management and improve any debugging

It was already there but, I removed the domains

Source -> 
https://raw.githubusercontent.com/scafroglia93/blocklists/master/blocklists-unit42-silverterrier.txt

**Comment by notracking** [comment]
@scafroglia93 A lot of unique entries, but only ~10% is still alive/registered. I will include it for now. In a couple of days you could use the [dead domain list](https://github.com/notracking/hosts-blocklists-scripts/blob/master/hostnames.dead.txt) to moderate your list by removing the unregistered domains? (Would be appreciated as it would reduce the load on my databases/scripts).
