### ISSUE TITLE
[Threat Intelligence] Palo Alto Unit42 Playbook

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#614]
This list gathers all the apt threats collected by unit42 (palo alto networks)

Source ->
https://raw.githubusercontent.com/scafroglia93/blocklists/master/blocklists-unit42-playbook.txt

**Comment by notracking** [comment]
@scafroglia93  Added, thanks! (please double check: `ztm.waw.pl` as it's marked in the whitelist)
