### ISSUE TITLE
[Threat Intelligence] blocklists-personal

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#615]
This list collects the domains that I collect within the company where I work through email, viruses and other malicious software

Source -> 
https://raw.githubusercontent.com/scafroglia93/blocklists/master/blocklists-personal.txt

**Comment by notracking** [comment]
Excellent list again! Added, will be merged with the next autoupdate.

```
[+] Total number of filters in original list: 655
[+] Total number of dupes with notracking list (including dead lists): 191
[+] Total number of unique filters: 464
```
