### ISSUE TITLE
release auto-update script?

### ISSUE THREAD

**Issue by craftyguy** [notracking/hosts-blocklists#62]
Would you mind making the script you use for auto-updating available for others to use? I would like to expand on this project some and be more aggressive in blocking domains that you have whitelisted (e.g. facebook).

**Comment by mister2d** [comment]
This is a simple script I came up with on my CentOS 7 box.
Just put the script inside of one of your cron folders. I inserted mine into `/etc/cron.weekly`.

```
#!/bin/bash

curl https://raw.githubusercontent.com/notracking/hosts-blocklists/master/domains.txt > /etc/dnsmasq-blocklist-domains.txt && \

curl https://raw.githubusercontent.com/notracking/hosts-blocklists/master/hostnames.txt > /etc/dnsmasq-blocklist-hostnames.txt && \

systemctl restart dnsmasq
```

**Comment by craftyguy** [comment]
Ah, no, I mean the script that the author is using to make daily updates to this repo, that is assembling the `hostname.txt` and `domain.txt` files here.. I'm assuming @notracking is not manually creating these files every day manually and pushing them but is using a script...

**Comment by mister2d** [comment]
I see. Sorry for the misunderstanding.

**Comment by Mausy5043** [comment]
From a purely academic perspective I too am very interested in the sources used to create these lists. But I assume they have not been released for good reasons.

@craftyguy : You might want to take a look at my [USS Cygnus repo](https://github.com/Mausy5043/USS_Cygnus).  
The `freebsd` branch hasn't seen some work for the last few weeks. It's what I used before I discovered this repo. 😉 I don't want to pretend completeness or fitness for use. But you might find it helpful if you need a springboard.  
The `OPNsense` branch "just" downloads and installs the lists from this repo.  
The `master` branch is a really old development version of what I used when I still had a [Pi-hole](https://pi-hole.net/), hence the repo's name.

**Comment by craftyguy** [comment]
> But I assume they have not been released for good reasons.

Any reasons I can think of for refusing to release the sources for the script(s) are big red flags indicating these lists cannot be trusted :stuck_out_tongue: 

Hopefully I am wrong though, and these can be provided!

**Comment by brass37** [comment]
Please Add to notracking:  
gshort.click
ibb.co
juos.site
to the block list.  hundreds of tracking pixels hosted on them have been posted in dozens of discussion forums found in past month.

**Comment by craftyguy** [comment]
that's unfortunate.
