### ISSUE TITLE
new list -> phishing -> SecureReload

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#620]
Source ->
https://securereload.tech/
https://securereload.tech/Phishing/Lists/

Source ->
https://securereload.tech/Phishing/Lists/Latest/

**Comment by notracking** [comment]
Some very nice entries in these, but completely wack in regard of how they are generating/formatting their lists. This would require a completely custom parser which I will not implement for this provider. You might want to ask the to generate a combined hostname based list and resubmit if this is available.
