### ISSUE TITLE
new list -> REvil Domain (nextdns)

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#630]
new list ->

Source ->
https://github.com/nextdns/metadata/commit/f274573df362cf8e222506368dd1d2917b3bb186

https://gist.githubusercontent.com/romaincointepas/b9b8990ee824b013125d87d1ab1f8944/raw/e369597ce9f93b3fb4ce465c03c0f505cc11d8d5/REvil%2520potential%2520C2%2520domains

**Comment by notracking** [comment]
Has a bit too many false calls. There are a lot of smaller websites in this list, that are likely being hacked at some point in time, but not removed again once the infection has been removed..
