### ISSUE TITLE
Pegasus spyware hosts

### ISSUE THREAD

**Issue by Avamander** [notracking/hosts-blocklists#633]
Amnesty international released a list of domains related to NSO Group's Pegasus, it would probably be nice to block any known ones still registered.

https://www.amnesty.org/en/latest/research/2021/07/forensic-methodology-report-how-to-catch-nso-groups-pegasus/

**Comment by stavitian** [comment]
https://github.com/0n1cOn3/nso-blacklist/blob/main/hosts.txt

the full list

**Comment by notracking** [comment]
The official Amnesty hosts are already covered via other malware lists. I will not add the 2nd one because it's blocking cloudfront.net.
