### ISSUE TITLE
Bootstrap CDN Blocked

### ISSUE THREAD

**Issue by jeremybuff** [notracking/hosts-blocklists#636]
A recent update blocked stackpath.bootstrapcdn.com. This domain shouldn't be blocked because so many website use it as a CDN for the Bootstrap frontend framework.

**Comment by notracking** [comment]
Thanks! Added to the whitelist. @scafroglia93 this is on your personal list.
Will also push this update as it might be a high impact one.

**Comment by scafroglia93** [comment]
fixed
