### ISSUE TITLE
false positive (important)

### ISSUE THREAD

**Issue by saurane** [notracking/hosts-blocklists#637]
This is required to watch tv live broadcasts. If you block this, you will not be able to watch the live broadcast.
Please remove from list. "" ipcheck.tmgrup.com.tr ""
Live broadcast address: https://www.atv.com.tr/canli-yayin

Available on these lists: 1Hosts, Energized, AdGuard tracking protection filter, AdGuard DNS filter, Goodbyads, notracking, oisd

**Comment by notracking** [comment]
Thanks! Added to the whitelist, changes will be visible after the next auto update.
