### ISSUE TITLE
WindowsSpyBlocker

### ISSUE THREAD

**Issue by dartsmaster** [notracking/hosts-blocklists#638]
Thanks for making this excellent DNS blocklist. Would you consider adding https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt to your list. The main repository explains its purpose: https://github.com/crazy-max/WindowsSpyBlocker

**Comment by notracking** [comment]
Thank you for your submission, but this one was already checked before (and it did not make it in), see: https://raw.githubusercontent.com/notracking/hosts-blocklists/master/EXCLUDED.md
