### ISSUE TITLE
new list -> blocklists-malware-traffic

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#642]
Source ->
https://raw.githubusercontent.com/scafroglia93/blocklists/master/blocklists-malware-traffic.txt

Given the amount of feeds I decided to create a spinoff from the source.

The part of malware-traffic present in blocklists-main will be migrated to this

Thanks,
Lorenzo

**Comment by notracking** [comment]
Awesome! will add this one :) :+1:
