### ISSUE TITLE
sdk-statistics.abbyy.com

### ISSUE THREAD

**Issue by user8446** [notracking/hosts-blocklists#643]
Hello,

ABBYY mobile scanning app is hitting this domain for analytics/tracking. Please add to your list, thank you!

**Comment by notracking** [comment]
Thanks! Added to the custom list, changes will be visible after the next auto update.

**Comment by user8446** [comment]
Thank you... I just sent you a coffee (or beer!) as well

**Comment by notracking** [comment]
Thanks, much appreciated!!
