### ISSUE TITLE
Required for Cookies: cdn.privacy-mgmt.com

### ISSUE THREAD

**Issue by Zelo72** [notracking/hosts-blocklists#645]
Hi,

cdn.privacy-mgmt.com is required on several pages to accept cookies.

See also: https://github.com/AdguardTeam/AdguardFilters/blob/master/AnnoyancesFilter/sections/cookies_whitelist.txt

Greetings,
Gerd

**Comment by notracking** [comment]
Thanks! Added to the whitelist, changes will be visible after the next auto update.
