### ISSUE TITLE
Required for playing Videos: player-feedback-v1.glomex.com

### ISSUE THREAD

**Issue by Zelo72** [notracking/hosts-blocklists#646]
Hi, 

player-feedback-v1.glomex.com required for playing Videos in the Glomex-Player (player.glomex.com) on various sites.

See also: https://github.com/AdguardTeam/AdguardFilters/blob/master/SpywareFilter/sections/whitelist.txt

Regards,
Gerd

**Comment by notracking** [comment]
`glomex.com` is still blocked on the Adguard team tracking servers list.
Added to the whitelist, changes will be visible after the next auto update.
