### ISSUE TITLE
n-tv.de: videos and live streaming

### ISSUE THREAD

**Issue by Zelo72** [notracking/hosts-blocklists#647]
Hi,

videos and the livestream on n-tv.de show a black screen if the following domains are blocked:

*.damoh.n-tv.de
*.ntvde.damoh.schneevonmorgen.com

_(1.ntvde.damoh.schneevonmorgen.com
2.ntvde.damoh.schneevonmorgen.com
ssl.1.damoh.n-tv.de
ssl.2.damoh.n-tv.de)_

https://www.n-tv.de/mediathek/livestream/24-Stunden-ntv-Livestream-article9511936.html

Regards,
Gerd

**Comment by notracking** [comment]
I cannot find anything blocking `damoh.n-tv.de`, maybe you get a different cname for that one? (you can always check with `dig` under linux)

`*.damoh.schneevonmorgen.com` is now whitelisted, thanks for your feedback!
