### ISSUE TITLE
New spyware domain

### ISSUE THREAD

**Issue by DavidOsipov** [notracking/hosts-blocklists#651]
Hello! A Russian guy posted an article on a huge IT resource, where he found out that the domain **mgs123.com** is responsible for receiving secretly gathered information from DEXP mobile phones (not smartphones). The article is published [here ](https://habr.com/ru/post/575626/)

Could I ask you to add the domain  **mgs123.com** to notracking lists?

**Comment by notracking** [comment]
Thanks! Added to the custom list, changes will be visible after the next auto update.
