### ISSUE TITLE
tracker.cyber-hub.net [false positive]

### ISSUE THREAD

**Issue by 3xploiton3** [notracking/hosts-blocklists#652]
tracker.cyber-hub.net

its good tracker torrent site

**Comment by notracking** [comment]
Thanks! Added to the whitelist, changes will be visible after the next auto update.

**Comment by 3xploiton3** [comment]
![image](https://user-images.githubusercontent.com/19517680/133161090-5ea087c4-d24c-4535-b00d-36643f3e302c.png)

for how long?

**Comment by notracking** [comment]
`cyber-hub.net` was also blocked. Added to the whitelist, changes will be visible after the next auto update.
