### ISSUE TITLE
Android TV ad domain

### ISSUE THREAD

**Issue by user8446** [notracking/hosts-blocklists#655]
Hello,

Android TV is pulling ads from these domains:

androidtvchannels-pa.googleapis.com
androidtvwatsonfe-pa.googleapis.com

that many are complaining about: https://www.nvidia.com/en-us/geforce/forums/shield-tv/9/458562/remove-the-new-ads-on-the-home-screen/

**Comment by notracking** [comment]
Did you test if nothing else breaks when blocking these? I cannot validate as I do not own a shield.

**Comment by user8446** [comment]
Yes, everything is working as expected on my Nvidia Shield. If you want, I can let it go a week.

**Comment by notracking** [comment]
Let's give it a go! Added to the custom list, changes will be visible after the next auto update.

**Comment by user8446** [comment]
Ok and I have confirmed everything is still working as expected
