### ISSUE TITLE
cdn.cookielaw.org

### ISSUE THREAD

**Issue by gita6t5** [notracking/hosts-blocklists#658]
Blocked video
`https://www.sport.pl/pilka/7,65080,27588965,kosmiczny-samochod-cristiano-ronaldo-jest-warty-fortune.html#do_w=107&do_v=314&do_st=RS&do_sid=677&do_a=677&s=SMT_Img_2`

**Comment by notracking** [comment]
Thanks! Added to the whitelist, changes will be visible after the next auto update.
