### ISSUE TITLE
new list - my blacklist

### ISSUE THREAD

**Issue by Zelo72** [notracking/hosts-blocklists#661]
Hi,

if the list meets your requirements please check my personal blacklist and add if necessary. I make sure that this list does not contain any false positive domains. It will be extended and updated regularly. The list blocks ads, tracking, telemetry, metrics and more.

Blocklist formats:

Domains - https://raw.githubusercontent.com/Zelo72/rpi/master/pihole/blocklists/personal.txt

Hosts - https://raw.githubusercontent.com/Zelo72/hosts/main/personal.txt

AdBlock/AdGuard - https://raw.githubusercontent.com/Zelo72/adguard/main/personal.adblock

Thanks and greets,
Gerd

**Comment by notracking** [comment]
Why did you close it, something not ok? I will make time to check it, but adding new lists requires some extra work from my side, which is a bit difficult at this moment due to personal priorities.

**Comment by Zelo72** [comment]
Thank you, that would be great.

**Comment by notracking** [comment]
Took me some time, but I managed to check it out. It's good to see that you are still actively maintaining your list, thanks!

Roughly 15k unique hosts added, with almost no whitelist hits and a very high score on active (non-dead) hosts.

notracking will now also track you list, thank you sir!
