### ISSUE TITLE
lib.onet.pl

### ISSUE THREAD

**Issue by gita6t5** [notracking/hosts-blocklists#665]
this domain blocks forms
https://www.medonet.pl/kalkulatory,odczuwasz-niepokojace-objawy--wykonaj-krotki-wywiad-medyczny-i-sprawdz-swoj-stan-zdrowia,artykul,96910898.html
![Zrzut ekranu z 2021-09-28 07-16-12](https://user-images.githubusercontent.com/80338577/135027439-8dba4065-f0d5-4dab-b480-4b7154453467.png)

**Comment by notracking** [comment]
Thanks! Added to the whitelist, changes will be visible after the next auto update.
