### ISSUE TITLE
Blocking Dropbox, Onedrive, et al

### ISSUE THREAD

**Issue by MarkoBL** [notracking/hosts-blocklists#682]
Hi,

sorry for 'hijacking' this bugtracker. I'm using the blocklist now for a few month and it's amazing. I can't live without it anymore :) Thanks to the author and all the contributors. Maybe, you can help me in this case.

I have a problem: some of our employees are going frenzy and use their private online drives (dropbox, onedrive, ...) to save confidential data and share it with others or work at home. And they use their private mail accounts to bypass our mailserver and spam filter.

Now, my question: Do you know any blocklist that targets all these online drives and/or web mail accounts?

Any help is welcome.

**Comment by notracking** [comment]
Thanks.

Likely you will find some maintainer that keeps such list, duckduckgo is your friend ;)
Personally I cannot recommend you any as I don't have the need for filters like that.
