### ISSUE TITLE
airvpn list

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#688]
Ads & Trackers Blocklist ->
https://airvpn.org/api/dns_lists/?code=air_ads&block=0.0.0.0&style=domains

Malware, phishing, botnet->
https://airvpn.org/api/dns_lists/?code=air_malware&block=0.0.0.0&style=domains

Cryptojacking->
https://airvpn.org/api/dns_lists/?code=air_cryptojacking&block=0.0.0.0&style=domains

**Comment by notracking** [comment]
https://airvpn.org/api/dns_lists/?code=air_ads&block=0.0.0.0&style=domains #too many false positives
https://airvpn.org/api/dns_lists/?code=air_malware&block=0.0.0.0&style=domains #too many false positives
https://airvpn.org/api/dns_lists/?code=air_cryptojacking&block=0.0.0.0&style=domains #also includes legit mining pools
