### ISSUE TITLE
zscaler.com in domains.txt is a False Positive

### ISSUE THREAD

**Issue by naturalpb** [notracking/hosts-blocklists#689]
This morning, zscaler.com appeared in domains.txt. They are a commercial secure web gateway used by many companies and should not be blocked. I'm not sure which of the 113 sources added it, but this entry needs to be removed.

Interestingly, you use Zscaler's malware list as a source yourself: https://raw.githubusercontent.com/scafroglia93/blocklists/master/blocklists-zscaler.txt

**Comment by notracking** [comment]
Thanks! Added to the whitelist, changes will be visible after the next auto update.
