### ISSUE TITLE
piano.io

### ISSUE THREAD

**Issue by gita6t5** [notracking/hosts-blocklists#690]
Blocks article content
https://www.komputerswiat.pl/recenzje/sprzet/komponenty-pc/test-intel-core-i5-12600k-i-core-i9-12900k-intel-znow-na-szczycie-wydajnosci/hgx0x2p
![Zrzut ekranu z 2021-11-06 15-53-44](https://user-images.githubusercontent.com/80338577/140613932-69418bb6-6430-4ac1-81d7-2f99bd768f3c.png)
![Zrzut ekranu z 2021-11-06 15-54-31](https://user-images.githubusercontent.com/80338577/140613934-c7e40908-c12e-4395-ba74-9c551d7b04c4.png)

**Comment by notracking** [comment]
Thanks! Added to the whitelist, changes will be visible after the next auto update.
