### ISSUE TITLE
tenforums.com

### ISSUE THREAD

**Issue by RudyMas** [notracking/hosts-blocklists#70]
I'm not sure if I need to report this here, but I was wondering why tenforums.com has been added to the domains.txt file.

I visit this forum a lot to find information about Windows 10. Plus, it's also a great forum when you need support with a problem.

Best regards,
Rudy Mas

**Comment by notracking** [comment]
I fully agree, this does not belong in the blocklists. I've added it to the white list, changes will be visible with the next auto update.

Thanks for submitting this issue!
