### ISSUE TITLE
dailymotion.com showing white page

### ISSUE THREAD

**Issue by gita6t5** [notracking/hosts-blocklists#703]
![Zrzut ekranu z 2021-12-12 21-26-49](https://user-images.githubusercontent.com/80338577/145728470-b9b98aa5-38e5-44be-946a-0cc79ae256d9.png)

Whitelist:
`vendorlist.dmcdn.net`

**Comment by notracking** [comment]
Thanks! Added to the whitelist, changes will be visible after the next auto update.
