### ISSUE TITLE
blocked site, needs to be removed

### ISSUE THREAD

**Issue by heatina** [notracking/hosts-blocklists#707]
godlikeproductions.com is on the list and is a good source of information which is relied upon in times of our censored internet.
This site, although including a lot of anon contributors, does have good intel.
Please consider removing this from the blocklist.
Thanks.
p.s. if I have not requested this in the usual way, please excuse me.

**Comment by notracking** [comment]
Thanks! Added to the whitelist, changes will be visible after the next auto update.
