### ISSUE TITLE
How do I enable these configs on Ubuntu 16.04 where dnsmasq is managed by NetworkManager ?

### ISSUE THREAD

**Issue by unoexperto** [notracking/hosts-blocklists#71]
How do I enable these configs on Ubuntu 16.04 where dnsmasq is managed by NetworkManager ?

I tried creating `/etc/NetworkManager/dnsmasq.d/dnsmasq.conf` with two lines you specified in readme but it doesn't seem to help.

Thanks!

**Comment by notracking** [comment]
I'm not familiair with Ubuntu, nor its network manager. However I've had a Debian install that also used a Network Manager and that was kind of a pain to get dnsmasq to behave in a way I wanted. I ended up installing dnsmasq seperately.

But before you have to go that far, can you give me some info I might be able to guide you in the right direction? It would be helpfull (I guess) to create a Ubuntu specific toturial for this in the end..

Run the following commands and post the output here:
```sudo updatedb; locate dnsmasq.conf```
```ps aux  |grep dnsmasq```
```sudo service dnsmasq status```

**Comment by notracking** [comment]
Missing info.
