### ISSUE TITLE
tl88.net

### ISSUE THREAD

**Issue by ccyykkcyk** [notracking/hosts-blocklists#714]
I can't open some website like [docs.microsoft.com](docs.microsoft.com) and [www.dell.com](www.dell.com) with this rule ``||tl88.net`` because of the cname record in china.
It is a china cdn.

> ; <<>> DiG 9.16.20 <<>> docs.microsoft.com
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 28683
> ;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 0
> 
> ;; QUESTION SECTION:
> ;docs.microsoft.com.            IN      A
> 
> ;; ANSWER SECTION:
> docs.microsoft.com.     1       IN      CNAME   docs.microsoft.com-c.edgekey.net.
> docs.microsoft.com-c.edgekey.net. 1 IN  CNAME   docs.microsoft.com-c.edgekey.net.globalredir.akadns.net.
> docs.microsoft.com-c.edgekey.net.globalredir.akadns.net. 1 IN CNAME e13630.ca2.s.tl88.net.
> e13630.ca2.s.tl88.net.  1       IN      A       61.147.221.186
> 
> ;; Query time: 15 msec
> ;; SERVER: 223.5.5.5#53(223.5.5.5)
> ;; WHEN: Wed Dec 22 22:32:58 ;; MSG SIZE  rcvd: 196

**Comment by notracking** [comment]
Thanks! Added to the whitelist, changes will be visible after the next auto update.
