### ISSUE TITLE
Samsung smart TV apps

### ISSUE THREAD

**Issue by alberanid** [notracking/hosts-blocklists#717]
Hi,
I'm using the dnsmasq blocklist and my 2019 Samsung smart TV is unable to install new apps or update existing ones.

To enable this feature again I had to remove:
```
samsungqbe.com # for osb-apps.samsungqbe.com
oempprd.samsungcloudsolution.com
samsungcloudsolution.net
notice.samsungcloudsolution.com
d1oxlq5h9kq8q5.cloudfront.net
```

I may have had remove a little too much: testing is a bit tedious, since you have to physically unplug the TV (due to aggressive caching, I guess).

The last domain (d1oxlq5h9kq8q5.cloudfront.net) is especially troublesome since I assume it may change. Or maybe not: in the last ten days the only other blocked subdomain of cloudfront.net was d2uap9jskdzp2.cloudfront.net, on my home network.

Thanks for the great project!

**Comment by alberanid** [comment]
I've noticed that it also needs `sas.samsungcloudsolution.com` to be able to do search for new apps and install them.

**Comment by notracking** [comment]
Whitelisted: `samsungcloudsolution.com,sas.samsungcloudsolution.com,samsungqbe.com` should be fine with these (cloudfront one was already removed).
