### ISSUE TITLE
[threat intelligence] unc1878 domains (CERT-GEORGIA)

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#719]
Source ->
http://blacklists.cert.gov.ge/

Source1 ->
https://www.trusted-introducer.org/directory/teams/cert-ge.html

Lists ->
http://blacklists.cert.gov.ge/unc1878_domains.txt

**Comment by notracking** [comment]
Server is timing out..

**Comment by notracking** [comment]
Still timing out, they should fix their server issues.
