### ISSUE TITLE
Don't necessarily agree with blocking kijiji.ca | kijiji.com

### ISSUE THREAD

**Issue by altmoola** [notracking/hosts-blocklists#72]
This is essentially the equivalent of blocking ebay.ca for Canadians. I do understand that kijiji serves ads so it's sort of a tough one.

**Comment by notracking** [comment]
I think that these domains are relatively safe to whitelist. They only appear in the Shalla list.
I've added them, changes will be visible with the next auto update.

Thanks for the feedback!
