### ISSUE TITLE
BetterDiscord + DevilBro's Repos

### ISSUE THREAD

**Issue by Greigh** [notracking/hosts-blocklists#722]
I can't figure out which domain is blocking them but the blocklist is not allowing these to update or connect to the update URLs. I have looked through the source code of all of it and can't figure out a URL that it's blocking.

### BetterDiscord
https://betterdiscord.app/
GitHub: https://github.com/BetterDiscord/BetterDiscord

### BetterDiscord Plugin and Theme Repos
https://betterdiscord.app/plugin/PluginRepo
GitHub: https://github.com/mwittrien/BetterDiscordAddons/tree/48fd20a04e640adcf58e43f2cda334e3cb8526a1/Plugins/PluginRepo
https://betterdiscord.app/plugin/ThemeRepo
GitHub: https://github.com/mwittrien/BetterDiscordAddons/blob/48fd20a04e640adcf58e43f2cda334e3cb8526a1/Plugins/ThemeRepo/ThemeRepo.plugin.js

**Comment by notracking** [comment]
It might be more convenient to check you dns logs instead; I do not use this application to test.

**Comment by Greigh** [comment]
I did. I tried disabling the different DNS URLs and couldn’t find the culprit. I just disabled the filter list from injecting into Discord.

**Comment by Greigh** [comment]
Found the issue was related to BetterDiscord.
