### ISSUE TITLE
Google Shopping False Positive (Semi Critical)

### ISSUE THREAD

**Issue by 0ABDL0** [notracking/hosts-blocklists#731]
https://clickserve.dartsearch.net is being used as a bridge between googleadservices.com / Google Built in Ads / Shopping to the website that it's leading to. It's whitelisted in nearly every single filter, even heavier ones.

Completely Brakes Google Shopping ads as the sites that are advertised at the top won't resolve.

Thank you for the great filter.

**Comment by 0ABDL0** [comment]
To explain further let's say I typed in RTX 3080 on Google and went on the Shopping tab, the first recommendations or the listed Ads first resolve to googleadservices.com then go to clickserve.dartsearch.net so whitelisting the first domain doesn't help when it's just used to bounce on to the blocked domain.

**Comment by notracking** [comment]
Thanks! Added to the whitelist, changes will be visible after the next auto update.
