### ISSUE TITLE
Orange Cyber IOC Ukraine - Russia

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#745]
Original ->
https://github.com/Orange-Cyberdefense/russia-ukraine_IOCs/blob/main/OCD-Datalake-russia-ukraine_IOCs-ALL.csv

Source ->
https://raw.githubusercontent.com/scafroglia93/blocklists/master/blocklists-orangecyber.txt

**Comment by notracking** [comment]
List added, thanks!
