### ISSUE TITLE
Include https://hosts.oisd.nl/ to Sources.md

### ISSUE THREAD

**Issue by Sn0whax** [notracking/hosts-blocklists#746]
This is a feature request to add the blocklist "**https://hosts.oisd.nl/**" to Sources.md to allow further blocking.

The host site is https://oisd.nl/ which is a respectable site with a large list of junk to block for various methods.

Per the site:
This will not interfere with: Torrent, Warez, Porn, Crypto Exchanges, News Satire, Slickdeals (or shopping sites in general), Google (shopping), Facebook, Twitter, Snapchat, Link Shortners, Affiliate/Tracking Links, Gambling, Surveys, etc.

**Comment by notracking** [comment]
This will not be added as this is a list build up from various other sources.
