### ISSUE TITLE
False positive : tigase.net/tigase.tech

### ISSUE THREAD

**Issue by ABelliqueux** [notracking/hosts-blocklists#747]
The sisking iOS XMPP client project seems to be hosting their doc and community at tigase.net/tigase.tech. ( See https://siskin.im/ )

Project's repo : https://github.com/tigase/siskin-im

"tigase.net" is listed in `domains.txt` and I suspect "tigase.tech" is listed too as I can't access it either.

**Comment by notracking** [comment]
Thanks! Added to the whitelist, changes will be visible after the next auto update.
