### ISSUE TITLE
pix2.services.tvn.pl

### ISSUE THREAD

**Issue by gita6t5** [notracking/hosts-blocklists#748]
Blocked video
https://fakty.tvn24.pl/ogladaj-online,60/jaroslaw-kaczynski-i-mateusz-morawiecki-w-kijowie-planowane-spotkanie-z-wolodymyrem-zelenskim,1099474.html
https://eurosport.tvn24.pl/tenis,115/iga-swiatek-angelique-kerber-wynik-meczu-i-relacja-indian-wells-2022,1099511.html
![Zrzut ekranu z 2022-03-15 23-21-02](https://user-images.githubusercontent.com/80338577/158482437-a1706a35-8fe6-4339-8ce3-272aec24a176.png)
![Zrzut ekranu z 2022-03-15 23-21-39](https://user-images.githubusercontent.com/80338577/158482446-f4819199-2d2b-4c9b-8660-c391893b7b58.png)

**Comment by notracking** [comment]
Not blocked (anymore) by this list
