### ISSUE TITLE
why is 'image.ibb.co' on the blacklist?

### ISSUE THREAD

**Issue by Th3M3** [notracking/hosts-blocklists#75]
Hello,

i am using yours lists on my pi-hole installation.

Today I uploaded some pictures on `https://de.imgbb.com` to use them in an forum.
`imgbb` is a free service for uploading and sharing pictures.

The uploaded pictures are stored on <b>`image.ibb.co`</b> and they are not getting loaded because the domain is on the blocklist.

**Comment by notracking** [comment]
Hi there,

Thank you for the feedback! host has been added to the whitelist, changes will be visible with the next auto update. This host was listed on the yhosts list.
