### ISSUE TITLE
False positives: ia*.archive.org

### ISSUE THREAD

**Issue by mmurphy2** [notracking/hosts-blocklists#750]
The dnsmasq block list has two false positives:

address=/ia601408.us.archive.org/#
address=/ia801408.us.archive.org/#

The Internet Archive is using a storage cluster, and some legitimate content (chiefly, one of my university-level lecture videos) is served from one of those addresses. Blocking the entire host is denying service to at least some legitimate, non-advertising content.

**Comment by notracking** [comment]
Thanks! Added to the whitelist, changes will be visible after the next auto update.
