### ISSUE TITLE
Domain level blocking...  hearstnp.com

### ISSUE THREAD

**Issue by rururudy** [notracking/hosts-blocklists#754]
Setting up the domain blocklist today caused Hearst sites to not resolve.  Example,
```
# host -t ns sfchronicle.com
sfchronicle.com name server ns5.hearstnp.com.
sfchronicle.com name server ns1.hearstnp.com.
```
Since hearstnp.com was blocked, our DNS server could not recurse to ns1.hearstnp.com to lookup the SFChronicle.com address.

Other people seeing this issue, and is _hostname_ instead of _domainname_ the solution?

**Comment by rururudy** [comment]
It looks like the domains list is not pruned of old entries or something... it is 2x longer than the hostnames list, this does not _"significantly reduces the size of the blocklists"_ as mentioned on the **notracking** page.

**Comment by notracking** [comment]
Thanks! Added to the whitelist, changes will be visible after the next auto update.

**Comment by notracking** [comment]
I recommend using the combined lists, for example the ones made for newer versions of dnsmasq
```https://github.com/notracking/hosts-blocklists/blob/master/dnsmasq/dnsmasq.blacklist.txt```
