### ISSUE TITLE
False positive = noscript.net ??

### ISSUE THREAD

**Issue by jondagle** [notracking/hosts-blocklists#755]
notracking is blocking this domain, which is the homepage of the NoScript extension for firefox, etc... 
https://addons.mozilla.org/en-US/firefox/addon/noscript

I see Ultimate Hosts and Phishing Army still block it; oisd had blocked it for 2 days earlier this month.  
https://blocklist-tools.developerdan.com/entries/search?q=noscript.net

**Comment by notracking** [comment]
Thanks! Added to the whitelist, changes will be visible after the next auto update.
