### ISSUE TITLE
False Positive Totalav

### ISSUE THREAD

**Issue by scafroglia93** [notracking/hosts-blocklists#756]
totalav.com

**Comment by notracking** [comment]
Thanks! Added to the whitelist, changes will be visible after the next auto update.

**Comment by 29039** [comment]
@notracking Please take TotalAV OFF the whitelist and put it onto the blacklist. It is NOT a false positive. Google for "TotalAV Scam" and you find from various discussion forums that even though it is actual antivirus software (using Avira engine), they are notorious for using scams to get people to buy it through affiliates and keep charging far more than the agreed price.

**Comment by 29039** [comment]
@scafroglia93

**Comment by scafroglia93** [comment]
So, what's the issue ?

Totalav is legit company

**Comment by iam-py-test** [comment]
> So, what's the issue ?
> 
> Totalav is legit company

Evidence?
This company is very shady.
i.e.
https://www.virustotal.com/gui/url/42047d9bd1c0a9ffda3b38dc9e7e95d809a5b7f4b345dce42088d0ada486f6fb/community
https://www.mywot.com/scorecard/totalav.com
https://blog.malwarebytes.com/detections/pup-optional-totalav/

**Comment by 29039** [comment]
@scafroglia93 Extra evidence:

https://forums.malwarebytes.com/topic/242780-totalav-registered-as-pup/
https://www.wilderssecurity.com/threads/totalav.392399/
https://www.productreview.com.au/listings/total-av
See the comments: https://securitygladiators.com/totalav-review-worth-reading/
https://review.easycounter.com/totalav-scam-report
https://shackfeel.com/totalav/
https://newsonlineincome.com/totalav/
https://www.logitheque.com/en/articles/total-av-a-product-closer-to-a-scam-than-an-antivirus-13218
https://malwaretips.com/threads/total-av-is-it-a-scam.80362/
https://trojan-killer.net/remove-totalav/
https://www.bbb.org/us/ca/venice/profile/computer-software/total-av-antivirus-1216-716805/complaints
https://www.reddit.com/r/antivirus/comments/dwlnlf/totalav_scam/
https://www.austech.info/showthread.php/122563-Bull-Crap-Scamming-Domain-Names!!!?p=859437
https://www.viruspup.com/kb/is-total-av-safe.html
Mostly fake reviews: https://www.trustpilot.com/review/totalav.com
https://old.reddit.com/r/antivirus/search?q=totalav&restrict_sr=on&sort=relevance&t=all

**Comment by notracking** [comment]
Moved it to the blocklist again, thanks for the sources. Obvious scam company.
