### ISSUE TITLE
Pls add this into whitelist into domain.txt

### ISSUE THREAD

**Issue by ookangzheng** [notracking/hosts-blocklists#76]
distillery.wistia.com
fast.wistia.com
pipedream.wistia.com
wistia.com

**Comment by notracking** [comment]
Whitelisted, except for pipedream.wistia.com and distillery.wistia.com.
 
Changes will be visible after the next auto update, I will leave the ticket open for you to confirm if this is sufficient.

Thanks for the feedback!
