### ISSUE TITLE
New tracker > bf.dynatrace.com

### ISSUE THREAD

**Issue by iam0day** [notracking/hosts-blocklists#760]
![IMG_20220513_142835_159](https://user-images.githubusercontent.com/17969978/168283147-12f78dc5-3327-4585-bb37-85a98b31eb49.jpg)

It seems that `bf.dynatrace.com` is a trackers, i recommend adding it to the list.

**Comment by notracking** [comment]
Thanks! Added to the custom list, changes will be visible after the next auto update.
