### ISSUE TITLE
False positive:  wl.spotify.com

### ISSUE THREAD

**Issue by Sduibek** [notracking/hosts-blocklists#763]
This subdomain is used for legitimate purposes with links in Spotify emails, for example when selecting "unsubscribe" or "edit my profile".

The text usually appears something like-

_"This message was sent to [emailaddress]. If you don't want to receive these emails from Spotify in the future, you can **edit your profile** or **unsubscribe**."_

**Comment by notracking** [comment]
Thanks! Added to the whitelist, changes will be visible after the next auto update.
