### ISSUE TITLE
False positive: https://faizanullah.com

### ISSUE THREAD

**Issue by faizanchem** [notracking/hosts-blocklists#772]
faizanullah.com is personal academic website. Please remove it.

**Comment by notracking** [comment]
faizanullah.com is marked as infected with zscaler (did you check for any intrusions lately?)

**Comment by faizanchem** [comment]
Previously the site was compromised but I have cleaned and rebuild site on new host with improved security settings. And it is now to the best of my knowledge clean and secure. So I request its removal from your list.

**Comment by notracking** [comment]
Thanks! Added to the whitelist, changes will be visible after the next auto update.

You should also check with Scafrog93, as his zscaler list is the source.
