### ISSUE TITLE
SimpleLogin false positive

### ISSUE THREAD

**Issue by iam0day** [notracking/hosts-blocklists#785]
`slmail.me`

`simplelogin.fr`

Hi, these two domains are blocked from your list... They are legitimate domains.

**Comment by hagezi** [comment]
Hi,

`slmail.me` is flagged by 8 vendors:
https://www.virustotal.com/gui/url/48fcd0353c961bdcef3727c95e51fc191b5f92ee8336fc352d03b193aeaeb529

`simplelogin.fr` is flagged by 8 vendors:
https://www.virustotal.com/gui/url/4f1481d63322977d7079eaef48b5678ba693c153d99b947c35c13ffcd7158452

Cheers,
[Gerd](https://github.com/hagezi/dns-blocklists)

**Comment by iam0day** [comment]
Hello, I can assure you that these are false positives because they are [official and verified domains](https://simplelogin.io/security/).

**Comment by hagezi** [comment]
Then the operator should make sure that they are no longer marked as malicious. The domains are on many malware block lists.

**Comment by notracking** [comment]
Thanks! Added to the whitelist, changes will be visible after the next auto update.
