### ISSUE TITLE
fwmrm.net

### ISSUE THREAD

**Issue by gita6t5** [notracking/hosts-blocklists#787]
Video is not loading
https://sportowefakty.wp.pl/pilka-nozna/wideo/44323/darwin-przywital-sie-z-anfield-najgorzej-jak-mogl-nerwy-mu-kompletnie-puscily
![Screenshot_20220816_105725](https://user-images.githubusercontent.com/80338577/184840122-78b16487-949d-4fbc-b0e9-3e42e014c059.png)
https://oisd.nl/excludes.php?w=m1.fwmrm.net
https://oisd.nl/excludes.php?w=mssl.fwmrm.net

**Comment by notracking** [comment]
Thanks! Added to the whitelist, changes will be visible after the next auto update.
