### ISSUE TITLE
dcf.espn.com

### ISSUE THREAD

**Issue by gita6t5** [notracking/hosts-blocklists#788]
Video is not loading
https://fivethirtyeight.com/videos/are-democrats-really-going-to-win-in-ohio-and-wisconsin/
![Screenshot_20220816_111737](https://user-images.githubusercontent.com/80338577/184844285-4f998a84-5efc-4577-b195-1acb810817b0.png)

**Comment by hagezi** [comment]
I had to whitelist `players.brightcove.net` for the video to start.

Cheers,
[Gerd](https://github.com/hagezi/dns-blocklists)

**Comment by notracking** [comment]
Thanks! Added to the whitelist, changes will be visible after the next auto update.
