### ISSUE TITLE
custom blocklist

### ISSUE THREAD

**Issue by alsyundawy** [notracking/hosts-blocklists#790]
hi, can req for custom blocklist just

Blocks scam websites
Blocks malware servers
Blocks phishing servers

**Comment by hagezi** [comment]
You can try my Threat-Intelligence-Feeds list. An blocklist for blocking malware, crypto, coin, scam, spam and phishing. Blocks domains known to spread malware, launch phishing attacks and host command-and-control servers.

https://github.com/hagezi/dns-blocklists#threat-intelligence-feeds---increases-security-significantly

**Comment by alsyundawy** [comment]
ok thx, i will try becouse i wanna just block all but ads allowed.

**Comment by notracking** [comment]
No active plans to try splitting up the lists.
