### ISSUE TITLE
pxl.qccerttest.com

### ISSUE THREAD

**Issue by r2fo** [notracking/hosts-blocklists#797]
I found this domain in my logs when visiting 9to5Mac. It seems to be a pixel tracker based on a Google search. I use a lot of other blocklists (including OISD, 1Hosts Pro, Energized Ultimate, EasyPrivacy, all AdGuard lists, Lightswitch, ...) and none of these blocks that tracker domain except the aggressive 1Hosts Xtra list

**Comment by yokoffing** [comment]
It is in 1Hosts Pro as of 25 Sept 2022 https://blocklist-tools.developerdan.com/entries/search?q=pxl.qccerttest.com
