### ISSUE TITLE
Adblock_Plus para PiHole tiene formato incorrecto

### ISSUE THREAD

**Issue by JuanRodenas** [notracking/hosts-blocklists#798]
El fichero para el blockeo de Adblock_Plus, es incorrecto:

[i] Target: https://raw.githubusercontent.com/notracking/hosts-blocklists/master/adblock/adblock.txt
[✓] Status: Retrieval successful
[i] Analyzed 337054 domains, 337054 domains invalid!
Sample of invalid domains:
- 2.0]
- ||0--0.gq^
- ||0--0.ml^
- ||0--e.info^
- ||0-0-0-0-0-0-0-0-0-0-0-0-0-37-0-0-0-0-0-0-0-0-0-0-0-0-0.info^

Saludos

**Comment by hagezi** [comment]
Pihole cannot process lists in adblock format. Use domain or host lists.
