### ISSUE TITLE
linksynergy.com blocked

### ISSUE THREAD

**Issue by ookangzheng** [notracking/hosts-blocklists#80]
linksynergy.com was blocked in domains.txt

**Comment by notracking** [comment]
This domain is only used for tracking purposes, why should it be whitelisted?

**Comment by ookangzheng** [comment]
hmm, I saw a lot udemy courses, they use this domain to redirect

**Comment by notracking** [comment]
Link redirectors are dangerous for the internet; if they break all sites using them break and they are commonly used to obfuscate malicious domains.

I was not able to find any malfunction at https://www.udemy.com/, maybe I missed something? Besides that: this particular one is owned by a company who's core business is tracking and spamming of users.

Will not whitelist for now.
