### ISSUE TITLE
xep.li | Short URL service

### ISSUE THREAD

**Issue by S8D** [notracking/hosts-blocklists#800]
I am using xep.li link shortening service and also using notracking filter
But xep.li has been blacklisted by the notracking filter.
Maybe it was abused to do bad things so it was blacklisted by nottracking, but that affects a lot of the rest of users.
Looking forward to nottracking think about removing xep.li from the blacklist.
Thank you.

**Comment by notracking** [comment]
Thanks! Added to whitelist.
