### ISSUE TITLE
[FP] self.events.data.microsoft.com

### ISSUE THREAD

**Issue by devipasigner** [notracking/hosts-blocklists#803]
Endpoint self.events.data.microsoft.com is used to connect to the Microsoft 365 admin center's shared infrastructure, including Office in a browser. If you turn off traffic for these endpoints, users won't be able to save documents to the cloud or see their recently used documents.

https://docs.microsoft.com/en-us/windows/privacy/manage-windows-1903-endpoints

**Comment by notracking** [comment]
Thanks! Added to whitelist.
