### ISSUE TITLE
Disguised.nl

### ISSUE THREAD

**Issue by Zendio** [notracking/hosts-blocklists#804]
Disguised.nl is my personal domain which I use as an e-mail alias server ([SimpleLogin service](https://simplelogin.io)). No malicious activity on my part. The domain links to a privacy related website.
I wonder how I ended up on the blocklist.

**Comment by JohnChristianD** [comment]
This also gets blocked by "Threat Intelligence" of NextDNS. I wonder how long till they correct these incorrect blockages as there seems to be a lot of open issues including mine that are long unresolved.

**Comment by notracking** [comment]
Added to the whitelist, this fp was sourced from the toxic domains list.
