### ISSUE TITLE
Unblock a.klaviyo.com

### ISSUE THREAD

**Issue by mahtd** [notracking/hosts-blocklists#808]
Blocking a.klaviyo.com prevents me from unsubscribing from Graf Lantz and Darn Tough Vermont marketing emails, both which use Klaviyo to manage the lists

https://manage.kmail-lists.com/subscriptions/unsubscribe?a=pvj9uj

**Comment by notracking** [comment]
Thanks! Added to the whitelist, changes will be visible after the next auto update.
