### ISSUE TITLE
false positive

### ISSUE THREAD

**Issue by hyder365** [notracking/hosts-blocklists#815]
I'm using https://raw.githubusercontent.com/notracking/hosts-blocklists/master/dnscrypt-proxy/dnscrypt-proxy.blacklist.txt for DNS ad blocking.

One of the domains on it is "services.chipotle.com" which breaks the online order functionality of the website.

**Comment by hagezi** [comment]
ping @notracking

**Comment by FadeMind** [comment]
@hagezi maintainer does not have time for maintain false positives, also > https://github.com/notracking/hosts-blocklists-scripts/pull/9

**Comment by hyder365** [comment]
Upstream will not fix it: https://github.com/AdguardTeam/cname-trackers/issues/62

So I'll just have to drop this list from my filters if it's not being actively maintained.

**Comment by notracking** [comment]
Thanks! Added to the whitelist, changes will be visible after the next auto update.

**Comment by notracking** [comment]
And excuse me for being less active for the first time in 10 years, I've got a lot going on in my private life atm. This is not a paid job, just a hobby. Other things have higher priority from time to time..

Still thanks for submitting the false positives.

**Comment by yokoffing** [comment]
> This is not a paid job, just a hobby.

Yep. We are not compensated for our services.

> I've got a lot going on in my private life atm... Other things have higher priority from time to time.

That's fair. I hope things settle down for you.
