### ISSUE TITLE
za.zdn.vn - false positive

### ISSUE THREAD

**Issue by hlqviet** [notracking/hosts-blocklists#817]
![image](https://user-images.githubusercontent.com/5486625/202839402-72f86fcd-de28-4ee4-a6a3-2c7f6706cf0b.png)

I reported this hostname in the upstream hosts bigdargon/hostsVN#334 and it has been removed. notracking is still blocking it but I don't know where it comes from.

**Comment by notracking** [comment]
Thanks! Added to the whitelist, changes will be visible after the next auto update.
