### ISSUE TITLE
kutt.it (false positive)

### ISSUE THREAD

**Issue by lyrad87** [notracking/hosts-blocklists#819]
Kutt is an open-source and modern URL shortener with support for custom domains and stats and it's currently blocked by notracking. Please add it to your allowlist or inform the upstream source to remove it. Thanks in advance!

https://kutt.it/
https://github.com/thedevs-network/kutt

**Comment by notracking** [comment]
Thanks! Added to the whitelist, changes will be visible after the next auto update.
