### ISSUE TITLE
js.captcha-display.com block prevents logging in

### ISSUE THREAD

**Issue by JohnChristianD** [notracking/hosts-blocklists#822]
Link is https://auth.garena.com/oauth/login?client_id=200089&redirect_uri=https%3A%2F%2Fgarena.authenticate.riotgames.com%2Fredirects%2Fgarena&state=3af47bc0e84dfde5cd4b13821479004a5893d1a2954b26555d31ed2511bc&scope=&platform=1&response_type=code&prompt=login which is required by https://leaguelink.riotgames.com/en-us/ to link Riot account to Garena account.

**Comment by notracking** [comment]
Thanks! Added to the whitelist, changes will be visible after the next auto update.
