### ISSUE TITLE
Add 98% ads and trackers blocked

### ISSUE THREAD

**Issue by githubissocool** [notracking/hosts-blocklists#823]
![image](https://user-images.githubusercontent.com/97558900/206968249-830a8772-e552-4ce4-8143-746ec9f923f3.png)
Add googleadservices.com and ads.google.com for 100% of ads blocked

Website: https://d3ward.github.io/toolz/adblock.html

**Comment by hagezi** [comment]
Such tests have zero significance for the quality and efficiency of a block list.

**Comment by notracking** [comment]
ads.google.com is not used for serving ads.
blocking googleadservices.com will break the entire google shopping infra, which will lead to people stopping using the filters completely.

Please check to validate why certain items are whitelisted: https://github.com/notracking/hosts-blocklists-scripts/blob/master/hostnames.whitelist.txt
