### ISSUE TITLE
||pxf.io^

### ISSUE THREAD

**Issue by marcoclg19** [notracking/hosts-blocklists#828]
Hi, I clicked on a link of a site I usually read and your blocklist seems to be blocking this domain.

I use AdGuardDNS.
This is the link: https://www.upgo.it/ly/fibranew
The redirection to the final page does not happen because this domain is blocked in the middle:  `comparetech.pxf.io`
So I looked here at what the initial short link might interfere with the final link: https://urlscan.io/result/cfe1b2fc-f865-4220-9020-6c970d83dd04/#redirects

@notracking I think I have given all the necessary information.

Cheers!

**Comment by marcoclg19** [comment]
https://blocklist-tools.developerdan.com/entries/search?q=pxf.io
These are the blocklits that block this domain. I don't know if the @hagezi blocklits also block it. The AdGuard list also seems to block it.

**Comment by hagezi** [comment]
@marcoclg19 `pxf.io` is used as a referral domain. In my lists it is only blocked in utlimate because I explicitly do not unblock referral domains in utlimate.
In all other lists referral domains were unblocked.

**Comment by marcoclg19** [comment]
> `pxf.io` is used as a referral domain

Ok! All clear now... do you think I should open an issue to request to remove it from the AdGuard list too?

**Comment by hagezi** [comment]
Hi, @Alex-302,

can you take a look at this and possibly unblock it in the AdGuardDNS blocklist?
Domain: `comparetech.pxf.io`

Thanks,
Gerd

ping @marcoclg19

**Comment by Alex-302** [comment]
Changed in our filter, which is used as part of our DNS filter.

**Comment by notracking** [comment]
Thanks! Added to the whitelist, changes will be visible after the next auto update.
(was blocked in yoyo's list)

**Comment by marcoclg19** [comment]
ping @StevenBlack 

Also your blocklist blocks this domain... Maybe because it includes yoyo's list.
