### ISSUE TITLE
Please add captcha-display.com to allowlist

### ISSUE THREAD

**Issue by vuongvan** [notracking/hosts-blocklists#830]
captcha-display.com block prevents logging in Garena
[Link](https://auth.garena.com/oauth/login?client_id=200089&redirect_uri=https%3A%2F%2Fgarena.authenticate.riotgames.com%2Fredirects%2Fgarena&state=3af47bc0e84dfde5cd4b13821479004a5893d1a2954b26555d31ed2511bc&scope=&platform=1&response_type=code&prompt=login)

**Comment by notracking** [comment]
Thanks! Added to the whitelist, changes will be visible after the next auto update.
