### ISSUE TITLE
Add Control D to readme

### ISSUE THREAD

**Issue by trollybusman** [notracking/hosts-blocklists#833]
I really like this blocklist, and Control D made it really easy for me to use it on mobile. Just set the Private DNS to `x-notracking.freedns.controld.com` and it just works. Getting same latency as to Cloudflare. 

They also support DOH, and UDP DNS: 
- https://freedns.controld.com/x-notracking
- 76.76.2.37 + 76.76.10.37
- 2606:1a40::37 + 2606:1a40:1::37

I think this is really useful for those who don't want to run their own piholes. I used to, but now theres no point.  They support a whole bunch of other blocklists too https://kb.controld.com/en/3rd-party-filters

**Comment by notracking** [comment]
Thanks! Added a link to their own instructions.
