### ISSUE TITLE
List blocks "vlscppe.microsoft.com" which is needed to download ISOs from Microsoft.

### ISSUE THREAD

**Issue by JacobDrivers** [notracking/hosts-blocklists#834]
This list blocks "vlscppe.microsoft.com" which thwarts any ISO download attempts from Microsoft's download page with the error message below. Other tools that download Windows ISO's (Directly from Microsft's servers), such as [Rufus](https://rufus.ie), [TechBench](https://techbench.betaworld.cn/), and more - [also fail if this is blocked](https://imgur.com/zfhXHs5). After some hours of fiddling around, I finally found out it was [this DNS blocklist](https://imgur.com/mITxBnX). I thought it was OISD's at first. For now, I will be disabling this list, as I need to be able to download Windows ISOs.

Error message "We are unable to complete your request at this time. Some users, entities and locations are banned from using this service. For this reason, leveraging anonymous or location hiding technologies when connecting to this service is not generally allowed. If you believe that you encountered this problem in error, please try again. If the problem persists you may contact[ Microsoft Support – Contact Us ](https://support.microsoft.com/en-gb/contactus/)page for assistance. Refer to message code 715-123130"

**Comment by notracking** [comment]
Thanks! Added to the whitelist, changes will be visible after the next auto update.
