### ISSUE TITLE
IPV6 Supported?

### ISSUE THREAD

**Issue by DaniSpringer** [notracking/hosts-blocklists#836]
Is IPv6 supported? (M1 Mac)
Thanks

**Comment by notracking** [comment]
That depends on your dns resolver, not on the blocklist.

**Comment by DaniSpringer** [comment]
> That depends on your dns resolver, not on the blocklist.

Check again. That is not correct.

**Comment by notracking** [comment]
In that case you will need to provide me with a better problem description. I do not have access to a mac, nor do I know how its dns works. With dnsmasq and dnscrypt-proxy (recommended) ipv4 and ipv6 are working without any issue.
