### ISSUE TITLE
Block "Get cookies.txt"

### ISSUE THREAD

**Issue by rapdodge** [notracking/hosts-blocklists#842]
[Get cookies.txt](https://chrome.google.com/webstore/detail/get-cookiestxt/bgaddhkoddajcdgocldbbfleckgcbcid) is a spyware now.

Please adding this domain below to block the access.
`getcookiestxt.com`

Proof
![image](https://user-images.githubusercontent.com/33513626/217723540-c0ec3c09-1374-4412-aae2-66f3ad90561a.png)

External References:
https://github.com/ytdl-org/youtube-dl/issues/31465

**Comment by hagezi** [comment]
@notracking you can block the tracker domain `ck.getcookiestxt.com`, see https://github.com/hagezi/dns-blocklists/issues/320

**Comment by notracking** [comment]
Thanks, added!

**Comment by Kavolc** [comment]
Is there a way to do this on mobile? I was using it on kiwi browser.
