### ISSUE TITLE
The domain of tracking etc. that I discovered

### ISSUE THREAD

**Issue by 00028** [notracking/hosts-blocklists#847]
analytics.sothinkmedia.com
analytics.karakuri.ai
analytics.streamfab.jp

metrics.evernote.com

tracking.iwhop.cn
tracking.mbc.net
et.topazlabs.com
tracking.apptrackerlink.com

log.tpns.sgp.tencent.com
client-log.karte.io
stream-log.profilepassport.jp
aclog.itmedia.co.jp
log.happypvp.com
log.happymodio.com

support-beacon.userlocal.jp
api-sdk.beaconbank.jp

servo-report.streamfab.jp
report-edge.agora.io

ka.unext.jp
statis.simeji.me
buddy.simeji.me
aityping.simeji.me
n-da.tplinkcloud.com

tr.api.itmedia.jp
tr.api.itmedia.co.jp

events.backtrace.io

**Comment by notracking** [comment]
Thanks! Added to the custom list, changes will be visible after the next auto update.
