### ISSUE TITLE
False positive: blog.pixelexperience.org

### ISSUE THREAD

**Issue by kerryzx** [notracking/hosts-blocklists#855]
Hello, the aforementioned website is used by PixelExperience team (an open-source project) to publish new announcements regarding their work. It is a safe and trustful website and there is no reason for it to be blacklisted. Please see if you can unblock it. Thank you.

**Comment by notracking** [comment]
Seems to be resolved.

**Comment by notracking** [comment]
My excuse, it was actually the CNAME 'g.ezoic.net' that is still blocked. Removed it from the list, changes will be visible after the next auto-update!
