### ISSUE TITLE
False positive: incorporateapps.com

### ISSUE THREAD

**Issue by IncorporateApps** [notracking/hosts-blocklists#857]
Hello,

someone has falsely submitted our domain name www.incorporateapps.com to your blacklist. We would appreciate it if you remove it.

Thank you very much!

**Comment by hagezi** [comment]
It is flagged:
https://www.virustotal.com/gui/domain/incorporateapps.com/detection

That's probably why it ended up on the list.

**Comment by IncorporateApps** [comment]
There is nothing harmful on our servers. Probably added because we have Android Ad based apps.

**Comment by hagezi** [comment]
@IncorporateApps I believe so, but I recommend having the page removed by the services that flagged it. Otherwise, sooner or later it will always end up on some lists.

**Comment by IncorporateApps** [comment]
We just submitted false positives to CRDF and Seclookup and stamparm. Any other places?

**Comment by hagezi** [comment]
I have not found any others.

**Comment by notracking** [comment]
Seems to be resolved.
