### ISSUE TITLE
Remove Neo23x0/signature-base from sources

### ISSUE THREAD

**Issue by amano-kenji** [notracking/hosts-blocklists#859]
https://raw.githubusercontent.com/Neo23x0/signature-base/master/iocs/c2-iocs.txt blocks monero mining pools.

Monero mining pools are not malwares.

https://github.com/Neo23x0/signature-base/commit/96a0697d4144c19c998463306a0682d70a7f5e75 specifically blocks monero mining pools.

**Comment by notracking** [comment]
Agreed, list will be remove with the next autoupdate. Thanks!
