### ISSUE TITLE
maxmind.com whitelist request

### ISSUE THREAD

**Issue by bahamas10** [notracking/hosts-blocklists#86]
hi, i love this blocklist :+1: !

I noticed maxmind.com was blocked - i've used this site in the past for some of its geoip tools... i don't really know much else about it.  if you google "geoip" it's the first result.

ps: i made https://github.com/bahamas10/notracking to automatically pull the latest lists, ensure they are valid (point to 0.0.0.0, if these lists got hacked it could be really bad), and optionally restart a service... thanks again for this list :D

**Comment by notracking** [comment]
That's a nice and safer way of automatically downloading the blocklists ,good job!

Unless there are some clear samples of websites not functioning due to making 3rd party requests to maxmind.com, I really cannot whitelist this one.
