### ISSUE TITLE
Hostname tms.nab.com.au

### ISSUE THREAD

**Issue by Pikey18** [notracking/hosts-blocklists#861]
The domain tms.nab.com.au is used for NAB (a bank in Australia) for card payments (as a merchant).

If this domain is blocked it stops card payments working in their app (linked below). I have whitelisted it on my end but think it should be removed as a false positive on the master list. 

https://www.nab.com.au/business/payments-and-merchants/accepting-in-person-payments/nab-easy-tap

**Comment by notracking** [comment]
Thanks! Added to the whitelist, changes will be visible after the next auto update.
