### ISSUE TITLE
Adding email trackers

### ISSUE THREAD

**Issue by Nive9** [notracking/hosts-blocklists#868]
Here are a few read receipt tracking links/ pixels for some email clients I've tested with throwaway accounts:

(Mailspring, Polymail, Newton, Mailbird, Canary Mail)
```
link.getmailspring.com
share.polymail.io
tr.cloudmagic.com
tracking.getmailbird.com
read-receipts.canarymail.io
```

Since they're just embedded images without content, they shouldn't and don't seem to break anything.

**Comment by thomasmerz** [comment]
I checked my Pi-hole using some nice sources of block-lists:
```
 Match found in https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts:
   link.getmailspring.com
 Match found in https://raw.githubusercontent.com/notracking/hosts-blocklists/master/hostnames.txt:
   link.getmailspring.com
   link.getmailspring.com
 Match found in https://github.com/badmojr/1Hosts/releases/download/latest/1hosts-Lite_domains.txt:
   link.getmailspring.com
  [i] No results found for share.polymail.io within the adlists
  [i] No results found for tr.cloudmagic.com within the adlists
  [i] No results found for tracking.getmailbird.com within the adlists
  [i] No results found for read-receipts.canarymail.io within the adlists
```

`link.getmailspring.com` is already in this hosts-blocklists.

**Comment by hagezi** [comment]
I will never understand the sense behind blocking referral domains via DNS that are only called up when the user explicitly clicks on a link and are not used for other tracking actions. Unless you want to annoy the user.

**Comment by notracking** [comment]
Agree to not wanting to list actual links for unsubscribing etc, but these seem to be actual tracking pixel domains. Added.
