### ISSUE TITLE
Spotify-Ad-free source is broken

### ISSUE THREAD

**Issue by imTHAI** [notracking/hosts-blocklists#87]
Hello,

I checked some sources you've listed and it appears that:
https://raw.githubusercontent.com/FadeMind/hosts.extras/master/Spotify-Ad-free/hosts
is broken. 
So each time you autoupdate, you should get an error too. Or the list of sources you publish is not up-to-date ?

Thanks

**Comment by notracking** [comment]
Hi, Thank you for the feedback!

I've wrote some basic validation tests to check for these kind of issues. In case a list is invalid the last known good version will be used. In this case the script was already updated, but I forgot to (manually) update de README.

This is fixed now :)
