### ISSUE TITLE
VC++Redist links blocked (false-positive)

### ISSUE THREAD

**Issue by w3lld0ne** [notracking/hosts-blocklists#874]
https://download.visualstudio.microsoft.com/download/pr/8b92f460-7e03-4c75-a139-e264a770758d/26C2C72FBA6438F5E29AF8EBC4826A1E424581B3C446F8C735361F1DB7BEFF72/VC_redist.x64.exe

https://download.visualstudio.microsoft.com/download/pr/b2519016-4a13-4120-936c-cae003d567c4/8AE59D82845159DB3A70763F5CB1571E45EBF6A1ADFECC47574BA17B019483A0/VC_redist.x86.exe

**Comment by manalshaikh** [comment]
can confirm. Don't know why `download.visualstudio.microsoft.com` is blocked.

**Comment by notracking** [comment]
No problems here, can you check if there are specific cnames that are blocked?

```
# dig download.visualstudio.microsoft.com

; <<>> DiG 9.16.37-Debian <<>> download.visualstudio.microsoft.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 44826
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;download.visualstudio.microsoft.com. IN	A

;; ANSWER SECTION:
download.visualstudio.microsoft.com. 2233 IN CNAME visualstudio.download.prss.trafficmanager.net.
visualstudio.download.prss.trafficmanager.net. 2233 IN CNAME 4316b.wpc.azureedge.net.
4316b.wpc.azureedge.net. 2233	IN	CNAME	cs10.wpc.v0cdn.net.
cs10.wpc.v0cdn.net.	1207	IN	A	68.232.34.200

;; Query time: 0 msec
;; SERVER: 10.9.0.1#53(10.9.0.1)
;; WHEN: Mon Apr 24 23:41:06 CEST 2023
;; MSG SIZE  rcvd: 208
```

**Comment by w3lld0ne** [comment]
Currently it's working, maybe one of the autoupdates fixed it. @manalshaikh can you confirm?

**Comment by manalshaikh** [comment]
Unfortunately I use a third party DNS provider for blocking requests. And they use notracking as one of their repository for listing requests.
However, considering they update regularly, it seems that it is no longer blocked as of writing this.
