### ISSUE TITLE
Please create a separate txt for porn sites and remove them from domains.txt

### ISSUE THREAD

**Issue by blackoutworm** [notracking/hosts-blocklists#88]
Hi there. 
In your general politics, it says "Should not break useful websites or apps". But it does.
I found a lot of porn sites in that websites.txt list.
And I get it. A lot of people use this script on their kid's computer. But people like me just want to block out ads, malware and spam like that.
So do you think you can please create a separate file for porn instead?

**Comment by notracking** [comment]
Hi there,

This blocklist should not block porn sites by default, unfortunately though a lot of 'porn' domains are used to serve malware. Malicious domains should and always will remain blocked here. If you have a set of domains which you believe should be whitelisted then please create a separate ticket so I can investigate them one by one.

So there is no need to create a separate list for porn related domains.
