### ISSUE TITLE
[false positive] s6920149.sendpul.se

### ISSUE THREAD

**Issue by 3xploiton3** [notracking/hosts-blocklists#884]
s6920149.sendpul.se
email unsubscribe snov.id

![image](https://github.com/notracking/hosts-blocklists/assets/19517680/6b61f357-d563-49ad-a377-d5c6f5e80c49)
![image](https://github.com/notracking/hosts-blocklists/assets/19517680/100782cc-e711-4b92-8b53-a922fa245f36)

**Comment by notracking** [comment]
Thanks! Added to the whitelist, changes will be visible after the next auto update.

**Comment by notracking** [comment]
My Bad! Should have also whitelist their main domain. Will be fixed with the next autoupdate.
