### ISSUE TITLE
invalid domains

### ISSUE THREAD

**Issue by pallebone** [notracking/hosts-blocklists#887]
Hi there,

Thank you for these lists, I notice there are 5 invalid domains:

  [i] Target: https://raw.githubusercontent.com/notracking/hosts-blocklists/master/adblock/adblock.txt
  [✓] Status: Retrieval successful
  [✓] Parsed 0 exact domains and 456427 ABP-style domains (ignored 5 non-domain entries)
      Sample of non-domain entries:
        - "||9904.a^"
        - "||cloudacademies.p^"
        - "||ionix.co.d^"
        - "||mightbesupposed.t^"
        - "||reken-bhf.d^"

EG: .d is not a TLD.

Kind regards
Peter

**Comment by notracking** [comment]
Thanks Peter! Will be fixed after the next auto update.

**Comment by pallebone** [comment]
[i] Target: https://raw.githubusercontent.com/notracking/hosts-blocklists/master/adblock/adblock.txt
  [✓] Status: Retrieval successful
  [✓] Parsed 0 exact domains and 423228 ABP-style domains (ignored 0 non-domain entries)
  [i] List has been updated
