### ISSUE TITLE
false positive

### ISSUE THREAD

**Issue by brspace-com-br** [notracking/hosts-blocklists#888]
Hi, congratultations for ur work. Please, where to submit false positive? It is a hosting company.
brspace.com.br
hostz.com.br

**Comment by lkraider** [comment]
Another false positive is: accounts.google.com.br

**Comment by lkraider** [comment]
It seems to be blocking many .com.br domains

**Comment by brspace-com-br** [comment]
Yes, some days ago, amazon.com.br too.

**Comment by Safibulae** [comment]
I also had to cease using Notracking due to the unexpected blocking of several .com.br domains, including, for example, uol.com.br and iFood.com.br.

**Comment by ubalklen** [comment]
> Yes, some days ago, amazon.com.br too.

Actually, one of their front-end servers has been flagged by Google Safe Browsing.

**Comment by leonirlopes** [comment]
The following rule is blocking a Country Code Top-Level Domain (ccTLD) from Brazil.
`||com.br^`

Trusted sites that are affected by the rule:
- google.com.br
- microsoft.com.br

**Comment by scafroglia93** [comment]
it was fixed

**Comment by notracking** [comment]
Added measures to prevent this from happening in the future, issue is solved.
