### ISSUE TITLE
FP gateway.fe.apple-dns.net

### ISSUE THREAD

**Issue by Thomas-Schubert** [notracking/hosts-blocklists#889]
False positive: gateway.fe.apple-dns.net

this blocks access to gateway.iCloud.com which is Apples iCloud service.

**Comment by 33b5e5** [comment]
Came here to report the same.

Also, `stocks-edge.apple.com` appears incorrectly blocked. This prevents the news articles from loading in Apple's Stocks app on iOS.

**Comment by Thomas-Schubert** [comment]
> 
This relates to the same blocked domain (apple-dns.net).

**Comment by notracking** [comment]
These have been fixed and preventive whitelisted.
