### ISSUE TITLE
notracking list blocked all com.br websites

### ISSUE THREAD

**Issue by np212pn** [notracking/hosts-blocklists#890]
Please remove the line ||com.br^ from your blocklist, it's blocking ALL brazilian (com.br) domains and subdomains. Thanks!

**Comment by TrueConfiguration** [comment]
Hi, can confirm. `.com.br` is the commercial second level domain to wich every company in Brazil must register, aside from government entities.

Blocking this domain with a wildcard effectively blocks the vast majority of Brazilian domains.

**Comment by np212pn** [comment]
If you use Pi-hole and want to continue to use notracking list while having access to ".com.br" websites you have to remove the entry straight from the gravity.db with the command:

sudo pihole-FTL sqlite3 /etc/pihole/gravity.db "delete from gravity where domain = '||com.br^';"

Remember Pi-hole updates gravity.db every Sunday morning.

I really hope they remove that line from blocklist, makes no sense to block ALL ".com.br" domains and subdomains.

**Comment by TrueConfiguration** [comment]
> If you use Pi-hole and want to continue to use notracking list while having access to ".com.br" websites you have to remove the entry straight from the gravity.db with the command:
> 
> sudo pihole-FTL sqlite3 /etc/pihole/gravity.db "delete from gravity where domain = '||com.br^';"
> 
> Remember Pi-hole updates gravity.db every Sunday morning.
> 
> I really hope they remove that line from blocklist, makes no sense to block ALL ".com.br" domains and subdomains.

Won't this rule be recreated every time gravity runs an update? Anyway, I disabled this list altogether until they remove the `||com.br^` rule, since manually removing the rule is just a palliative (I use Adguard Home and update my lists daily) and adding an exception would mean unblocking every `.com.br` domain.

**Comment by hagezi** [comment]
ping source: @scafroglia93

https://github.com/scafroglia93/blocklists/blob/c1a7b7f0176b17cb712f14da6969ae0b1ee2ad56/blocklists-malware-traffic.txt#L157

**Comment by scafroglia93** [comment]
fixed

**Comment by TrueConfiguration** [comment]
> fixed

It's definitely not fixed, still seeing it in the lists.

**Comment by scafroglia93** [comment]
https://github.com/scafroglia93/blocklists/commit/e3c3d53221ffef731ed42d0dc5d8be152d0cbc5c

**Comment by TrueConfiguration** [comment]
Thanks, just checked the new update and `||com.br^` was really removed.
