### ISSUE TITLE
This list blocks a lot

### ISSUE THREAD

**Issue by dm9tr0** [notracking/hosts-blocklists#891]
I use Adguard with this filter list. https://adguardteam.github.io/HostlistsRegistry/assets/filter_32.txt 
Issues:
Iphone can not create reserve copy to iCloud because was blocked [gateway.icloud.com ](url), should be blocked metrics.icloud.com like it is in Adguard filter, but not hole gateway itself.
Also firefox could not get latest update (didn`t find right request in log), but after turn off this list - update was downloaded.

Maybe something else, for me was enough even these both to remove your block list.
Thanks!

**Comment by notracking** [comment]
These have been fixed in the upstream sources.
