### ISSUE TITLE
Sem acesso no Brasil - No access in Brazil 

### ISSUE THREAD

**Issue by andreenumo** [notracking/hosts-blocklists#893]
Bom dia o script está bloqueando todos os sites .com.br. Praticamente todos os sites que são do Brasil estão bloqueados

Good morning, the script is blocking all .com.br sites. Virtually all websites that are from Brazil are blocked

**Comment by andreenumo** [comment]
Good morning, the script is blocking all .com.br sites. Virtually all websites that are from Brazil are blocked

**Comment by riomccloud** [comment]
The same is happening here. I was unable to access Banco do Brasil (local bank) and TechTudo (local technology news site).

**Comment by scafroglia93** [comment]
it was fixed

**Comment by notracking** [comment]
preventive measure are taken, fixed.
