### ISSUE TITLE
can you please remove www.surveygizmo.com ?

### ISSUE THREAD

**Issue by Retia-Adolf** [notracking/hosts-blocklists#93]
`||www.surveygizmo.com^`

Because a more precise rule is exist in `Fanboy’s Annoyance List`, which is one of uBO's default lists:

`||surveygizmo.com^$third-party`

Also, blocking `surveygizmo.com` breaks `https://qsurvey.mozilla.com/s3/devpanels` (rating wouldn't work unless I uncheck these lists):

![image](https://user-images.githubusercontent.com/34053927/45925329-fcead400-bee0-11e8-81c3-5ff54146334c.png)

**Comment by notracking** [comment]
Hi, thanks for the feedback!

Surveygizmo.com is on the list because of a custom filter and not due to fanboy's list (we only parse full domain filters from adblock based lists). I've remove it from the list, changes will be visible with the next auto update.
