### ISSUE TITLE
is1-ssl.mzstatic.com was blocked in hostname.txt

### ISSUE THREAD

**Issue by ookangzheng** [notracking/hosts-blocklists#99]
it is a address for itunes and appstore

**Comment by notracking** [comment]
I cannot locate it; did you mistype? or do you maybe have it in some other list?

> grep mzstatic.com hostnames.txt 
> 0.0.0.0 dzc-metrics.mzstatic.com
> :: dzc-metrics.mzstatic.com
> 0.0.0.0 metrics.mzstatic.com
> :: metrics.mzstatic.com

**Comment by notracking** [comment]
Lets call this a self repairing issue then, those are the best type of issues ;)
